"""Deterministic leaf ship driver for one umbrella leaf."""

from __future__ import annotations

import argparse
import math
import re
import time
from collections.abc import Callable
from dataclasses import dataclass, replace
from pathlib import Path
from typing import Final

from larch import io as larch_io
from larch.core import config, logging_util, proc, redact, retry, repo_roots
from larch.core.proc import CommandResult, Runner
from larch.errors import ShipError
from larch.git import gh, git, pr_body, push
from larch.implement import ci, ci_monitor
from larch.issue import (
    issue_mutation,
    issue_wire,
    tracking_issue,
)
from larch.state.session_env import is_allowed_session_tmpdir

SleepFn = Callable[[float], None]

_STATE_BASENAME: Final = "complete-umbrella-ship.env"
_STATE_SCHEMA: Final = "1"
_STATE_KEYS: Final = frozenset(
    {
        "SCHEMA",
        "REPOSITORY",
        "UMBRELLA",
        "LEAF",
        "BRANCH",
        "HEAD_SHA",
        "PR_NUMBER",
        "PR_URL",
        "STATUS",
        "CI_ERRORS_FILE",
        "CI_FIX_ATTEMPTS",
        "CONFLICT_FILES",
        "CONFLICT_FIX_ATTEMPTS",
        "MAIN_RECONCILE_ATTEMPTS",
    },
)
_STATE_STATUSES: Final = frozenset(
    {
        "prepared",
        "monitoring",
        "ci_failed",
        "needs_conflict_fix",
        "queued",
        "merged",
        "finalizing",
        "complete",
    },
)
_BRANCH_RE: Final = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._/-]*$")
_HEAD_RE: Final = re.compile(r"^[0-9a-f]{40,64}$")
_CI_ERRORS_RE: Final = re.compile(r"^ci-errors-[0-9]+\.md$")
_CONFLICT_PATH_RE: Final = re.compile(r"^[A-Za-z0-9._][A-Za-z0-9._/-]*$")
_CHIEF_MIGRATION_UMBRELLA_RE: Final = re.compile(
    r"#[1-9][0-9]*(?![0-9])[^\r\n]{0,160}\[CHIEF[ \t]+UMBRELLA\]",
    re.IGNORECASE,
)
_GENERATED_RUST_MARKERS: Final = (
    "@generated",
    "Code generated by",
    "AUTOGENERATED",
)
_NUMSTAT_INTEGER_RE: Final = re.compile(r"^[0-9]+$")
_NUMSTAT_HEADER_PARTS: Final = 3
_PLAN_SIZE_INPUT_BASENAME: Final = "complete-umbrella-plan.txt"
_PLAN_SIZE_RESULT_KEYS: Final = (
    "OVERSIZE_OVERRIDE",
    "PLAN_SIZE_STATUS",
    "SIZE_TRIGGER_FIRED",
    "TRIGGER_REASONS",
)


@dataclass(frozen=True)
class LeafShipRequest:
    repository: str
    repo_root: Path
    handoff_root: Path
    umbrella: int
    leaf: int


@dataclass(frozen=True)
class LeafShipState:
    repository: str
    umbrella: int
    leaf: int
    branch: str = ""
    head_sha: str = ""
    pr_number: int = 0
    pr_url: str = ""
    status: str = "prepared"
    ci_errors_file: str = ""
    ci_fix_attempts: int = 0
    conflict_files: str = ""
    conflict_fix_attempts: int = 0
    main_reconcile_attempts: int = 0


@dataclass(frozen=True)
class LeafShipOutcome:
    status: str
    pr_number: int = 0
    pr_url: str = ""
    ci_errors_file: str = ""
    conflict_files: str = ""
    detail: str = ""


@dataclass(frozen=True)
class LeafPlanAdmission:
    needs_design: bool
    trigger_reasons: tuple[str, ...] = ()


class _LeafPlanNeedsDesign(ShipError):
    """A durable plan contract defect that requires the full design lifecycle."""


@dataclass(frozen=True)
class CiWaitOutcome:
    status: str
    failed_run_id: str = ""


@dataclass(frozen=True)
class MergePrOutcome:
    pull_request: gh.PullRequest
    queued: bool = False


@dataclass(frozen=True)
class ReconcileOutcome:
    """Result of rebasing the leaf branch onto the latest origin/main."""

    status: str
    conflict_files: str = ""
    head_sha: str = ""
    rebased: bool = False


@dataclass(frozen=True)
class ConflictHandoff:
    """Branch identity carried into a needs_conflict_fix ship status."""

    conflict_files: str
    branch: str
    head_sha: str
    pull_request: gh.PullRequest | None


@dataclass(frozen=True)
class NumstatRow:
    """One NUL-delimited git numstat row, preserving rename identity."""

    added: int | None
    deleted: int | None
    old_path: str | None
    new_path: str


@dataclass(frozen=True)
class RustLineBudget:
    """Exact added non-generated Rust count for one feature head."""

    base_sha: str
    head_sha: str
    added_lines: int


@dataclass(frozen=True)
class RustLineBudgetOutcome:
    """Read-only managed-leaf Rust-budget advisory used before review and merge."""

    status: str
    budget: RustLineBudget | None = None


def _detail(text: str) -> str:
    cleaned = redact.redact_outbound(text).replace("\r", " ").replace("\n", " ").strip()
    return cleaned[:500]


def _line_value(value: str, *, label: str) -> str:
    if "\n" in value or "\r" in value:
        raise ShipError(f"{label} contains a line break")
    return value


def _valid_branch(branch: str) -> bool:
    return bool(
        branch
        and branch != "main"
        and _BRANCH_RE.fullmatch(branch)
        and ".." not in branch
        and "//" not in branch
        and "@{" not in branch
        and not branch.endswith(("/", "."))
    )


def _expected_branch(leaf: int) -> str:
    return f"complete-umbrella/leaf-{leaf}"


def _validate_request(request: LeafShipRequest) -> LeafShipRequest:
    if not gh.validate_repo_slug(request.repository):
        raise ShipError("repository must use OWNER/REPO syntax")
    if request.umbrella <= 0 or request.leaf <= 0:
        raise ShipError("umbrella and leaf must be positive integers")
    try:
        repo_root = request.repo_root.resolve(strict=True)
        handoff_root = larch_io.validate_trusted_directory(request.handoff_root)
    except OSError as exc:
        raise ShipError(f"path validation failed: {exc}") from exc
    if not repo_root.is_dir():
        raise ShipError("repo root must be a directory")
    if not is_allowed_session_tmpdir(handoff_root):
        raise ShipError("handoff root is outside the allowed session roots")
    return replace(request, repo_root=repo_root, handoff_root=handoff_root)


def _state_path(request: LeafShipRequest) -> Path:
    return request.handoff_root / _STATE_BASENAME


def _state_rows(state: LeafShipState) -> tuple[tuple[str, str], ...]:
    values: tuple[tuple[str, str], ...] = (
        ("SCHEMA", _STATE_SCHEMA),
        ("REPOSITORY", state.repository),
        ("UMBRELLA", str(state.umbrella)),
        ("LEAF", str(state.leaf)),
        ("BRANCH", state.branch),
        ("HEAD_SHA", state.head_sha),
        ("PR_NUMBER", str(state.pr_number) if state.pr_number else ""),
        ("PR_URL", state.pr_url),
        ("STATUS", state.status),
        ("CI_ERRORS_FILE", state.ci_errors_file),
        ("CI_FIX_ATTEMPTS", str(state.ci_fix_attempts)),
        ("CONFLICT_FILES", state.conflict_files),
        ("CONFLICT_FIX_ATTEMPTS", str(state.conflict_fix_attempts)),
        ("MAIN_RECONCILE_ATTEMPTS", str(state.main_reconcile_attempts)),
    )
    return tuple((key, _line_value(value, label=key)) for key, value in values)


def _write_state(request: LeafShipRequest, state: LeafShipState) -> None:
    _validate_state(request, state)
    text = larch_io.format_kvs(_state_rows(state))
    try:
        larch_io.trusted_atomic_write(
            _state_path(request),
            text,
            root=request.handoff_root,
            mode=0o600,
        )
    except OSError as exc:
        raise ShipError(f"ship state write failed: {exc}") from exc


def _read_state(request: LeafShipRequest) -> LeafShipState | None:
    path = _state_path(request)
    try:
        if not larch_io.trusted_file_present(path, root=request.handoff_root):
            return None
        text = larch_io.read_trusted_text(
            path,
            root=request.handoff_root,
            errors="strict",
            reject_cr=True,
        )
    except (OSError, UnicodeError, ValueError) as exc:
        raise ShipError(f"ship state read failed: {exc}") from exc
    return _parse_state(request, text)


def _parse_state(request: LeafShipRequest, text: str) -> LeafShipState:
    physical_lines = [line for line in text.splitlines() if line]
    if any("=" not in line for line in physical_lines):
        raise ShipError("ship state contains a malformed row")
    parsed = larch_io.parse_kv(text, duplicate_policy="all")
    if set(parsed) != set(_STATE_KEYS) or any(
        len(values) != 1 for values in parsed.values()
    ):
        raise ShipError("ship state has missing, unknown, or duplicate keys")

    def value(key: str) -> str:
        return parsed[key][0]

    if value("SCHEMA") != _STATE_SCHEMA:
        raise ShipError("ship state schema is unsupported")
    try:
        umbrella = int(value("UMBRELLA"))
        leaf = int(value("LEAF"))
        pr_number = int(value("PR_NUMBER") or "0")
        ci_fix_attempts = int(value("CI_FIX_ATTEMPTS"))
        conflict_fix_attempts = int(value("CONFLICT_FIX_ATTEMPTS"))
        main_reconcile_attempts = int(value("MAIN_RECONCILE_ATTEMPTS"))
    except ValueError as exc:
        raise ShipError("ship state contains a non-numeric identity") from exc
    state = LeafShipState(
        repository=value("REPOSITORY"),
        umbrella=umbrella,
        leaf=leaf,
        branch=value("BRANCH"),
        head_sha=value("HEAD_SHA"),
        pr_number=pr_number,
        pr_url=value("PR_URL"),
        status=value("STATUS"),
        ci_errors_file=value("CI_ERRORS_FILE"),
        ci_fix_attempts=ci_fix_attempts,
        conflict_files=value("CONFLICT_FILES"),
        conflict_fix_attempts=conflict_fix_attempts,
        main_reconcile_attempts=main_reconcile_attempts,
    )
    _validate_state(request, state)
    return state


def _validate_state(request: LeafShipRequest, state: LeafShipState) -> None:
    if state.status not in _STATE_STATUSES:
        raise ShipError(f"invalid ship state status: {state.status}")
    _validate_state_identity(request, state)
    _validate_state_pr(request, state)
    _validate_state_ci(request, state)
    _validate_state_conflicts(request, state)


def _validate_state_identity(request: LeafShipRequest, state: LeafShipState) -> None:
    if (
        state.repository != request.repository
        or state.umbrella != request.umbrella
        or state.leaf != request.leaf
    ):
        raise ShipError("ship state identity does not match the live leaf")
    if (
        state.pr_number < 0
        or state.ci_fix_attempts < 0
        or state.conflict_fix_attempts < 0
        or state.main_reconcile_attempts < 0
    ):
        raise ShipError("ship state contains an invalid counter")
    if state.ci_fix_attempts > config.COMPLETE_UMBRELLA_CI_FIX_ATTEMPTS:
        raise ShipError("ship state exceeds the CI fix attempt cap")
    if state.conflict_fix_attempts > config.COMPLETE_UMBRELLA_CONFLICT_FIX_ATTEMPTS:
        raise ShipError("ship state exceeds the conflict fix attempt cap")
    if state.main_reconcile_attempts > config.COMPLETE_UMBRELLA_MAIN_RECONCILE_ATTEMPTS:
        raise ShipError("ship state exceeds the main-reconcile attempt cap")


def _expected_pr_url(state: LeafShipState) -> str:
    return f"https://github.com/{state.repository}/pull/{state.pr_number}"


def _validate_branch_and_head(
    request: LeafShipRequest, state: LeafShipState, *, require_both: bool
) -> None:
    if require_both and (not state.branch or not state.head_sha):
        raise ShipError("conflict ship state lacks branch identity")
    if state.branch and not _valid_branch(state.branch):
        raise ShipError("ship state contains an invalid branch")
    if state.branch and state.branch != _expected_branch(request.leaf):
        raise ShipError("ship state branch does not match the leaf identity")
    if state.head_sha and _HEAD_RE.fullmatch(state.head_sha) is None:
        raise ShipError("ship state contains an invalid head SHA")


def _validate_pr_url_pair(state: LeafShipState) -> None:
    pr_pair = (state.pr_number > 0, bool(state.pr_url))
    if any(pr_pair) and not all(pr_pair):
        raise ShipError("ship state contains a partial PR identity")
    if state.pr_url and state.pr_url != _expected_pr_url(state):
        raise ShipError("ship state contains an invalid PR URL")


def _validate_state_pr(request: LeafShipRequest, state: LeafShipState) -> None:
    if state.status == "needs_conflict_fix":
        _validate_branch_and_head(request, state, require_both=True)
        _validate_pr_url_pair(state)
        return
    pr_identity = (
        bool(state.branch),
        bool(state.head_sha),
        state.pr_number > 0,
        bool(state.pr_url),
    )
    if any(pr_identity) and not all(pr_identity):
        raise ShipError("ship state contains a partial PR identity")
    _validate_branch_and_head(request, state, require_both=False)
    _validate_pr_url_pair(state)
    if state.status != "prepared" and not all(pr_identity):
        raise ShipError("advanced ship state lacks a complete PR identity")


def _validate_state_ci(request: LeafShipRequest, state: LeafShipState) -> None:
    if state.status == "ci_failed":
        _validate_ci_errors_file(request, state.ci_errors_file)
    elif state.ci_errors_file:
        raise ShipError("non-failed ship state contains a CI errors file")


def _validate_state_conflicts(
    request: LeafShipRequest, state: LeafShipState
) -> None:
    del request
    if state.status == "needs_conflict_fix":
        _validate_conflict_files(state.conflict_files)
    elif state.conflict_files:
        raise ShipError("non-conflict ship state contains conflict files")


def _validate_ci_errors_file(request: LeafShipRequest, value: str) -> None:
    path = Path(value)
    if (
        not path.is_absolute()
        or ".." in path.parts
        or _CI_ERRORS_RE.fullmatch(path.name) is None
    ):
        raise ShipError("ship state contains an invalid CI errors file")
    try:
        _ = path.relative_to(request.handoff_root)
        present = larch_io.trusted_file_present(path, root=request.handoff_root)
    except (OSError, ValueError) as exc:
        raise ShipError("ship state contains an unsafe CI errors file") from exc
    if not present:
        raise ShipError("ship state CI errors file is missing")


def _validate_conflict_files(value: str) -> None:
    if not value:
        return
    paths = value.split(",")
    if any(not path or _CONFLICT_PATH_RE.fullmatch(path) is None for path in paths):
        raise ShipError("ship state contains invalid conflict files")
    if len(set(paths)) != len(paths):
        raise ShipError("ship state contains duplicate conflict files")


def _leaf_prefix(umbrella: int) -> str:
    return f"[LEAF OF {umbrella}] "


def _active_leaf_title(title: str, *, umbrella: int) -> str:
    leaf_prefix = _leaf_prefix(umbrella)
    active_prefix = config.TRACKING_ISSUE_PREFIX_BY_STATE["implementing"]
    designed_prefix = config.TRACKING_ISSUE_PREFIX_BY_STATE["designed"]
    active_leaf_prefix = f"{active_prefix}{leaf_prefix}"
    designed_leaf_prefix = f"{designed_prefix}{leaf_prefix}"
    if (
        title.startswith(active_leaf_prefix)
        and title[len(active_leaf_prefix) :].strip()
    ):
        return title
    if title.startswith(leaf_prefix) and title[len(leaf_prefix) :].strip():
        return f"{active_prefix}{title}"
    if (
        title.startswith(designed_leaf_prefix)
        and title[len(designed_leaf_prefix) :].strip()
    ):
        return f"{active_prefix}{title[len(designed_prefix) :]}"
    raise ShipError("leaf title does not have the exact managed leaf prefix")


def _done_leaf_title(title: str, *, umbrella: int) -> str:
    leaf_prefix = _leaf_prefix(umbrella)
    active_prefix = config.TRACKING_ISSUE_PREFIX_BY_STATE["implementing"]
    done_prefix = config.TRACKING_ISSUE_PREFIX_BY_STATE["done"]
    active_leaf_prefix = f"{active_prefix}{leaf_prefix}"
    done_leaf_prefix = f"{done_prefix}{leaf_prefix}"
    if title.startswith(done_leaf_prefix) and title[len(done_leaf_prefix) :].strip():
        return title
    if (
        title.startswith(active_leaf_prefix)
        and title[len(active_leaf_prefix) :].strip()
    ):
        return f"{done_prefix}{title[len(active_prefix) :]}"
    raise ShipError("leaf title is not in the active managed lifecycle")


def _is_chief_migration_umbrella(runner: Runner, request: LeafShipRequest) -> bool:
    """Return whether this managed umbrella declares a chief-migration parent."""
    parent = issue_mutation.read_snapshot(
        runner,
        repository=request.repository,
        issue=str(request.umbrella),
        cwd=str(request.repo_root),
    )
    return _CHIEF_MIGRATION_UMBRELLA_RE.search(parent.body) is not None


def _require_leaf_plan(
    runner: Runner,
    request: LeafShipRequest,
    *,
    issue_body: str,
) -> str:
    """Validate and return durable M1/M2 plan evidence before implementation."""
    result = issue_wire.validate_issue_plan(
        issue_body=issue_body,
        repo_root=request.repo_root,
        tracked_paths=frozenset(git.ls_files(runner, cwd=str(request.repo_root))),
    )
    if not result.ok:
        raise _LeafPlanNeedsDesign(
            "complete-umbrella leaf requires a valid issue plan: "
            + ",".join(result.defects)
        )
    plan_inner, malformed = issue_wire.parse_named_block(body=issue_body, marker="plan")
    if plan_inner is None or malformed:
        raise _LeafPlanNeedsDesign("validated leaf plan could not be materialized")
    return plan_inner


def _plan_size_fields(stdout: str) -> dict[str, str]:
    parsed = larch_io.parse_kv(
        stdout,
        duplicate_policy="all",
        allowed_keys=_PLAN_SIZE_RESULT_KEYS,
    )
    fields: dict[str, str] = {}
    for key in _PLAN_SIZE_RESULT_KEYS:
        values = parsed.get(key, [])
        if len(values) != 1:
            raise ShipError(f"plan size preflight returned invalid {key}")
        fields[key] = values[0]
    if fields["PLAN_SIZE_STATUS"] != "ok":
        raise ShipError("plan size preflight did not return ok")
    if fields["SIZE_TRIGGER_FIRED"] not in {"true", "false"}:
        raise ShipError("plan size preflight returned an invalid trigger")
    if fields["OVERSIZE_OVERRIDE"]:
        raise ShipError("plan size preflight accepted an untrusted override")
    return fields


def _assess_leaf_plan(
    runner: Runner,
    request: LeafShipRequest,
    *,
    issue_body: str,
) -> LeafPlanAdmission:
    """Apply the canonical size gate before the thin implementation phase."""
    plan_inner = _require_leaf_plan(runner, request, issue_body=issue_body)
    plan_path = request.handoff_root / _PLAN_SIZE_INPUT_BASENAME
    try:
        larch_io.trusted_atomic_write(
            plan_path,
            plan_inner,
            root=request.handoff_root,
            mode=0o600,
        )
    except OSError as exc:
        raise ShipError(f"plan size input write failed: {exc}") from exc
    entrypoint = repo_roots.larch_entrypoint(Path(__file__).resolve().parents[3])
    checked = runner.run(
        [
            str(entrypoint),
            "plan",
            "check-size",
            "--design-tmpdir",
            str(request.handoff_root),
            "--plan-file",
            str(plan_path),
        ],
        cwd=str(request.repo_root),
    )
    if checked.returncode != 0:
        raise ShipError("plan size preflight failed")
    fields = _plan_size_fields(checked.stdout)
    reasons = tuple(reason for reason in fields["TRIGGER_REASONS"].split(",") if reason)
    return LeafPlanAdmission(
        needs_design=fields["SIZE_TRIGGER_FIRED"] == "true",
        trigger_reasons=reasons,
    )


def _parse_numstat_count(value: str) -> int | None:
    if value == "-":
        return None
    if _NUMSTAT_INTEGER_RE.fullmatch(value) is None:
        raise ShipError("Rust line budget numstat output has an invalid count")
    return int(value)


def _parse_numstat_z(output: str) -> tuple[NumstatRow, ...]:
    """Parse `git diff --numstat -z` rows, including the rename form."""
    if output and not output.endswith("\0"):
        raise ShipError("Rust line budget numstat output is not NUL terminated")
    fields = output.split("\0")
    rows: list[NumstatRow] = []
    index = 0
    while index + 1 < len(fields):
        header = fields[index]
        if not header:
            raise ShipError("Rust line budget numstat output has an empty row")
        parts = header.split("\t", _NUMSTAT_HEADER_PARTS - 1)
        if len(parts) != _NUMSTAT_HEADER_PARTS:
            raise ShipError("Rust line budget numstat output is malformed")
        added_text, deleted_text, path = parts
        added = _parse_numstat_count(added_text)
        deleted = _parse_numstat_count(deleted_text)
        if path:
            rows.append(
                NumstatRow(
                    added=added,
                    deleted=deleted,
                    old_path=None,
                    new_path=path,
                )
            )
            index += 1
            continue
        if index + 3 >= len(fields):
            raise ShipError("Rust line budget rename numstat output is truncated")
        old_path = fields[index + 1]
        new_path = fields[index + 2]
        if not old_path or not new_path:
            raise ShipError("Rust line budget rename numstat output is malformed")
        rows.append(
            NumstatRow(
                added=added,
                deleted=deleted,
                old_path=old_path,
                new_path=new_path,
            )
        )
        index += 3
    return tuple(rows)


def _is_generated_rust_source(
    runner: Runner,
    *,
    head_sha: str,
    path: str,
    cwd: str,
) -> bool:
    result = git.show_file(runner, f"{head_sha}:{path}", cwd=cwd)
    if result.returncode != 0:
        raise ShipError("Rust line budget could not read the changed source")
    return any(
        marker in line
        for line in result.stdout.splitlines()[:40]
        for marker in _GENERATED_RUST_MARKERS
    )


def _measure_rust_line_budget(
    runner: Runner,
    request: LeafShipRequest,
    *,
    head_sha: str,
) -> RustLineBudget:
    """Count added Rust lines from the merge base with fixed rename semantics."""
    cwd = str(request.repo_root)
    base_sha = git.merge_base(runner, "origin/main", head_sha, cwd=cwd)
    diff = git.diff_numstat_z(
        runner,
        base_sha,
        head_sha,
        find_renames=True,
        cwd=cwd,
    )
    if diff.returncode != 0:
        raise ShipError("Rust line budget diff failed")
    added_lines = 0
    for row in _parse_numstat_z(diff.stdout):
        if not row.new_path.endswith(".rs") or row.added == 0:
            continue
        if row.added is None:
            raise ShipError("Rust line budget cannot measure a binary Rust diff")
        if _is_generated_rust_source(
            runner,
            head_sha=head_sha,
            path=row.new_path,
            cwd=cwd,
        ):
            continue
        added_lines += row.added
    return RustLineBudget(
        base_sha=base_sha,
        head_sha=head_sha,
        added_lines=added_lines,
    )


def _rust_line_budget_outcome(
    runner: Runner,
    request: LeafShipRequest,
    *,
    head_sha: str,
) -> RustLineBudgetOutcome:
    if not _is_chief_migration_umbrella(runner, request):
        return RustLineBudgetOutcome(status="not-managed")
    budget = _measure_rust_line_budget(runner, request, head_sha=head_sha)
    if budget.added_lines <= config.MANAGED_LEAF_RUST_LINE_LIMIT:
        return RustLineBudgetOutcome(status="within-limit", budget=budget)
    return RustLineBudgetOutcome(status="over-limit", budget=budget)


def prepare_leaf(
    runner: Runner,
    request: LeafShipRequest,
) -> LeafShipOutcome:
    request = _validate_request(request)
    snapshot = issue_mutation.read_snapshot(
        runner,
        repository=request.repository,
        issue=str(request.leaf),
        cwd=str(request.repo_root),
    )
    if snapshot.state.upper() != "OPEN":
        raise ShipError("leaf must be open before implementation starts")
    try:
        admission = _assess_leaf_plan(
            runner,
            request,
            issue_body=snapshot.body,
        )
    except _LeafPlanNeedsDesign:
        return LeafShipOutcome(
            status="needs-design",
            detail=f"run /design {request.leaf} before implementation (plan-contract)",
        )
    if admission.needs_design:
        reasons = ",".join(admission.trigger_reasons) or "plan-size"
        return LeafShipOutcome(
            status="needs-design",
            detail=f"run /design {request.leaf} before implementation ({reasons})",
        )
    title = _active_leaf_title(snapshot.title, umbrella=request.umbrella)
    if title != snapshot.title:
        mutation = issue_mutation.apply(
            runner,
            issue_mutation.request_for_snapshot(
                snapshot,
                fields=frozenset({issue_mutation.MutationField.TITLE}),
                title=title,
            ),
            cwd=str(request.repo_root),
        )
        if mutation.after.title != title:
            raise ShipError("active leaf title read-back failed")
    state = LeafShipState(
        repository=request.repository,
        umbrella=request.umbrella,
        leaf=request.leaf,
    )
    existing = _read_state(request)
    if existing is not None and existing.pr_number:
        state = existing
    _write_state(request, state)
    return LeafShipOutcome(
        status="prepared",
        pr_number=state.pr_number,
        pr_url=state.pr_url,
    )


def _push_branch(
    runner: Runner,
    request: LeafShipRequest,
    *,
    force: bool = False,
) -> tuple[str, str]:
    cwd = str(request.repo_root)
    push.assert_clean_worktree(runner, cwd=cwd)
    branch = git.current_branch(runner, cwd=cwd)
    if branch != _expected_branch(request.leaf):
        raise ShipError("leaf implementation is not on its exact managed branch")
    head_sha = git.rev_parse(runner, "HEAD", cwd=cwd)
    remote = git.remote_branch_state(runner, branch, cwd=cwd)
    use_force = force and remote.state == "present"

    def attempt() -> tuple[CommandResult, int, str]:
        if use_force:
            result = git.force_push_with_lease(
                runner, "origin", f"HEAD:refs/heads/{branch}", cwd=cwd
            )
        else:
            result = git.push_set_upstream(runner, "origin", "HEAD", cwd=cwd)
        return result, result.returncode, result.stdout + result.stderr

    pushed = retry.with_transient_retry(attempt).value
    if pushed.returncode != 0:
        raise ShipError("feature branch push failed")
    return branch, head_sha


def _abort_rebase_idempotent(runner: Runner, *, cwd: str) -> None:
    if not git.rebase_in_progress(runner, cwd=cwd):
        return
    aborted = git.rebase(runner, "--abort", cwd=cwd)
    if aborted.returncode != 0 and git.rebase_in_progress(runner, cwd=cwd):
        raise ShipError("could not abort an in-progress rebase")


def _normalize_conflict_files(raw: str) -> str:
    cleaned = raw.strip().replace("\r", "").replace("\n", "")
    if not cleaned:
        return ""
    paths = [part for part in cleaned.split(",") if part]
    for path in paths:
        if _CONFLICT_PATH_RE.fullmatch(path) is None:
            raise ShipError("rebase reported an invalid conflict path")
    if len(set(paths)) != len(paths):
        raise ShipError("rebase reported duplicate conflict paths")
    return ",".join(paths)


def _reconcile_onto_main(
    runner: Runner,
    request: LeafShipRequest,
) -> ReconcileOutcome:
    """Fetch origin/main and rebase the leaf branch, handing conflicts off."""
    cwd = str(request.repo_root)
    push.assert_clean_worktree(runner, cwd=cwd)
    if git.rebase_in_progress(runner, cwd=cwd):
        raise ShipError("cannot reconcile while a rebase is already in progress")
    branch = git.current_branch(runner, cwd=cwd)
    if branch != _expected_branch(request.leaf):
        raise ShipError("leaf implementation is not on its exact managed branch")

    def fetch_attempt() -> tuple[CommandResult, int, str]:
        result = git.fetch(runner, "origin", "main", cwd=cwd)
        return result, result.returncode, result.stdout + result.stderr

    fetched = retry.with_transient_retry(fetch_attempt).value
    if fetched.returncode != 0:
        raise ShipError("could not fetch origin/main before leaf reconcile")

    if git.is_ancestor(runner, "origin/main", "HEAD", cwd=cwd):
        head_sha = git.rev_parse(runner, "HEAD", cwd=cwd)
        return ReconcileOutcome(status="clean", head_sha=head_sha, rebased=False)

    entrypoint = repo_roots.larch_entrypoint(Path(__file__).resolve().parents[3])
    rebased = runner.run(
        [
            str(entrypoint),
            "push",
            "rebase",
            "--no-push",
            "--keep-on-conflict",
            "--base-remote",
            "origin",
            "--base-ref",
            "main",
        ],
        cwd=cwd,
    )
    if rebased.returncode == 0:
        head_sha = git.rev_parse(runner, "HEAD", cwd=cwd)
        if _HEAD_RE.fullmatch(head_sha) is None:
            raise ShipError("reconcile produced an invalid head SHA")
        return ReconcileOutcome(status="clean", head_sha=head_sha, rebased=True)

    fields = larch_io.parse_kv(
        rebased.stdout,
        duplicate_policy="last",
        allowed_keys={"CONFLICT_FILES"},
    )
    conflict_files = _normalize_conflict_files(fields.get("CONFLICT_FILES", ""))
    if rebased.returncode == 1 and (
        conflict_files or git.rebase_in_progress(runner, cwd=cwd)
    ):
        return ReconcileOutcome(
            status="conflict",
            conflict_files=conflict_files,
            rebased=True,
        )
    _abort_rebase_idempotent(runner, cwd=cwd)
    return ReconcileOutcome(status="failed")


def _force_push_reconciled_head(
    runner: Runner,
    request: LeafShipRequest,
    *,
    branch: str,
) -> str:
    cwd = str(request.repo_root)
    push.assert_clean_worktree(runner, cwd=cwd)
    if git.rebase_in_progress(runner, cwd=cwd):
        raise ShipError("cannot push while a rebase is still in progress")
    head_sha = git.rev_parse(runner, "HEAD", cwd=cwd)
    if _HEAD_RE.fullmatch(head_sha) is None:
        raise ShipError("reconciled head SHA is invalid")

    def attempt() -> tuple[CommandResult, int, str]:
        result = git.force_push_with_lease(
            runner, "origin", f"HEAD:refs/heads/{branch}", cwd=cwd
        )
        return result, result.returncode, result.stdout + result.stderr

    pushed = retry.with_transient_retry(attempt).value
    if pushed.returncode != 0:
        raise ShipError("force-push after main reconcile failed")
    return head_sha


def _conflict_fix_outcome(
    runner: Runner,
    request: LeafShipRequest,
    state: LeafShipState,
    handoff: ConflictHandoff,
) -> tuple[LeafShipState, LeafShipOutcome]:
    if state.conflict_fix_attempts >= config.COMPLETE_UMBRELLA_CONFLICT_FIX_ATTEMPTS:
        _abort_rebase_idempotent(runner, cwd=str(request.repo_root))
        raise ShipError("complete-umbrella conflict fix attempt cap reached")
    pull_request = handoff.pull_request
    pr_number = pull_request.number if pull_request is not None else state.pr_number
    pr_url = pull_request.url if pull_request is not None else state.pr_url
    next_state = replace(
        state,
        branch=handoff.branch,
        head_sha=handoff.head_sha,
        pr_number=pr_number,
        pr_url=pr_url,
        status="needs_conflict_fix",
        ci_errors_file="",
        conflict_files=handoff.conflict_files,
    )
    _write_state(request, next_state)
    return next_state, LeafShipOutcome(
        status="needs_conflict_fix",
        pr_number=next_state.pr_number,
        pr_url=next_state.pr_url,
        conflict_files=handoff.conflict_files,
        detail="leaf branch conflicts with origin/main; resolve via MODE=conflict",
    )


def _default_pr_body(request: LeafShipRequest) -> str:
    body = (
        "## Summary\n\n"
        f"- Implement leaf #{request.leaf} of umbrella #{request.umbrella}.\n"
    )
    return tracking_issue.link_pr_closes(body=body, issue_number=request.leaf)


def _pr_title(runner: Runner, request: LeafShipRequest) -> str:
    subject = git.log_subject(runner, "HEAD", cwd=str(request.repo_root))
    summary = subject or f"Implement umbrella leaf #{request.leaf}"
    prefix = f"Fixes #{request.leaf}: "
    title = summary if summary.startswith(prefix) else f"{prefix}{summary}"
    return _line_value(title[:250], label="PR title")


def _ensure_pr_body(
    runner: Runner,
    request: LeafShipRequest,
    pull_request: gh.PullRequest,
) -> None:
    cwd = str(request.repo_root)
    remote_body = gh.pr_view_body(
        runner,
        pull_request.number,
        repo=request.repository,
        cwd=cwd,
    )
    if remote_body is None:
        raise ShipError("could not read the PR body for closing-link verification")
    linked = tracking_issue.link_pr_closes(body=remote_body, issue_number=request.leaf)
    if linked.rstrip() != remote_body.rstrip():
        raise ShipError("existing PR body lacks the required leaf closing link")


def _require_main_base(
    runner: Runner,
    request: LeafShipRequest,
    *,
    pr_number: int,
) -> None:
    base_ref = gh.pr_base_ref(
        runner,
        pr_number,
        repo=request.repository,
        cwd=str(request.repo_root),
    )
    if base_ref != "main":
        raise ShipError("implementation PR does not target main")


def _require_pr_head(
    runner: Runner,
    request: LeafShipRequest,
    *,
    pr_number: int,
    head_sha: str,
) -> gh.MergeState:
    state = gh.pr_merge_state(
        runner,
        pr_number,
        repo=request.repository,
        cwd=str(request.repo_root),
    )
    if state.head_ref_oid != head_sha:
        raise ShipError("PR head changed after the verified push")
    return state


def _ensure_pr(
    runner: Runner,
    request: LeafShipRequest,
    *,
    branch: str,
    state: LeafShipState,
) -> gh.PullRequest:
    cwd = str(request.repo_root)
    pull_request: gh.PullRequest | None = None
    if state.pr_number:
        pull_request = gh.pr_view(
            runner,
            state.pr_number,
            repo=request.repository,
            cwd=cwd,
        )
        if pull_request.head_ref != branch:
            raise ShipError(
                "persisted PR no longer belongs to the implementation branch"
            )
    if pull_request is None:
        pull_request = gh.pr_for_branch(
            runner,
            branch,
            repo=request.repository,
            cwd=cwd,
        )
    if pull_request is None:
        body = pr_body.redact_pr_body(_default_pr_body(request))
        pull_request, _created = gh.pr_create(
            runner,
            repo=request.repository,
            branch=branch,
            title=_pr_title(runner, request),
            body=body,
            base="main",
            assignee=None,
            draft=False,
            cwd=cwd,
        )
    if pull_request.state.upper() not in {"OPEN", "MERGED"}:
        raise ShipError("implementation PR is closed without a merge")
    if pull_request.head_ref != branch:
        raise ShipError("implementation PR branch read-back failed")
    _require_main_base(runner, request, pr_number=pull_request.number)
    _ensure_pr_body(runner, request, pull_request)
    return pull_request


def _wait_for_ci(
    runner: Runner,
    request: LeafShipRequest,
    *,
    pr_number: int,
    sleep_fn: SleepFn,
) -> CiWaitOutcome:
    interval = config.COMPLETE_UMBRELLA_CI_POLL_INTERVAL_SEC
    max_polls = max(1, math.ceil(config.COMPLETE_UMBRELLA_CI_TIMEOUT_SEC / interval))
    cwd = str(request.repo_root)
    for poll_index in range(max_polls):
        status, failed_run_id = ci_monitor.checks_status(
            runner,
            pr=pr_number,
            repo=request.repository,
            empty_checks_grace=0,
            required=False,
            cwd=cwd,
            sleep_fn=sleep_fn,
        )
        if status == "pass":
            return CiWaitOutcome(status="pass")
        if status == "fail":
            run_id = failed_run_id or ci_monitor.resolve_failed_run_id_once(
                runner,
                pr=pr_number,
                repo=request.repository,
                cwd=cwd,
            )
            return CiWaitOutcome(status="fail", failed_run_id=run_id or "")
        if status not in {"pending", "empty", "NO_CHECKS", ""}:
            raise ShipError(f"CI returned an unsupported status: {status}")
        if poll_index + 1 >= max_polls:
            break
        sleep_fn(float(interval))
    raise ShipError("CI did not complete within the leaf ship timeout")


def _distill_ci_failure(
    runner: Runner,
    request: LeafShipRequest,
    *,
    run_id: str,
    sleep_fn: SleepFn,
) -> Path:
    if not run_id.isdigit():
        raise ShipError("failed CI did not expose a numeric Actions run id")
    output = request.handoff_root / f"ci-errors-{run_id}.md"
    for attempt in range(config.COMPLETE_UMBRELLA_CI_LOG_READY_ATTEMPTS):
        outcome = ci.distill_log_to_root(
            runner=runner,
            run_id=run_id,
            repo=request.repository,
            output=output,
            trusted_root=request.handoff_root,
        )
        if outcome.status == "ok":
            return output
        if outcome.status != "in_progress":
            raise ShipError(f"CI log distill failed: {outcome.bail_class}")
        if attempt + 1 < config.COMPLETE_UMBRELLA_CI_LOG_READY_ATTEMPTS:
            sleep_fn(float(config.COMPLETE_UMBRELLA_CI_POLL_INTERVAL_SEC))
    raise ShipError("failed CI logs did not become ready")


def _warn_if_rust_line_budget_exceeded(
    runner: Runner,
    request: LeafShipRequest,
    *,
    head_sha: str,
    pr_number: int,
) -> None:
    budget_outcome = _rust_line_budget_outcome(runner, request, head_sha=head_sha)
    if budget_outcome.status != "over-limit":
        return
    budget = budget_outcome.budget
    if budget is None:
        raise ShipError("over-limit Rust line-budget result lacks its measurement")
    logging_util.diagnostic(
        "WARNING: managed Chief leaf "
        f"#{request.leaf}, PR #{pr_number}, exceeds the Rust line budget "
        f"({budget.added_lines} added non-generated Rust lines; "
        f"limit {config.MANAGED_LEAF_RUST_LINE_LIMIT}); continuing with warning."
    )


def _merge_pr(
    runner: Runner,
    request: LeafShipRequest,
    *,
    pull_request: gh.PullRequest,
    head_sha: str,
    sleep_fn: SleepFn,
) -> MergePrOutcome:
    cwd = str(request.repo_root)
    state = _require_pr_head(
        runner,
        request,
        pr_number=pull_request.number,
        head_sha=head_sha,
    )
    if pull_request.state.upper() == "MERGED":
        return MergePrOutcome(pull_request=pull_request)
    _require_main_base(runner, request, pr_number=pull_request.number)
    if state.merge_state_status not in config.ADMIN_ELIGIBLE_MERGE_STATES:
        raise ShipError(f"PR is not admin-merge eligible: {state.merge_state_status}")
    if not gh.pr_checks_all_pass(
        runner,
        pull_request.number,
        repo=request.repository,
        cwd=cwd,
    ):
        raise ShipError("CI changed after the green pre-merge check")
    _warn_if_rust_line_budget_exceeded(
        runner,
        request,
        head_sha=head_sha,
        pr_number=pull_request.number,
    )

    queue_enabled = gh.default_branch_merge_queue_enabled(
        runner,
        repo=request.repository,
        cwd=cwd,
    )

    def attempt() -> tuple[CommandResult, int, str]:
        result = gh.pr_merge(
            runner,
            pull_request.number,
            repo=request.repository,
            merge_method="squash",
            admin=not queue_enabled,
            delete_branch=not queue_enabled,
            merge_queue=queue_enabled,
            cwd=cwd,
        )
        return result, result.returncode, result.stdout + result.stderr

    merged = retry.with_transient_retry(attempt, sleeper=sleep_fn).value
    if merged.returncode != 0:
        action = "merge queue submission" if queue_enabled else "admin merge"
        raise ShipError(f"{action} failed")
    if queue_enabled:
        _ = gh.confirm_pr_merge_queue_submission(
            runner,
            pull_request.number,
            repo=request.repository,
            sleeper=sleep_fn,
            cwd=cwd,
        )
    read_back = gh.pr_view(
        runner,
        pull_request.number,
        repo=request.repository,
        cwd=cwd,
    )
    if queue_enabled and read_back.state.upper() == "OPEN":
        return MergePrOutcome(pull_request=read_back, queued=True)
    if read_back.state.upper() != "MERGED":
        raise ShipError("merged PR read-back failed")
    return MergePrOutcome(pull_request=read_back)


def _wait_for_queued_merge(
    runner: Runner,
    request: LeafShipRequest,
    state: LeafShipState,
    *,
    sleep_fn: SleepFn,
) -> LeafShipState:
    if not state.pr_number:
        raise ShipError("queued ship state lacks a PR number")
    _require_main_base(runner, request, pr_number=state.pr_number)
    _ = _require_pr_head(
        runner,
        request,
        pr_number=state.pr_number,
        head_sha=state.head_sha,
    )
    merged = ci_monitor.wait_for_pr_merge(
        runner,
        pr=state.pr_number,
        repo=request.repository,
        sleep_fn=sleep_fn,
        cwd=str(request.repo_root),
    )
    if merged.head_ref != state.branch:
        raise ShipError("queued PR branch identity changed")
    completed = replace(
        state,
        status="merged",
        pr_url=merged.url,
        ci_errors_file="",
    )
    _write_state(request, completed)
    return completed


def _finish_leaf_issue(
    runner: Runner,
    request: LeafShipRequest,
    *,
    sleep_fn: SleepFn,
) -> None:
    cwd = str(request.repo_root)
    snapshot = issue_mutation.read_snapshot(
        runner,
        repository=request.repository,
        issue=str(request.leaf),
        cwd=cwd,
    )
    title = _done_leaf_title(snapshot.title, umbrella=request.umbrella)
    if title != snapshot.title:
        mutation = issue_mutation.update_title(
            runner,
            repository=request.repository,
            issue=str(request.leaf),
            title=title,
            cwd=cwd,
        )
        snapshot = mutation.after
    for attempt in range(config.COMPLETE_UMBRELLA_ISSUE_CLOSE_ATTEMPTS):
        if snapshot.state.upper() == "CLOSED" and snapshot.title == title:
            return
        if attempt + 1 < config.COMPLETE_UMBRELLA_ISSUE_CLOSE_ATTEMPTS:
            sleep_fn(float(config.COMPLETE_UMBRELLA_ISSUE_CLOSE_POLL_INTERVAL_SEC))
            snapshot = issue_mutation.read_snapshot(
                runner,
                repository=request.repository,
                issue=str(request.leaf),
                cwd=cwd,
            )
    raise ShipError("leaf issue did not auto-close after the PR merge")


def _sync_main(
    runner: Runner,
    request: LeafShipRequest,
) -> None:
    cwd = str(request.repo_root)
    push.assert_clean_worktree(runner, cwd=cwd)
    current = git.current_branch(runner, cwd=cwd)
    if current != "main":
        switched = git.switch_branch(runner, "main", cwd=cwd)
        if switched.returncode != 0:
            raise ShipError("could not switch to main after merge")

    def fetch_attempt() -> tuple[CommandResult, int, str]:
        result = git.fetch(runner, "origin", "main", cwd=cwd)
        return result, result.returncode, result.stdout + result.stderr

    fetched = retry.with_transient_retry(fetch_attempt).value
    if fetched.returncode != 0:
        raise ShipError("could not fetch origin/main after merge")
    rebased = git.rebase(runner, "origin/main", cwd=cwd)
    if rebased.returncode != 0:
        aborted = git.rebase(runner, "--abort", cwd=cwd)
        if aborted.returncode != 0:
            raise ShipError("main rebase failed and could not be aborted")
        raise ShipError("could not rebase local main onto origin/main")
    push.assert_clean_worktree(runner, cwd=cwd)
    if git.rev_parse(runner, "HEAD", cwd=cwd) != git.rev_parse(
        runner, "origin/main", cwd=cwd
    ):
        raise ShipError("local main does not match origin/main after rebase")


def _delete_branch(
    runner: Runner,
    request: LeafShipRequest,
    *,
    branch: str,
) -> None:
    cwd = str(request.repo_root)
    if git.local_branch_exists(runner, branch, cwd=cwd):
        deleted = git.delete_branch(runner, branch, force=True, cwd=cwd)
        if deleted.returncode != 0:
            raise ShipError("could not delete the local implementation branch")
    remote = git.remote_branch_state(runner, branch, cwd=cwd)
    if remote.state == "present":
        deleted_remote = git.push(runner, "origin", f":refs/heads/{branch}", cwd=cwd)
        if deleted_remote.returncode != 0:
            raise ShipError("could not delete the remote implementation branch")
        remote = git.remote_branch_state(runner, branch, cwd=cwd)
    if remote.state != "absent":
        raise ShipError("remote implementation branch deletion did not verify")
    if git.local_branch_exists(runner, branch, cwd=cwd):
        raise ShipError("local implementation branch deletion did not verify")


def _sync_main_and_delete_branch(
    runner: Runner,
    request: LeafShipRequest,
    *,
    branch: str,
) -> None:
    if not _valid_branch(branch):
        raise ShipError("cannot clean up an invalid implementation branch")
    _sync_main(runner, request)
    _delete_branch(runner, request, branch=branch)


def _verify_complete(
    runner: Runner,
    request: LeafShipRequest,
    state: LeafShipState,
) -> None:
    if not state.pr_number or not _valid_branch(state.branch):
        raise ShipError("complete ship state lacks PR or branch identity")
    cwd = str(request.repo_root)
    pull_request = gh.pr_view(
        runner,
        state.pr_number,
        repo=request.repository,
        cwd=cwd,
    )
    if pull_request.state.upper() != "MERGED" or pull_request.head_ref != state.branch:
        raise ShipError("complete ship state does not match the merged PR")
    _require_main_base(runner, request, pr_number=state.pr_number)
    _ = _require_pr_head(
        runner,
        request,
        pr_number=state.pr_number,
        head_sha=state.head_sha,
    )
    issue = issue_mutation.read_snapshot(
        runner,
        repository=request.repository,
        issue=str(request.leaf),
        cwd=cwd,
    )
    expected_title = _done_leaf_title(issue.title, umbrella=request.umbrella)
    if issue.state.upper() != "CLOSED" or issue.title != expected_title:
        raise ShipError("leaf issue is not closed with the exact done title")
    if git.current_branch(runner, cwd=cwd) != "main":
        raise ShipError("repository is not on main after leaf shipping")
    push.assert_clean_worktree(runner, cwd=cwd)
    if git.rev_parse(runner, "HEAD", cwd=cwd) != git.rev_parse(
        runner, "origin/main", cwd=cwd
    ):
        raise ShipError("local main is not synchronized after leaf shipping")
    if git.local_branch_exists(runner, state.branch, cwd=cwd):
        raise ShipError("local implementation branch still exists")
    remote = git.remote_branch_state(runner, state.branch, cwd=cwd)
    if remote.state != "absent":
        raise ShipError("remote implementation branch still exists")


def _merged_reentry_state(
    runner: Runner,
    request: LeafShipRequest,
    state: LeafShipState,
) -> LeafShipState | None:
    if not state.pr_number:
        return None
    persisted_pr = gh.pr_view(
        runner,
        state.pr_number,
        repo=request.repository,
        cwd=str(request.repo_root),
    )
    if persisted_pr.head_ref != state.branch:
        raise ShipError("persisted PR branch identity changed")
    if persisted_pr.state.upper() != "MERGED":
        if state.status in {"merged", "finalizing"}:
            raise ShipError("persisted postmerge state contradicts the live PR")
        return None
    if not _valid_branch(state.branch):
        raise ShipError("merged ship state lacks a valid branch")
    _require_main_base(runner, request, pr_number=state.pr_number)
    _ = _require_pr_head(
        runner,
        request,
        pr_number=state.pr_number,
        head_sha=state.head_sha,
    )
    merged = replace(
        state,
        status="merged",
        pr_url=persisted_pr.url,
        ci_errors_file="",
        conflict_files="",
    )
    _write_state(request, merged)
    return merged


def _require_leaf_head(
    runner: Runner,
    request: LeafShipRequest,
    *,
    expected_head: str,
    unchanged_error: str,
) -> str:
    cwd = str(request.repo_root)
    branch = git.current_branch(runner, cwd=cwd)
    if branch != _expected_branch(request.leaf):
        raise ShipError("leaf implementation is not on its exact managed branch")
    head_sha = git.rev_parse(runner, "HEAD", cwd=cwd)
    if head_sha == expected_head:
        raise ShipError(unchanged_error)
    return head_sha


def _begin_ci_fix_reentry(
    runner: Runner,
    request: LeafShipRequest,
    state: LeafShipState,
) -> tuple[LeafShipState, bool]:
    _ = _require_leaf_head(
        runner,
        request,
        expected_head=state.head_sha,
        unchanged_error="CI failed but no fixer commit changed the branch head",
    )
    if state.ci_fix_attempts >= config.COMPLETE_UMBRELLA_CI_FIX_ATTEMPTS:
        raise ShipError("complete-umbrella CI fix attempt cap reached")
    return (
        replace(
            state,
            ci_fix_attempts=state.ci_fix_attempts + 1,
            conflict_files="",
        ),
        True,
    )


def _begin_conflict_fix_reentry(
    runner: Runner,
    request: LeafShipRequest,
    state: LeafShipState,
) -> tuple[LeafShipState, bool]:
    cwd = str(request.repo_root)
    if git.rebase_in_progress(runner, cwd=cwd):
        raise ShipError("conflict fix left a rebase in progress")
    _ = _require_leaf_head(
        runner,
        request,
        expected_head=state.head_sha,
        unchanged_error="conflict fix did not change the branch head",
    )
    if state.conflict_fix_attempts >= config.COMPLETE_UMBRELLA_CONFLICT_FIX_ATTEMPTS:
        raise ShipError("complete-umbrella conflict fix attempt cap reached")
    return (
        replace(
            state,
            conflict_fix_attempts=state.conflict_fix_attempts + 1,
            conflict_files="",
            ci_errors_file="",
        ),
        True,
    )


def _handoff_reconcile_conflict(  # noqa: PLR0913 - conflict handoff carries optional live PR/branch identity overlays
    runner: Runner,
    request: LeafShipRequest,
    state: LeafShipState,
    reconcile: ReconcileOutcome,
    *,
    pull_request: gh.PullRequest | None = None,
    branch: str | None = None,
    head_sha: str | None = None,
) -> tuple[LeafShipState, LeafShipOutcome]:
    cwd = str(request.repo_root)
    live_branch = branch or git.current_branch(runner, cwd=cwd)
    live_head = head_sha or git.rev_parse(runner, "HEAD", cwd=cwd)
    live_pr = pull_request
    if live_pr is None and state.pr_number:
        live_pr = gh.pr_view(
            runner,
            state.pr_number,
            repo=request.repository,
            cwd=cwd,
        )
    return _conflict_fix_outcome(
        runner,
        request,
        state,
        ConflictHandoff(
            conflict_files=reconcile.conflict_files,
            branch=live_branch,
            head_sha=live_head,
            pull_request=live_pr,
        ),
    )


def _note_clean_reconcile(
    state: LeafShipState, reconcile: ReconcileOutcome
) -> tuple[LeafShipState, bool]:
    if reconcile.status != "clean":
        raise ShipError("could not reconcile the leaf branch onto origin/main")
    if not reconcile.rebased:
        return state, False
    if state.main_reconcile_attempts >= config.COMPLETE_UMBRELLA_MAIN_RECONCILE_ATTEMPTS:
        raise ShipError("complete-umbrella main-reconcile attempt cap reached")
    return (
        replace(
            state,
            main_reconcile_attempts=state.main_reconcile_attempts + 1,
            conflict_files="",
        ),
        True,
    )


def _persist_monitoring_state(
    request: LeafShipRequest,
    state: LeafShipState,
    *,
    branch: str,
    head_sha: str,
    pull_request: gh.PullRequest,
) -> LeafShipState:
    next_state = replace(
        state,
        branch=branch,
        head_sha=head_sha,
        pr_number=pull_request.number,
        pr_url=pull_request.url,
        status="monitoring",
        ci_errors_file="",
        conflict_files="",
    )
    _write_state(request, next_state)
    return next_state


def _ci_failure_outcome(
    runner: Runner,
    request: LeafShipRequest,
    state: LeafShipState,
    *,
    failed_run_id: str,
    sleep_fn: SleepFn,
) -> tuple[LeafShipState, LeafShipOutcome]:
    errors_file = _distill_ci_failure(
        runner,
        request,
        run_id=failed_run_id,
        sleep_fn=sleep_fn,
    )
    next_state = replace(
        state,
        status="ci_failed",
        ci_errors_file=str(errors_file),
        conflict_files="",
    )
    _write_state(request, next_state)
    if next_state.ci_fix_attempts >= config.COMPLETE_UMBRELLA_CI_FIX_ATTEMPTS:
        raise ShipError("complete-umbrella CI fix attempt cap reached after failed CI")
    return next_state, LeafShipOutcome(
        status="ci_failed",
        pr_number=next_state.pr_number,
        pr_url=next_state.pr_url,
        ci_errors_file=next_state.ci_errors_file,
    )


def _recover_dirty_pr(  # noqa: PLR0913 - dirty recovery needs the verified PR head identity
    runner: Runner,
    request: LeafShipRequest,
    state: LeafShipState,
    *,
    branch: str,
    head_sha: str,
    pull_request: gh.PullRequest,
) -> tuple[LeafShipState, LeafShipOutcome | None, bool]:
    dirty = _reconcile_onto_main(runner, request)
    if dirty.status == "conflict":
        handed = _handoff_reconcile_conflict(
            runner,
            request,
            state,
            dirty,
            pull_request=pull_request,
            branch=branch,
            head_sha=head_sha,
        )
        return handed[0], handed[1], False
    if dirty.status != "clean" or not dirty.rebased:
        raise ShipError("PR is DIRTY but reconcile did not produce a rebased head")
    if state.main_reconcile_attempts >= config.COMPLETE_UMBRELLA_MAIN_RECONCILE_ATTEMPTS:
        raise ShipError("complete-umbrella main-reconcile attempt cap reached")
    new_head = _force_push_reconciled_head(runner, request, branch=branch)
    next_state = replace(
        state,
        head_sha=new_head,
        status="monitoring",
        ci_errors_file="",
        conflict_files="",
        main_reconcile_attempts=state.main_reconcile_attempts + 1,
    )
    _write_state(request, next_state)
    return next_state, None, True


def _finish_merge_attempt(  # noqa: PLR0913 - merge finish needs the verified PR head and sleeper
    runner: Runner,
    request: LeafShipRequest,
    state: LeafShipState,
    *,
    pull_request: gh.PullRequest,
    head_sha: str,
    sleep_fn: SleepFn,
) -> tuple[LeafShipState, LeafShipOutcome | None]:
    merge_outcome = _merge_pr(
        runner,
        request,
        pull_request=pull_request,
        head_sha=head_sha,
        sleep_fn=sleep_fn,
    )
    if merge_outcome.queued:
        queued = replace(
            state,
            status="queued",
            pr_url=merge_outcome.pull_request.url,
        )
        _write_state(request, queued)
        return _wait_for_queued_merge(
            runner,
            request,
            queued,
            sleep_fn=sleep_fn,
        ), None
    merged = replace(
        state,
        status="merged",
        pr_url=merge_outcome.pull_request.url,
    )
    _write_state(request, merged)
    return merged, None


def _run_premerge(  # noqa: C901 - ship premerge owns reentry, reconcile, CI, dirty recovery, and merge routing
    runner: Runner,
    request: LeafShipRequest,
    state: LeafShipState,
    *,
    sleep_fn: SleepFn,
) -> tuple[LeafShipState, LeafShipOutcome | None]:
    force_push = False
    if state.status == "ci_failed":
        state, force_push = _begin_ci_fix_reentry(runner, request, state)
    elif state.status == "needs_conflict_fix":
        state, force_push = _begin_conflict_fix_reentry(runner, request, state)

    for _ in range(config.COMPLETE_UMBRELLA_MAIN_RECONCILE_ATTEMPTS + 1):
        reconcile = _reconcile_onto_main(runner, request)
        if reconcile.status == "conflict":
            return _handoff_reconcile_conflict(runner, request, state, reconcile)
        state, rebased = _note_clean_reconcile(state, reconcile)
        if rebased:
            force_push = True

        branch, head_sha = _push_branch(runner, request, force=force_push)
        force_push = False
        if state.branch and state.branch != branch:
            raise ShipError("implementation branch changed after leaf preparation")
        pull_request = _ensure_pr(runner, request, branch=branch, state=state)
        state = _persist_monitoring_state(
            request,
            state,
            branch=branch,
            head_sha=head_sha,
            pull_request=pull_request,
        )
        ci_wait = _wait_for_ci(
            runner,
            request,
            pr_number=pull_request.number,
            sleep_fn=sleep_fn,
        )
        if ci_wait.status == "fail":
            return _ci_failure_outcome(
                runner,
                request,
                state,
                failed_run_id=ci_wait.failed_run_id,
                sleep_fn=sleep_fn,
            )

        merge_state = _require_pr_head(
            runner,
            request,
            pr_number=pull_request.number,
            head_sha=head_sha,
        )
        if merge_state.merge_state_status == "DIRTY":
            state, early, retry = _recover_dirty_pr(
                runner,
                request,
                state,
                branch=branch,
                head_sha=head_sha,
                pull_request=pull_request,
            )
            if early is not None:
                return state, early
            if retry:
                continue

        return _finish_merge_attempt(
            runner,
            request,
            state,
            pull_request=pull_request,
            head_sha=head_sha,
            sleep_fn=sleep_fn,
        )

    raise ShipError("complete-umbrella main-reconcile attempt cap reached")


def ship_leaf(
    runner: Runner,
    request: LeafShipRequest,
    *,
    sleep_fn: SleepFn = time.sleep,
) -> LeafShipOutcome:
    request = _validate_request(request)
    state = _read_state(request)
    if state is None:
        raise ShipError("leaf prepare phase has not initialized ship state")
    if state.status == "complete":
        _verify_complete(runner, request, state)
        return LeafShipOutcome(
            status="complete", pr_number=state.pr_number, pr_url=state.pr_url
        )

    merged_state = _merged_reentry_state(runner, request, state)
    if merged_state is None:
        if state.status == "queued":
            state = _wait_for_queued_merge(
                runner,
                request,
                state,
                sleep_fn=sleep_fn,
            )
        else:
            state, early_outcome = _run_premerge(
                runner,
                request,
                state,
                sleep_fn=sleep_fn,
            )
            if early_outcome is not None:
                return early_outcome
    else:
        state = merged_state

    _finish_leaf_issue(runner, request, sleep_fn=sleep_fn)
    _sync_main_and_delete_branch(runner, request, branch=state.branch)
    state = replace(
        state, status="finalizing", ci_errors_file="", conflict_files=""
    )
    _write_state(request, state)
    _verify_complete(runner, request, state)
    state = replace(state, status="complete")
    _write_state(request, state)
    verified = _read_state(request)
    if verified != state:
        raise ShipError("complete ship marker read-back failed")
    return LeafShipOutcome(
        status="complete",
        pr_number=state.pr_number,
        pr_url=state.pr_url,
    )


def verify_leaf(
    runner: Runner,
    request: LeafShipRequest,
) -> LeafShipOutcome:
    request = _validate_request(request)
    state = _read_state(request)
    if state is None or state.status != "complete":
        raise ShipError("leaf ship state is not complete")
    _verify_complete(runner, request, state)
    return LeafShipOutcome(
        status="complete", pr_number=state.pr_number, pr_url=state.pr_url
    )


def line_budget_leaf(
    runner: Runner,
    request: LeafShipRequest,
) -> RustLineBudgetOutcome:
    """Report the current branch's managed-chief Rust line-budget status."""
    request = _validate_request(request)
    head_sha = git.rev_parse(runner, "HEAD", cwd=str(request.repo_root))
    if _HEAD_RE.fullmatch(head_sha) is None:
        raise ShipError("Rust line budget head SHA is invalid")
    return _rust_line_budget_outcome(runner, request, head_sha=head_sha)


def _emit(outcome: LeafShipOutcome) -> None:
    logging_util.emit_kv(key="SHIP_STATUS", value=outcome.status)
    logging_util.emit_kv(
        key="PR_NUMBER", value=str(outcome.pr_number) if outcome.pr_number else ""
    )
    logging_util.emit_kv(key="PR_URL", value=outcome.pr_url)
    logging_util.emit_kv(key="CI_ERRORS_FILE", value=outcome.ci_errors_file)
    logging_util.emit_kv(key="CONFLICT_FILES", value=outcome.conflict_files)
    logging_util.emit_kv(key="DETAIL", value=_detail(outcome.detail))


def _emit_line_budget(outcome: RustLineBudgetOutcome) -> None:
    budget = outcome.budget
    logging_util.emit_kv(key="RUST_LINE_BUDGET_STATUS", value=outcome.status)
    logging_util.emit_kv(
        key="RUST_LINE_BUDGET_LIMIT",
        value=str(config.MANAGED_LEAF_RUST_LINE_LIMIT),
    )
    logging_util.emit_kv(
        key="RUST_LINE_BUDGET_ADDED_LINES",
        value=str(budget.added_lines) if budget is not None else "",
    )
    logging_util.emit_kv(
        key="RUST_LINE_BUDGET_BASE_SHA",
        value=budget.base_sha if budget is not None else "",
    )
    logging_util.emit_kv(
        key="RUST_LINE_BUDGET_HEAD_SHA",
        value=budget.head_sha if budget is not None else "",
    )


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="cli.py complete-umbrella ship-leaf")
    _ = parser.add_argument(
        "--mode",
        choices=(
            "prepare",
            "ship",
            "verify",
            "line-budget",
        ),
        required=True,
    )
    _ = parser.add_argument("--repository", required=True)
    _ = parser.add_argument("--repo-root", required=True)
    _ = parser.add_argument("--handoff-root", required=True)
    _ = parser.add_argument("--umbrella", required=True, type=int)
    _ = parser.add_argument("--leaf", required=True, type=int)
    try:
        args = parser.parse_args(argv)
    except SystemExit as exc:
        return int(exc.code) if isinstance(exc.code, int) else config.EXIT_USAGE
    request = LeafShipRequest(
        repository=str(args.repository),
        repo_root=Path(args.repo_root),
        handoff_root=Path(args.handoff_root),
        umbrella=int(args.umbrella),
        leaf=int(args.leaf),
    )
    try:
        if args.mode == "prepare":
            outcome = prepare_leaf(proc, request)
        elif args.mode == "ship":
            outcome = ship_leaf(proc, request)
        elif args.mode == "verify":
            outcome = verify_leaf(proc, request)
        else:
            budget_outcome = line_budget_leaf(proc, request)
            _emit_line_budget(budget_outcome)
            return config.EXIT_OK
    except (OSError, ShipError, ValueError) as exc:
        _emit(LeafShipOutcome(status="error", detail=str(exc)))
        return config.EXIT_INTERNAL_ERROR
    _emit(outcome)
    return config.EXIT_OK
