#!/usr/bin/env bash
# /design session env — generated by write-design-current-env.sh. Do not edit.
export DESIGN_TMPDIR=<TMPDIR>
export SESSION_TMPDIR=<TMPDIR>
export SESSION_ID=C3F210EC-3D6B-4F27-956E-07611E72BBC1
export CODEX_PRESENT=true
export CURSOR_PRESENT=false
export CODEX_AVAILABLE=true
export CURSOR_AVAILABLE=false
export CLAUDE_PLUGIN_ROOT=<OPERATOR_REPO_PATH>/plugins/cache/larch-local/larch/42.4.9
