#!/usr/bin/env bash
# /design session env — generated by write-design-current-env.sh. Do not edit.
export DESIGN_TMPDIR=<TMPDIR>
export SESSION_TMPDIR=<TMPDIR>
export SESSION_ID=20B78C02-0777-48FF-902D-FE250DB1558F
export ISSUE_NUMBER=3292
export CODEX_PRESENT=false
export CURSOR_PRESENT=true
export CODEX_AVAILABLE=false
export CURSOR_AVAILABLE=true
export CLAUDE_PLUGIN_ROOT=<OPERATOR_REPO_PATH>/plugins/cache/larch-local/larch/47.0.27
