mod support;

use predicates::prelude::*;
use support::TempRepo;

#[test]
fn rejects_cross_module_normalized_duplicates() {
    let repository = TempRepo::new();
    let body = r"pub fn duplicated_block(input: i32) -> i32 {
    let mut total = input;
    total = total.saturating_add(1);
    total = total.saturating_add(2);
    total = total.saturating_add(3);
    total = total.saturating_add(4);
    total = total.saturating_add(5);
    total = total.saturating_add(6);
    total = total.saturating_add(7);
    total = total.saturating_add(8);
    total
}
";
    repository.write("src/a.rs", body.as_bytes());
    repository.write("src/b.rs", body.as_bytes());
    repository.commit_all();

    TempRepo::command_from(repository.path())
        .args(["rule", "duplicate-code"])
        .assert()
        .code(1)
        .stdout(predicate::str::contains(
            "src/a.rs:1: duplicate production block",
        ))
        .stdout(predicate::str::contains("src/b.rs:1"))
        .stderr(predicate::str::is_empty());
}

#[test]
fn ignores_imports_formatting_comments_tests_and_generated_code() {
    let repository = TempRepo::new();
    let production = r"use std::collections::BTreeMap;

pub fn keep(input: i32) -> i32 {
    // formatting and comments should not matter
    input.saturating_add(1)
}
";
    let reformatted = r"use std::fs;

pub fn keep(input:i32)->i32{input.saturating_add(1)}
";
    let generated = r"// @generated by fixture
pub fn keep(input: i32) -> i32 {
    let mut total = input;
    total = total.saturating_add(1);
    total = total.saturating_add(2);
    total = total.saturating_add(3);
    total = total.saturating_add(4);
    total = total.saturating_add(5);
    total = total.saturating_add(6);
    total = total.saturating_add(7);
    total = total.saturating_add(8);
    total
}
";
    let tests = r"#[cfg(test)]
mod tests {
    pub fn keep(input: i32) -> i32 {
        let mut total = input;
        total = total.saturating_add(1);
        total = total.saturating_add(2);
        total = total.saturating_add(3);
        total = total.saturating_add(4);
        total = total.saturating_add(5);
        total = total.saturating_add(6);
        total = total.saturating_add(7);
        total = total.saturating_add(8);
        total
    }
}
";
    repository.write("src/a.rs", production.as_bytes());
    repository.write("src/b.rs", reformatted.as_bytes());
    repository.write("src/generated.rs", generated.as_bytes());
    repository.write("src/lib.rs", tests.as_bytes());
    repository.commit_all();

    TempRepo::command_from(repository.path())
        .args(["rule", "duplicate-code"])
        .assert()
        .success()
        .stdout(predicate::str::is_empty())
        .stderr(predicate::str::is_empty());
}
