"""larch.debate: pure debate protocol types, parsing, and fingerprints."""

from __future__ import annotations

from larch.debate.protocol import (
    ACTION_AGREE,
    ACTION_CONCEDE,
    ACTION_HOLD,
    ACTION_TOKENS,
    ARTIFACT_CITATION_PREFIX,
    ARTIFACT_CITATION_SUFFIX,
    FINGERPRINT_ALGORITHM_VERSION,
    FINGERPRINT_HEX_LENGTH,
    LEDGER_POINT_TOKEN,
    POINT_ID_MAX,
    POINT_ID_MIN,
    POINT_ID_PREFIX,
    PROTOCOL_VERSION,
    ROUND_LIMIT,
    SLOT_ORDER,
    SLOT_SET,
    Action,
    ConcessionClassification,
    LedgerRow,
    ParseRejectionReason,
    ParsedSlotLedger,
    Participant,
    PointId,
    ProtocolRejection,
    ReasonFingerprint,
    classify_concession,
    fingerprint_reason,
    is_valid_artifact_path,
    is_valid_fingerprint,
    is_valid_fingerprint_version,
    is_valid_point_token,
    is_valid_protocol_version,
    is_valid_slot,
    normalize_reason_for_fingerprint,
    parse_fingerprint,
    parse_fingerprint_version,
    parse_protocol_version,
    parse_slot,
    parse_slot_ledger,
    reject_forbidden_plan_content,
)

# Stateful orchestration is intentionally available only by explicit import.
# Keep __all__ below protocol-only so ``from larch.debate import *`` cannot
# accidentally expose transition implementation details.
from larch.debate.orchestrator import (
    ActiveRound,
    DebateError,
    DropRecord,
    InitializationContext,
    ParticipantSlot,
    ProposalState,
    RestoreMetadata,
    SessionBootstrapper,
    TurnRequest,
    TurnResult,
    TurnRunner,
    abort,
    abort_main,
    init_main,
    initialize,
    load_state,
    record_turn,
    record_turn_main,
    round_prep,
    round_prep_main,
    write_state,
)

# These direct names are deliberately outside __all__: explicit imports are the
# supported facade while wildcard imports remain protocol-only.
_ORCHESTRATOR_FACADE = (
    ActiveRound, DebateError, DropRecord, InitializationContext, ParticipantSlot,
    ProposalState, RestoreMetadata, SessionBootstrapper, TurnRequest, TurnResult,
    TurnRunner, abort, abort_main, init_main, initialize, load_state, record_turn,
    record_turn_main, round_prep, round_prep_main, write_state,
)

__all__ = [
    "ACTION_AGREE",
    "ACTION_CONCEDE",
    "ACTION_HOLD",
    "ACTION_TOKENS",
    "ARTIFACT_CITATION_PREFIX",
    "ARTIFACT_CITATION_SUFFIX",
    "FINGERPRINT_ALGORITHM_VERSION",
    "FINGERPRINT_HEX_LENGTH",
    "LEDGER_POINT_TOKEN",
    "POINT_ID_MAX",
    "POINT_ID_MIN",
    "POINT_ID_PREFIX",
    "PROTOCOL_VERSION",
    "ROUND_LIMIT",
    "SLOT_ORDER",
    "SLOT_SET",
    "Action",
    "ConcessionClassification",
    "LedgerRow",
    "ParseRejectionReason",
    "ParsedSlotLedger",
    "Participant",
    "PointId",
    "ProtocolRejection",
    "ReasonFingerprint",
    "classify_concession",
    "fingerprint_reason",
    "is_valid_artifact_path",
    "is_valid_fingerprint",
    "is_valid_fingerprint_version",
    "is_valid_point_token",
    "is_valid_protocol_version",
    "is_valid_slot",
    "normalize_reason_for_fingerprint",
    "parse_fingerprint",
    "parse_fingerprint_version",
    "parse_protocol_version",
    "parse_slot",
    "parse_slot_ledger",
    "reject_forbidden_plan_content",
]
