# pyright: reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnusedCallResult=false, reportOptionalSubscript=false, reportOptionalMemberAccess=false, reportPossiblyUnboundVariable=false, reportUnnecessaryComparison=false, reportUnknownLambdaType=false, reportArgumentType=false
"""Tests for alias helper entrypoints."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from larch.core import alias_skill
from larch.core import proc

PUBLIC_STYLE_LINE = "**MANDATORY — READ ENTIRE FILE before composing user-facing prose: `${CLAUDE_PLUGIN_ROOT}/skills/shared/readability-style.md`.**"
DEV_STYLE_LINE = "**MANDATORY — READ ENTIRE FILE before composing user-facing prose: `$PWD/skills/shared/readability-style.md`.**"


def _result(argv: list[str], returncode: int = 0, stdout: str = "", stderr: str = "") -> proc.CommandResult:
    return proc.CommandResult(tuple(argv), returncode, stdout, stderr, 0.0)


def test_resolve_target_plugin_and_private(monkeypatch: Any, tmp_path: Path, capsys: Any) -> None:
    (tmp_path / ".claude-plugin").mkdir()
    (tmp_path / ".claude-plugin/plugin.json").write_text("{}", encoding="utf-8")
    (tmp_path / "skills/implement").mkdir(parents=True)
    (tmp_path / "skills/implement/SKILL.md").write_text("x", encoding="utf-8")

    monkeypatch.setattr(alias_skill.proc, "run", lambda argv, **_: _result(argv, stdout=f"{tmp_path}\n"))
    assert alias_skill.resolve_target_main(["--alias-name", "my-alias"]) == 0
    assert f"TARGET_DIR={tmp_path}/skills/my-alias" in capsys.readouterr().out
    assert alias_skill.resolve_target_main(["--alias-name", "my-alias", "--private"]) == 0
    assert f"TARGET_DIR={tmp_path}/.claude/skills/my-alias" in capsys.readouterr().out


def test_resolve_target_requires_git_repo(monkeypatch: Any, capsys: Any) -> None:
    monkeypatch.setattr(
        alias_skill.proc,
        "run",
        lambda argv, **_: _result(argv, returncode=128, stderr="fatal: not a git repository\n"),
    )
    assert alias_skill.resolve_target_main(["--alias-name", "my-alias"]) == 1
    assert "ERROR: not in a git repository" in capsys.readouterr().err


def test_resolve_target_non_plugin_repo_routes_private(monkeypatch: Any, tmp_path: Path, capsys: Any) -> None:
    repo = tmp_path / "consumer"
    repo.mkdir()
    monkeypatch.setattr(alias_skill.proc, "run", lambda argv, **_: _result(argv, stdout=f"{repo}\n"))
    assert alias_skill.resolve_target_main(["--alias-name", "my-alias"]) == 0
    out = capsys.readouterr().out
    assert "PLUGIN_REPO=false" in out
    assert f"TARGET_DIR={repo}/.claude/skills/my-alias" in out


def test_generate_yaml_escapes(capsys: Any) -> None:
    assert alias_skill.generate_main([
        "--name",
        "q",
        "--target",
        "implement",
        "--target-dir",
        "/tmp/repo/skills/q",
        "--flags",
        '--foo "bar"',
        "--version",
        "1.2.3",
    ]) == 0
    out = capsys.readouterr().out
    assert 'description: "Alias for /implement --foo \\"bar\\" (created by /alias)"' in out
    assert '/q <arguments> is equivalent to /implement --foo "bar" <arguments>' in out
    assert "allowed-tools: Read, Skill" in out
    assert PUBLIC_STYLE_LINE in out
    assert "Generated by larch /alias v1.2.3" in out


def test_generate_yaml_chooses_public_or_dev_style(capsys: Any) -> None:
    assert alias_skill.generate_main([
        "--name",
        "q",
        "--target",
        "implement",
        "--target-dir",
        "/tmp/repo/.claude/skills/q",
        "--version",
        "",
    ]) == 0
    dev_out = capsys.readouterr().out
    assert DEV_STYLE_LINE in dev_out

    assert alias_skill.generate_main([
        "--name",
        "q",
        "--target",
        "implement",
        "--target-dir",
        "/tmp/repo/skills/q",
        "--version",
        "",
    ]) == 0
    public_out = capsys.readouterr().out
    assert PUBLIC_STYLE_LINE in public_out
