#!/usr/bin/env bash
# /design session env — generated by write-design-current-env.sh. Do not edit.
export DESIGN_TMPDIR=<TMPDIR>
export SESSION_TMPDIR=<TMPDIR>
export SESSION_ID=FE4F9460-14BB-494F-AD5C-D6C32E7BF49E
export ISSUE_NUMBER=2868
export CODEX_PRESENT=true
export CURSOR_PRESENT=true
export CODEX_AVAILABLE=true
export CURSOR_AVAILABLE=true
export CLAUDE_PLUGIN_ROOT=<OPERATOR_REPO_PATH>/plugins/cache/larch-local/larch/45.0.0
