#!/usr/bin/env bash
# generate-alias.sh — Generate a SKILL.md file for an alias skill.
#
# Usage:
#   generate-alias.sh --name <alias-name> --target <target-skill> --flags "<preset-flags>" --version <version>
#
# Output (stdout): The complete SKILL.md content for the alias skill.
#
# Exit codes: 0 success, 1 invalid args

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT:-$(cd "$SCRIPT_DIR/../../.." && pwd -P)}"
# shellcheck source=scripts/lib-quiet.sh
source "$PLUGIN_ROOT/scripts/lib-quiet.sh"
larch_quiet_init
# This script emits only SKILL.md content; route all output to original stdout.
[ "${LARCH_QUIET_PID:-}" = "$$" ] && exec 1>&3

NAME=""
TARGET=""
FLAGS=""
VERSION=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name)   NAME="$2";    shift 2 ;;
    --target) TARGET="$2";  shift 2 ;;
    --flags)  FLAGS="$2";   shift 2 ;;
    --version) VERSION="$2"; shift 2 ;;
    *) larch_err "ERROR: Unknown argument: $1"; exit 1 ;;
  esac
done

if [[ -z "$NAME" || -z "$TARGET" ]]; then
  larch_err "ERROR: --name and --target are required"
  exit 1
fi

# Escape description for YAML frontmatter (wrap in double quotes, escape inner quotes)
ESCAPED_FLAGS="${FLAGS//\"/\\\"}"
if [[ -n "$FLAGS" ]]; then
  DESC="Alias for /${TARGET} ${ESCAPED_FLAGS} (created by /alias)"
else
  DESC="Alias for /${TARGET} (created by /alias)"
fi

# Build the usage equivalence line
if [[ -n "$FLAGS" ]]; then
  USAGE_LINE="/${NAME} <arguments> is equivalent to /${TARGET} ${FLAGS} <arguments>"
  BEHAVIOR_ARGS="${FLAGS} \$ARGUMENTS"
else
  USAGE_LINE="/${NAME} <arguments> is equivalent to /${TARGET} <arguments>"
  BEHAVIOR_ARGS="\$ARGUMENTS"
fi

# Build version footer
if [[ -n "$VERSION" ]]; then
  VERSION_LINE="Generated by larch /alias v${VERSION}"
else
  VERSION_LINE="Generated by larch /alias"
fi

# Use single-quoted heredoc to prevent $ARGUMENTS expansion
cat <<'HEREDOC_START'
---
HEREDOC_START

echo "name: ${NAME}"
echo "description: \"${DESC}\""
echo "argument-hint: \"<arguments>\""
echo "allowed-tools: Skill"

cat <<'HEREDOC_MID'
---

HEREDOC_MID

cat <<HEREDOC_BODY
Auto-generated alias created by larch /alias. Invokes /${TARGET} with preset flags.

## Usage

${USAGE_LINE}

## Behavior

Invoke the Skill tool:
- Try skill: "${TARGET}" first (bare name). If no skill matches, try skill: "larch:${TARGET}" (fully-qualified plugin name).
- args: ${BEHAVIOR_ARGS}
HEREDOC_BODY

if [[ "$TARGET" == "implement" ]]; then
  cat <<'HEREDOC_IMPLEMENT'

After the Skill tool loads /implement, the child skill MUST begin execution at its Step 0 (session setup). Do not investigate the codebase, plan, or implement anything before Step 0 completes.
HEREDOC_IMPLEMENT
fi

cat <<HEREDOC_FOOTER

${VERSION_LINE}
HEREDOC_FOOTER
