#!/usr/bin/env bash
# /design session env — generated by write-design-current-env.sh. Do not edit.
export DESIGN_TMPDIR=<TMPDIR>
export SESSION_TMPDIR=<TMPDIR>
export SESSION_ID=4A4F7B69-9EF5-4B05-B3B7-404248BAF6C7
export ISSUE_NUMBER=3246
export CODEX_PRESENT=true
export CURSOR_PRESENT=true
export CODEX_AVAILABLE=true
export CURSOR_AVAILABLE=true
export CLAUDE_PLUGIN_ROOT=<OPERATOR_REPO_PATH>/plugins/cache/larch-local/larch/47.0.35
