#!/usr/bin/env bash
# /design session env — generated by write-design-current-env.sh. Do not edit.
export DESIGN_TMPDIR=<TMPDIR>
export SESSION_TMPDIR=<TMPDIR>
export SESSION_ID=A40575AC-C174-4AE1-BA38-AD7477D06079
export ISSUE_NUMBER=3550
export CODEX_PRESENT=false
export CURSOR_PRESENT=true
export CODEX_AVAILABLE=false
export CURSOR_AVAILABLE=true
export LARCH_EXTERNAL_HEALTH_CHECK_TIMEOUT=30
export CLAUDE_PLUGIN_ROOT=<OPERATOR_REPO_PATH>/plugins/cache/larch-local/larch/47.0.70
