#!/usr/bin/env bash
# /design session env — generated by write-design-current-env.sh. Do not edit.
export DESIGN_TMPDIR=<TMPDIR>
export SESSION_TMPDIR=<TMPDIR>
export SESSION_ID=657071F3-B85A-4B8C-8705-BBA2232EC915
export ISSUE_NUMBER=3227
export CODEX_PRESENT=false
export CURSOR_PRESENT=true
export CODEX_AVAILABLE=false
export CURSOR_AVAILABLE=true
export CLAUDE_PLUGIN_ROOT=<OPERATOR_REPO_PATH>/plugins/cache/larch-local/larch/47.0.9
