[package]
name = "larch-core"
version.workspace = true
description = "Domain types and ports for larch"
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
zip.workspace = true

[dev-dependencies]

[lints]
workspace = true
