#!/usr/bin/env bash
# /design session env — generated by write-design-current-env.sh. Do not edit.
export DESIGN_TMPDIR=<TMPDIR>
export SESSION_TMPDIR=<TMPDIR>
export SESSION_ID=6704F1D4-D8F1-4B69-B4FD-6B9AC94A4F34
export ISSUE_NUMBER=2971
export CLAUDE_PLUGIN_ROOT=<OPERATOR_REPO_PATH>/plugins/cache/larch-local/larch/45.0.0
export CODEX_PRESENT=true
export CURSOR_PRESENT=true
