#!/usr/bin/env bash
# /design session env — generated by write-design-current-env.sh. Do not edit.
export DESIGN_TMPDIR=<TMPDIR>
export SESSION_TMPDIR=<TMPDIR>
export SESSION_ID=A9846A4A-0AC3-4F90-996C-AC0BE3A569E4
export ISSUE_NUMBER=2867
export CODEX_PRESENT=true
export CURSOR_PRESENT=true
export CODEX_AVAILABLE=true
export CURSOR_AVAILABLE=true
export CLAUDE_PLUGIN_ROOT=<OPERATOR_REPO_PATH>/plugins/cache/larch-local/larch/42.5.22
