#!/usr/bin/env bash
# /design session env — generated by write-design-current-env.sh. Do not edit.
export DESIGN_TMPDIR="<TMPDIR>"
export SESSION_TMPDIR="<TMPDIR>"
export SESSION_ID=D0AA77AB-FC57-4372-8BBD-65500C0F2928
export CODEX_PRESENT=true
export CURSOR_PRESENT=true
export CODEX_AVAILABLE=true
export CURSOR_AVAILABLE=true
