//! Normalized Rust duplicate-code detector for production sources.
//!
//! The rule lexes kept production items into a comment-free token stream,
//! ignores formatting and imports, skips generated and test code, skips
//! `impl Rule for …` registration boilerplate, and reports exact cross-module
//! clone families at or above the token threshold. There is no baseline: any
//! reported family fails the gate.

use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::hash::{Hash, Hasher};

use proc_macro2::{Delimiter, TokenStream, TokenTree};
use syn::spanned::Spanned;
use syn::{Attribute, Item};

use crate::syntax::RustSyntax;
use crate::{Finding, LintError, Repository, Rule, RuleMetadata, RuleOutput};

use super::path_discovery;

const NAME: &str = "duplicate-code";
const DESCRIPTION: &str =
    "Reject normalized duplicate production Rust blocks across modules";
const MIN_TOKENS: usize = 50;
const GENERATED_MARKERS: &[&str] = &["@generated", "Code generated by", "AUTOGENERATED"];

pub static METADATA: RuleMetadata = RuleMetadata::new(
    NAME,
    DESCRIPTION,
    "crates/larch-lint/migration-ledger/duplicate-code.toml",
);

#[derive(Debug)]
pub struct DuplicateCodeRule;

pub static RULE: DuplicateCodeRule = DuplicateCodeRule;

impl Rule for DuplicateCodeRule {
    fn name(&self) -> &'static str {
        NAME
    }

    fn description(&self) -> &'static str {
        DESCRIPTION
    }

    fn check(&self, repository: &Repository) -> Result<RuleOutput, LintError> {
        let mut sequences = Vec::new();
        for path in path_discovery::selected_rust_sources(repository)? {
            if path_discovery::is_test_path(path.as_str()) {
                continue;
            }
            let source = repository.read_utf8(path)?;
            if is_generated_source(&source) {
                continue;
            }
            sequences.extend(production_token_sequences(path.as_str(), &source)?);
        }
        Ok(RuleOutput::from_findings(find_cross_module_clones(
            &sequences,
            MIN_TOKENS,
        )))
    }
}

crate::register_rule!(METADATA, RULE);

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct NormToken(String);

#[derive(Clone, Debug, Eq, PartialEq)]
struct LocatedToken {
    token: NormToken,
    line: u32,
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct FileSequence {
    path: String,
    tokens: Vec<LocatedToken>,
}

#[derive(Clone, Debug, Eq, Ord, PartialEq, PartialOrd)]
struct CloneMember {
    path: String,
    line: u32,
    token_count: usize,
}

type SequencePair = (usize, usize);
type CloneSpan = (usize, usize, usize);

fn production_token_sequences(
    path: &str,
    source: &str,
) -> Result<Vec<FileSequence>, LintError> {
    let syntax = RustSyntax::parse(path, source)?;
    let line_starts = line_start_offsets(source);
    let mut sequences = Vec::new();
    for item in &syntax.file().items {
        if should_skip_item(item) {
            continue;
        }
        let span = item.span();
        let slice = source_slice_for_span(source, &line_starts, span)?;
        let stream = parse_token_stream(path, slice)?;
        let line_offset = span.start().line.saturating_sub(1);
        let mut tokens = Vec::new();
        flatten_stream(&stream, &mut tokens, line_offset);
        if tokens.len() < MIN_TOKENS {
            continue;
        }
        sequences.push(FileSequence {
            path: path.to_owned(),
            tokens,
        });
    }
    Ok(sequences)
}

fn should_skip_item(item: &Item) -> bool {
    match item {
        Item::Use(_) | Item::ExternCrate(_) => true,
        Item::Impl(item) if is_rule_impl(item) || has_cfg_test(&item.attrs) => true,
        Item::Mod(module) if has_cfg_test(&module.attrs) => true,
        Item::Fn(function) if is_test_function(&function.attrs) => true,
        Item::Struct(item) if has_cfg_test(&item.attrs) => true,
        Item::Enum(item) if has_cfg_test(&item.attrs) => true,
        Item::Trait(item) if has_cfg_test(&item.attrs) => true,
        Item::Const(item) if has_cfg_test(&item.attrs) => true,
        Item::Static(item) if has_cfg_test(&item.attrs) => true,
        Item::Type(item) if has_cfg_test(&item.attrs) => true,
        Item::Macro(item) if has_cfg_test(&item.attrs) => true,
        _ => false,
    }
}

fn is_rule_impl(item: &syn::ItemImpl) -> bool {
    item.trait_.as_ref().is_some_and(|(_, path, _)| {
        path.segments
            .last()
            .is_some_and(|segment| segment.ident == "Rule")
    })
}

fn is_test_function(attrs: &[Attribute]) -> bool {
    has_cfg_test(attrs)
        || attrs
            .iter()
            .any(|attr| attr.path().is_ident("test") || path_ends_with(attr, "test"))
}

fn path_ends_with(attr: &Attribute, name: &str) -> bool {
    attr.path()
        .segments
        .last()
        .is_some_and(|segment| segment.ident == name)
}

fn has_cfg_test(attrs: &[Attribute]) -> bool {
    attrs.iter().any(|attr| match &attr.meta {
        syn::Meta::List(list) if list.path.is_ident("cfg") => list
            .tokens
            .to_string()
            .split(|byte: char| !byte.is_ascii_alphanumeric() && byte != '_')
            .any(|token| token == "test"),
        _ => false,
    })
}

fn is_generated_source(source: &str) -> bool {
    source
        .lines()
        .take(40)
        .any(|line| GENERATED_MARKERS.iter().any(|marker| line.contains(marker)))
}

fn parse_token_stream(path: &str, slice: &str) -> Result<TokenStream, LintError> {
    slice
        .parse::<TokenStream>()
        .map_err(|error| LintError::new(format!("{path}: invalid token stream: {error}")))
}

fn flatten_stream(stream: &TokenStream, tokens: &mut Vec<LocatedToken>, line_offset: usize) {
    for tree in stream.clone() {
        flatten_tree(&tree, tokens, line_offset);
    }
}

fn flatten_tree(tree: &TokenTree, tokens: &mut Vec<LocatedToken>, line_offset: usize) {
    match tree {
        TokenTree::Group(group) => {
            let (open, close) = delimiter_tokens(group.delimiter());
            tokens.push(LocatedToken {
                token: NormToken(open.to_owned()),
                line: absolute_line(group.span_open(), line_offset),
            });
            flatten_stream(&group.stream(), tokens, line_offset);
            tokens.push(LocatedToken {
                token: NormToken(close.to_owned()),
                line: absolute_line(group.span_close(), line_offset),
            });
        }
        TokenTree::Ident(ident) => tokens.push(LocatedToken {
            token: NormToken(ident.to_string()),
            line: absolute_line(ident.span(), line_offset),
        }),
        TokenTree::Literal(literal) => tokens.push(LocatedToken {
            token: NormToken(literal.to_string()),
            line: absolute_line(literal.span(), line_offset),
        }),
        TokenTree::Punct(punct) => tokens.push(LocatedToken {
            token: NormToken(punct.as_char().to_string()),
            line: absolute_line(punct.span(), line_offset),
        }),
    }
}

fn absolute_line(span: proc_macro2::Span, line_offset: usize) -> u32 {
    let relative = span.start().line.max(1);
    u32::try_from(line_offset.saturating_add(relative)).unwrap_or(1)
}

const fn delimiter_tokens(delimiter: Delimiter) -> (&'static str, &'static str) {
    match delimiter {
        Delimiter::Parenthesis => ("(", ")"),
        Delimiter::Brace => ("{", "}"),
        Delimiter::Bracket => ("[", "]"),
        Delimiter::None => ("⟨", "⟩"),
    }
}

fn line_start_offsets(source: &str) -> Vec<usize> {
    let mut starts = vec![0];
    for (index, byte) in source.bytes().enumerate() {
        if byte == b'\n' {
            starts.push(index + 1);
        }
    }
    starts
}

fn source_slice_for_span<'source>(
    source: &'source str,
    line_starts: &[usize],
    span: proc_macro2::Span,
) -> Result<&'source str, LintError> {
    let start = byte_offset(line_starts, span.start())?;
    let end = byte_offset(line_starts, span.end())?;
    if start > end || end > source.len() {
        return Err(LintError::new("token span escaped source bounds"));
    }
    Ok(&source[start..end])
}

fn byte_offset(
    line_starts: &[usize],
    location: proc_macro2::LineColumn,
) -> Result<usize, LintError> {
    let line_index = location.line.checked_sub(1).ok_or_else(|| {
        LintError::new(format!("invalid token line {}", location.line))
    })?;
    let line_start = line_starts.get(line_index).copied().ok_or_else(|| {
        LintError::new(format!("token line {} exceeds source", location.line))
    })?;
    Ok(line_start.saturating_add(location.column))
}

fn find_cross_module_clones(sequences: &[FileSequence], min_tokens: usize) -> Vec<Finding> {
    if min_tokens == 0 || sequences.len() < 2 {
        return Vec::new();
    }

    // Hash every minimum window once. Rebuilding a window index for every
    // sequence pair made the rule's cost grow with both token and pair counts.
    let mut windows: HashMap<u64, Vec<(usize, usize)>> = HashMap::new();
    for (sequence_index, sequence) in sequences.iter().enumerate() {
        for (start, digest) in sequence_window_digests(sequence, min_tokens)
            .into_iter()
            .enumerate()
        {
            windows
                .entry(digest)
                .or_default()
                .push((sequence_index, start));
        }
    }
    let mut matches_by_pair: BTreeMap<SequencePair, BTreeSet<CloneSpan>> = BTreeMap::new();
    for occurrences in windows.into_values() {
        for left_position in 0..occurrences.len() {
            for right_position in (left_position + 1)..occurrences.len() {
                let (left_index, left_start) = occurrences[left_position];
                let (right_index, right_start) = occurrences[right_position];
                if left_index == right_index
                    || sequences[left_index].path == sequences[right_index].path
                    || !windows_match(
                        &sequences[left_index],
                        &sequences[right_index],
                        left_start,
                        right_start,
                        min_tokens,
                    )
                {
                    continue;
                }
                let (left_origin, right_origin, length) = expand_match(
                    &sequences[left_index],
                    &sequences[right_index],
                    left_start,
                    right_start,
                    min_tokens,
                );
                matches_by_pair
                    .entry((left_index, right_index))
                    .or_default()
                    .insert((left_origin, right_origin, length));
            }
        }
    }

    let mut families: BTreeMap<u64, BTreeSet<CloneMember>> = BTreeMap::new();
    for ((left_index, right_index), matches) in matches_by_pair {
        for (content, left_member, right_member) in retain_exact_clones(
            &sequences[left_index],
            &sequences[right_index],
            matches.into_iter().collect(),
        ) {
            let digest = content_digest(&content);
            let members = families.entry(digest).or_default();
            members.insert(left_member);
            members.insert(right_member);
        }
    }

    let mut findings = Vec::new();
    for members in families.into_values() {
        if members.len() < 2 {
            continue;
        }
        let members: Vec<CloneMember> = members.into_iter().collect();
        let primary = &members[0];
        let others = members[1..]
            .iter()
            .map(|member| format!("{}:{}", member.path, member.line))
            .collect::<Vec<_>>()
            .join(", ");
        findings.push(Finding::new(
            primary.path.clone(),
            primary.line,
            format!(
                "duplicate production block ({} tokens) also at {}",
                primary.token_count, others
            ),
        ));
    }
    findings.sort();
    findings.dedup();
    findings
}

fn windows_match(
    left: &FileSequence,
    right: &FileSequence,
    left_start: usize,
    right_start: usize,
    length: usize,
) -> bool {
    left.tokens[left_start..left_start + length]
        .iter()
        .zip(&right.tokens[right_start..right_start + length])
        .all(|(left_token, right_token)| left_token.token == right_token.token)
}

fn retain_exact_clones(
    left: &FileSequence,
    right: &FileSequence,
    mut matches: Vec<CloneSpan>,
) -> Vec<(Vec<NormToken>, CloneMember, CloneMember)> {
    matches.sort_by_key(|&(left_origin, right_origin, length)| {
        (std::cmp::Reverse(length), left_origin, right_origin)
    });
    let mut retained = Vec::new();
    let mut covered: Vec<(usize, usize, usize, usize)> = Vec::new();
    for (left_origin, right_origin, length) in matches {
        let left_end = left_origin + length;
        let right_end = right_origin + length;
        if covered.iter().any(|&(l0, l1, r0, r1)| {
            left_origin >= l0 && left_end <= l1 && right_origin >= r0 && right_end <= r1
        }) {
            continue;
        }
        covered.push((left_origin, left_end, right_origin, right_end));
        let content = left.tokens[left_origin..left_end]
            .iter()
            .map(|token| token.token.clone())
            .collect::<Vec<_>>();
        retained.push((
            content,
            member_at(left, left_origin, length),
            member_at(right, right_origin, length),
        ));
    }
    retained
}

fn sequence_window_digests(sequence: &FileSequence, min_tokens: usize) -> Vec<u64> {
    if min_tokens == 0 || sequence.tokens.len() < min_tokens {
        return Vec::new();
    }
    sequence
        .tokens
        .windows(min_tokens)
        .map(window_digest)
        .collect()
}

fn expand_match(
    left: &FileSequence,
    right: &FileSequence,
    left_start: usize,
    right_start: usize,
    min_tokens: usize,
) -> (usize, usize, usize) {
    let mut left_origin = left_start;
    let mut right_origin = right_start;
    let mut length = min_tokens;
    while left_origin + length < left.tokens.len()
        && right_origin + length < right.tokens.len()
        && left.tokens[left_origin + length].token == right.tokens[right_origin + length].token
    {
        length = length.saturating_add(1);
    }
    while left_origin > 0
        && right_origin > 0
        && left.tokens[left_origin - 1].token == right.tokens[right_origin - 1].token
    {
        left_origin = left_origin.saturating_sub(1);
        right_origin = right_origin.saturating_sub(1);
        length = length.saturating_add(1);
    }
    (left_origin, right_origin, length)
}

fn member_at(sequence: &FileSequence, start: usize, length: usize) -> CloneMember {
    CloneMember {
        path: sequence.path.clone(),
        line: sequence.tokens.get(start).map_or(1, |token| token.line.max(1)),
        token_count: length,
    }
}

fn content_digest(tokens: &[NormToken]) -> u64 {
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    for token in tokens {
        token.hash(&mut hasher);
    }
    hasher.finish()
}

fn window_digest(tokens: &[LocatedToken]) -> u64 {
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    for token in tokens {
        token.token.hash(&mut hasher);
    }
    hasher.finish()
}

#[cfg(test)]
mod tests {
    use super::{
        FileSequence, LocatedToken, MIN_TOKENS, NormToken, find_cross_module_clones,
        flatten_stream, has_cfg_test, is_generated_source, is_test_function,
        parse_token_stream, production_token_sequences, should_skip_item,
    };
    use syn::parse_quote;

    fn located(values: &[&str]) -> Vec<LocatedToken> {
        values
            .iter()
            .enumerate()
            .map(|(index, value)| LocatedToken {
                token: NormToken((*value).to_owned()),
                line: u32::try_from(index + 1).unwrap_or(1),
            })
            .collect()
    }

    fn sequence(path: &str, values: &[&str]) -> FileSequence {
        FileSequence {
            path: path.to_owned(),
            tokens: located(values),
        }
    }

    #[test]
    fn normalization_ignores_formatting_and_comments() {
        let compact = "fn demo(x:i32)->i32{x+1}";
        let spaced = "fn demo ( x : i32 ) -> i32 {\n    // increment\n    x + 1\n}\n";
        let left = parse_token_stream("a.rs", compact).expect("parse compact");
        let right = parse_token_stream("b.rs", spaced).expect("parse spaced");
        let mut left_tokens = Vec::new();
        let mut right_tokens = Vec::new();
        flatten_stream(&left, &mut left_tokens, 0);
        flatten_stream(&right, &mut right_tokens, 0);
        let left_values: Vec<_> = left_tokens.iter().map(|token| token.token.0.as_str()).collect();
        let right_values: Vec<_> = right_tokens
            .iter()
            .map(|token| token.token.0.as_str())
            .collect();
        assert_eq!(left_values, right_values);
    }

    #[test]
    fn production_sequence_skips_imports_and_cfg_test_modules() {
        let source = r"
use std::collections::BTreeMap;
fn keep() {
    let value = 1;
    let other = value + 1;
    let third = other + 1;
    let fourth = third + 1;
    let fifth = fourth + 1;
    let sixth = fifth + 1;
    let seventh = sixth + 1;
    let eighth = seventh + 1;
    let ninth = eighth + 1;
    let tenth = ninth + 1;
    let _ = tenth;
}
#[cfg(test)]
mod tests {
    fn duplicated() {
        let value = 1;
        let other = value + 1;
        let third = other + 1;
        let fourth = third + 1;
        let fifth = fourth + 1;
        let sixth = fifth + 1;
        let seventh = sixth + 1;
        let eighth = seventh + 1;
        let ninth = eighth + 1;
        let tenth = ninth + 1;
        let _ = tenth;
    }
}
";
        let sequences = production_token_sequences("src/lib.rs", source).expect("scan");
        assert_eq!(sequences.len(), 1);
        let rendered = sequences[0]
            .tokens
            .iter()
            .map(|token| token.token.0.as_str())
            .collect::<Vec<_>>()
            .join(" ");
        assert!(rendered.contains("fn keep"));
        assert!(!rendered.contains("BTreeMap"));
        assert!(!rendered.contains("duplicated"));
    }

    #[test]
    fn generated_and_test_markers_are_recognized() {
        assert!(is_generated_source("// @generated by tool\nfn demo() {}\n"));
        assert!(!is_generated_source("fn demo() {}\n"));
        let test_fn: syn::ItemFn = parse_quote! {
            #[test]
            fn demo() {}
        };
        assert!(is_test_function(&test_fn.attrs));
        let cfg_test: syn::ItemMod = parse_quote! {
            #[cfg(test)]
            mod tests {}
        };
        assert!(has_cfg_test(&cfg_test.attrs));
        let use_item: syn::Item = parse_quote! { use std::fs; };
        assert!(should_skip_item(&use_item));
    }

    #[test]
    fn threshold_and_same_module_clones_are_ignored() {
        let tokens: Vec<&str> = (0..MIN_TOKENS).map(|_| "x").collect();
        let short: Vec<&str> = (0..(MIN_TOKENS - 1)).map(|_| "x").collect();
        let same_module = [
            sequence("a.rs", &tokens),
            sequence("a.rs", &tokens),
        ];
        // Same path twice should not happen in production; windows still share one path.
        assert!(find_cross_module_clones(&same_module, MIN_TOKENS).is_empty());

        let below = [sequence("a.rs", &short), sequence("b.rs", &short)];
        assert!(find_cross_module_clones(&below, MIN_TOKENS).is_empty());
    }

    #[test]
    fn reports_deterministic_cross_module_clone_families() {
        let mut tokens = vec!["fn", "demo", "(", ")", "{"];
        tokens.extend(std::iter::repeat_n("stmt", MIN_TOKENS));
        tokens.push("}");
        let sequences = [
            sequence("crates/a/src/lib.rs", &tokens),
            sequence("crates/b/src/lib.rs", &tokens),
            sequence("crates/c/src/lib.rs", &tokens),
        ];
        let findings = find_cross_module_clones(&sequences, MIN_TOKENS);
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].to_string().lines().count(), 1);
        assert!(
            findings[0]
                .to_string()
                .starts_with("crates/a/src/lib.rs:1: duplicate production block")
        );
        assert!(findings[0].to_string().contains("crates/b/src/lib.rs:1"));
        assert!(findings[0].to_string().contains("crates/c/src/lib.rs:1"));
    }

    #[test]
    fn false_positive_near_misses_are_not_reported() {
        let left: Vec<&str> = (0..MIN_TOKENS).map(|index| if index == 0 { "a" } else { "x" }).collect();
        let right: Vec<&str> = (0..MIN_TOKENS).map(|index| if index == 0 { "b" } else { "x" }).collect();
        let sequences = [sequence("a.rs", &left), sequence("b.rs", &right)];
        assert!(find_cross_module_clones(&sequences, MIN_TOKENS).is_empty());
    }
}
