#!/usr/bin/env bash
# /design session env — generated by write-design-current-env.sh. Do not edit.
export DESIGN_TMPDIR=<TMPDIR>
export SESSION_TMPDIR=<TMPDIR>
export SESSION_ID=193746D3-3C8D-42C9-8F37-F9F94CCDCF78
export ISSUE_NUMBER=2754
export CODEX_PRESENT=true
export CURSOR_PRESENT=false
export CODEX_AVAILABLE=true
export CURSOR_AVAILABLE=false
export CLAUDE_PLUGIN_ROOT=<OPERATOR_REPO_PATH>/plugins/cache/larch-local/larch/42.4.9
