# pyright: reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnusedCallResult=false, reportOptionalSubscript=false, reportOptionalMemberAccess=false, reportPossiblyUnboundVariable=false, reportUnnecessaryComparison=false, reportUnknownLambdaType=false, reportArgumentType=false
"""Python entrypoints for /alias helper surfaces."""

from __future__ import annotations

import re
import sys
from pathlib import Path

from larch.core import proc


def generate_main(argv: list[str]) -> int:
    values: dict[str, str] = {}
    index = 0
    while index < len(argv):
        arg = argv[index]
        if arg in {"--name", "--target", "--flags", "--version"} and index + 1 < len(argv):
            values[arg] = argv[index + 1]
            index += 2
        else:
            print(f"ERROR: Unknown argument: {arg}", file=sys.stderr)
            return 1
    name = values.get("--name", "")
    target = values.get("--target", "")
    flags = values.get("--flags", "")
    version = values.get("--version", "")
    if not name or not target:
        print("ERROR: --name and --target are required", file=sys.stderr)
        return 1
    escaped_flags = flags.replace('"', '\\"')
    desc = f"Alias for /{target} {escaped_flags} (created by /alias)" if flags else f"Alias for /{target} (created by /alias)"
    usage_line = f"/{name} <arguments> is equivalent to /{target} {flags} <arguments>" if flags else f"/{name} <arguments> is equivalent to /{target} <arguments>"
    behavior_args = f"{flags} $ARGUMENTS" if flags else "$ARGUMENTS"
    version_line = f"Generated by larch /alias v{version}" if version else "Generated by larch /alias"
    print("---")
    print(f"name: {name}")
    print(f'description: "{desc}"')
    print('argument-hint: "<arguments>"')
    print("allowed-tools: Skill")
    print("---")
    print()
    print(f"Auto-generated alias created by larch /alias. Invokes /{target} with preset flags.")
    print()
    print("## Usage")
    print()
    print(usage_line)
    print()
    print("## Behavior")
    print()
    print("Invoke the Skill tool:")
    print(f'- Try skill: "{target}" first (bare name). If no skill matches, try skill: "larch:{target}" (fully-qualified plugin name).')
    print(f"- args: {behavior_args}")
    if target == "implement":
        print()
        print("After the Skill tool loads /implement, the child skill MUST begin execution at its Step 0 (session setup). Do not investigate the codebase, plan, or implement anything before Step 0 completes.")
    print()
    print(version_line)
    return 0


def resolve_target_main(argv: list[str]) -> int:
    name = ""
    private = False
    index = 0
    while index < len(argv):
        arg = argv[index]
        if arg == "--alias-name":
            if index + 1 >= len(argv):
                print("ERROR: --alias-name requires a value", file=sys.stderr)
                return 1
            name = argv[index + 1]
            index += 2
        elif arg == "--private":
            private = True
            index += 1
        else:
            print(f"ERROR: Unknown argument: {arg}", file=sys.stderr)
            return 1
    if not name:
        print("ERROR: --alias-name is required", file=sys.stderr)
        return 1
    if re.match(r"^[a-z][a-z0-9-]*$", name) is None:
        print(f"ERROR: alias-name '{name}' is invalid (must match ^[a-z][a-z0-9-]*$)", file=sys.stderr)
        return 1
    result = proc.run(["git", "rev-parse", "--show-toplevel"])
    repo_root = result.stdout.strip()
    if result.returncode != 0 or not repo_root:
        print("ERROR: not in a git repository", file=sys.stderr)
        return 1
    root = Path(repo_root)
    plugin_repo = (root / ".claude-plugin/plugin.json").is_file() and (root / "skills/implement/SKILL.md").is_file()
    target_dir = root / "skills" / name if plugin_repo and not private else root / ".claude" / "skills" / name
    print(f"REPO_ROOT={root}")
    print(f"PLUGIN_REPO={'true' if plugin_repo else 'false'}")
    print(f"TARGET_DIR={target_dir}")
    return 0
