"""Frozen Python behavior for the issue #8058 session-env writer cutover.

This reproduces `python/larch/state/session_env.py` as it behaved at cutover for
`session write-env`, `write-design-env`, `write-implement-env`,
`clear-implement-pointer`, `persist-run-flags`, `write-run-params`,
`restore-finalize-state`, and `resolve-trusted-design-env`, with three deliberate
omissions that are not part of any command contract:

* `logging_util.quiet_init` file routing. It duplicates stdout and stderr into a
  per-invocation `$TMPDIR/larch-quiet-*.log` while leaving the contract streams
  pointed at the original descriptors, so a caller sees identical bytes either
  way. The Rust owner writes the same bytes without the observability copy.
* Outbound redaction of breadcrumb diagnostics. The Rust owner keeps redaction;
  this reference omits it because the rules rewrite only `/Users/<user>/<repo>/`
  and `/home/<user>/<repo>/` prefixes, which no sandbox path can match.
* The best-effort `run-log write` delegation at the end of
  `restore-finalize-state`. Both owners spawn it only when the durable state
  carries both a bail reason and a run id, and both discard its result; the
  golden matrix covers the no-bail-reason path, and a `larch-cli` integration
  test covers the delegation itself against a fake plugin root.

Two differences are known and intentional, neither observable to a caller that
branches on exit codes:

* `clap` consumes a lone `--` before the Rust command sees it, so a trailing
  `--` exits 0 in Rust and 1 or 2 here. No production caller passes it. The same
  boundary already applies to the #8056 and #8057 owners.
* A carriage return inside `ship-pr-state.sh` raises an uncaught `ValueError`
  here, because `restore-finalize-state` never guarded its reads; the Rust owner
  reports the same diagnostic on stderr and exits 1 instead of printing a
  traceback. This case stays out of the byte-compared golden matrix.
* `--issue-number` accepts any Unicode digit here, because Python's
  `str.isdigit` does; the Rust owner accepts ASCII digits only. Both write the
  value into a wire file consumed as a GitHub issue number, which is always
  ASCII, so the Rust owner is the stricter of two acceptable readings.
* `--output` naming an existing directory is refused by both, but the wording
  differs: this reference surfaces the operating system's rename errno, and the
  Rust owner surfaces its confinement refusal. Exit code, refusal, and the
  untouched target are identical, so this case stays out of the golden matrix.

The generated design env keeps its `generated by session_env.py` banner: the
acceptance criterion is byte-identical output, so the banner is wire content,
not an attribution.
"""
# ruff: noqa: C901, PLR0911, PLR0912, PLR0913, PLR0915, S108

from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import subprocess
import sys
from contextlib import suppress
from pathlib import Path

TMP_FALLBACK = "/tmp"
MAX_PATH_VALUE_LEN = 512
_BOOL = {"true", "false"}
_SAFE_PATH_RE = re.compile(r"^[A-Za-z0-9_./~+-]+$")
_SAFE_ID_RE = re.compile(r"^[A-Za-z0-9_.-]{1,128}$")
_SAFE_RUN_ID_RE = re.compile(r"^[A-Za-z0-9._-]{1,128}$")
_REPO_RE = re.compile(r"^[A-Za-z0-9._-]+/[A-Za-z0-9._-]+$")
_KEY_RE = re.compile(r"^[A-Z_][A-Z0-9_]*$")
_PID_RE = re.compile(r"^[1-9][0-9]{0,6}$")
DIFFICULTIES = {"TRIVIAL", "MODERATE", "HARD"}

WRITE_ENV_KEYS = frozenset({
    "REPO", "REPO_ROOT", "REPO_UNAVAILABLE", "FORKED_TARGET",
    "LARCH_EXTERNAL_HEALTH_CHECK_TIMEOUT", "CLAUDE_BINARY_FOUND", "CODEX_BINARY_FOUND",
    "CURSOR_BINARY_FOUND", "LARCH_AUTO_MODE", "LARCH_TIMING_LEDGER", "LARCH_TOKEN_SESSION_ID",
    "LARCH_CLAUDE_SOURCE_FILE", "PREV_IMPLEMENT_TMPDIR", "LARCH_DYNAMIC_ARCHETYPES_MAX",
    "LARCH_RUN_ID", "LARCH_CLAUDE_PLUGIN_ROOT", "LARCH_LIVE_MUTATION_OK",
})
WRITE_DESIGN_ENV_KEYS = frozenset({
    "DESIGN_TMPDIR", "SESSION_TMPDIR", "SESSION_ID", "REPO", "REPO_ROOT", "ISSUE_NUMBER",
    "CODEX_BINARY_FOUND", "CURSOR_BINARY_FOUND", "LARCH_EXTERNAL_HEALTH_CHECK_TIMEOUT",
    "CLAUDE_PLUGIN_ROOT", "LARCH_CLAUDE_SOURCE_FILE", "LARCH_RUN_ID", "LARCH_LIVE_MUTATION_OK",
})
RUN_FLAG_KEYS = frozenset({
    "QUICK_MODE", "NO_ISSUES", "FORCE_REQUESTED", "SELF_REVIEW_REQUESTED",
    "SELF_IMPLEMENT_REQUESTED", "DIFFICULTY_OVERRIDE",
})
RESTORE_FINALIZE_KEYS = (
    "BRANCH_NAME", "PR_NUMBER", "PR_TITLE", "PR_URL", "ISSUE_NUMBER", "REPO", "DRAFT", "MERGE",
    "DEFERRED", "REPO_UNAVAILABLE", "PR_CLOSED", "DESIGN_ONLY_DONE", "BAIL_NEEDS_USER_INPUT",
    "STALL_TRACKING", "STALL_STEP", "DONE_RENAME_APPLIED", "RUN_ID", "EXPECTED_SESSION_ID",
    "EXPECTED_TMPDIR_BASENAME_PREFIX", "NO_LOGS_COMMIT",
)
RESTORE_FINALIZE_DEFAULTS = {
    "DESIGN_ONLY_DONE": "false", "DRAFT": "false", "MERGE": "false", "DEFERRED": "false",
    "REPO_UNAVAILABLE": "false", "PR_CLOSED": "false", "BAIL_NEEDS_USER_INPUT": "false",
    "STALL_TRACKING": "false", "DONE_RENAME_APPLIED": "false", "NO_LOGS_COMMIT": "false",
}


def cache_sessions_root() -> Path:
    xdg = os.environ.get("XDG_CACHE_HOME")
    if xdg:
        base = xdg
    else:
        home = os.environ.get("HOME", "")
        base = f"{home}/.cache" if home else f"{TMP_FALLBACK}/.cache"
    return Path(base) / "larch" / "sessions"


def allowed_roots() -> tuple[Path, ...]:
    return (Path(TMP_FALLBACK), Path("/private/tmp"), Path("/var/folders"),
            Path("/private/var/folders"), cache_sessions_root())


def _resolved(path: Path) -> Path:
    return path.resolve(strict=False)


def _under(path: Path, root: Path) -> bool:
    try:
        resolved, resolved_root = _resolved(path), _resolved(root)
    except OSError:
        return False
    return resolved == resolved_root or resolved_root in resolved.parents


def _strictly_under(path: Path, root: Path) -> bool:
    try:
        resolved, resolved_root = _resolved(path), _resolved(root)
    except OSError:
        return False
    return resolved_root in resolved.parents


def is_allowed_session_tmpdir(path: Path) -> bool:
    return any(_strictly_under(path, root) for root in allowed_roots())


def writer_target_allowed(path: Path) -> bool:
    return any(_under(path, root) for root in allowed_roots())


def safe_output_parent(path: Path) -> bool:
    parent = path.parent
    return parent.exists() and parent.is_dir() and not parent.is_symlink()


def assert_no_symlink_path_or_ancestors(path: Path) -> None:
    current = path if path.is_absolute() else Path.cwd() / path
    while True:
        if current.is_symlink():
            raise OSError(f"refusing symlinked path or ancestor: {current}")
        if current == current.parent:
            return
        current = current.parent


def atomic_write(path: Path, text: str, *, create_parent: bool = False, mode: int = 0o600) -> None:
    assert_no_symlink_path_or_ancestors(path if path.is_absolute() else Path.cwd() / path)
    if create_parent:
        path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_symlink():
        raise OSError(f"refusing to write through symlink: {path}")
    temp = path.with_suffix(path.suffix + ".tmp")
    with suppress(FileNotFoundError):
        temp.unlink()
    descriptor = os.open(str(temp), os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, mode)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
    except BaseException:
        with suppress(OSError):
            temp.unlink()
        raise
    os.chmod(temp, mode)
    temp.replace(path)


def kv_text(rows: list[tuple[str, str]]) -> str:
    return "".join(f"{key}={value}\n" for key, value in rows)


def read_kv_file_text(path: Path) -> str:
    text = path.read_bytes().decode("utf-8", errors="replace")
    if "\r" in text:
        raise ValueError(f"session env file contains carriage return: {path}")
    return text


def read_kv_raw(path: Path) -> dict[str, str]:
    if not path.is_file():
        return {}
    values: dict[str, str] = {}
    for raw in read_kv_file_text(path).splitlines():
        if not raw or raw.startswith("#") or "=" not in raw:
            continue
        key, value = raw.split("=", 1)
        values[key] = value
    return values


def parse_allowlisted_env_line(raw: str, allowlist: frozenset[str], *, reject_newline_rhs: bool) -> tuple[str, str] | None:
    line = raw.strip()
    if not line or line.startswith("#"):
        return None
    line = line.removeprefix("export ")
    if "=" not in line:
        return None
    key, rhs = line.split("=", 1)
    key = key.strip()
    if key not in allowlist or not _KEY_RE.match(key):
        return None
    if reject_newline_rhs and ("\n" in rhs or "\r" in rhs):
        return None
    try:
        parts = shlex.split(rhs, posix=True)
    except ValueError:
        return None
    if len(parts) > 1:
        return None
    value = parts[0] if parts else ""
    return None if "\n" in value or "\r" in value else (key, value)


def validate_no_newlines(rows: list[tuple[str, str]]) -> None:
    for key, value in rows:
        if "\n" in value or "\r" in value:
            raise ValueError(f"value for {key} contains newline or carriage return")


def validate_writer_keys(rows: list[tuple[str, str]], allowed: frozenset[str]) -> None:
    for key, _ in rows:
        if key not in allowed:
            raise ValueError(f"disallowed writer key: {key}")


def external_timeout() -> str:
    value = os.environ.get("LARCH_EXTERNAL_HEALTH_CHECK_TIMEOUT", "60")
    return value if value.isdigit() else "60"


def parse_bool_arg(value: str, flag: str) -> None:
    if value not in _BOOL:
        raise ValueError(f"Invalid {flag}: must be true or false")


def validate_plugin_root_value(value: str) -> bool:
    return bool(value) and len(value) <= MAX_PATH_VALUE_LEN and value.startswith("/") and bool(_SAFE_PATH_RE.match(value))


def validate_path_arg_value(value: str, flag: str) -> None:
    if value and (len(value) > MAX_PATH_VALUE_LEN or not _SAFE_PATH_RE.match(value)):
        raise ValueError(f"Invalid {flag}: must match ^[A-Za-z0-9_./~+-]{{1,512}}$")


def validate_repo_root_value(value: str, flag: str) -> None:
    if not value:
        return
    if len(value) > MAX_PATH_VALUE_LEN or "\n" in value or "\r" in value or "\x00" in value:
        raise ValueError(f"Invalid {flag}: must be an absolute single-line path")
    if not value.startswith("/"):
        raise ValueError(f"Invalid {flag}: must be an absolute path")


def valid_repo_value(value: str) -> bool:
    if not value:
        return True
    if value.startswith(("--", "/")) or "../" in value or "\\" in value:
        return False
    if "\n" in value or "\r" in value:
        return False
    return bool(_REPO_RE.match(value))


def fallback_repo_root() -> str:
    return os.environ.get("CLAUDE_PROJECT_DIR", "").strip() or os.environ.get("REPO_ROOT", "").strip()


def sessions_dir() -> Path:
    return Path.home() / ".cache" / "larch" / "sessions"


def design_pointer_path(pid: str) -> Path:
    return sessions_dir() / (f"current-design-env-{pid}.sh" if pid else "current-design-env.sh")


def implement_pointer_path(pid: str) -> Path:
    return sessions_dir() / f"current-implement-env-{pid}.sh"


def write_plugin_root_env(output: Path, value: str) -> None:
    if not value or not validate_plugin_root_value(value):
        return
    if not output.parent.is_dir():
        raise OSError(f"plugin-root.env parent is not a directory: {output.parent}")
    atomic_write(output, f"CLAUDE_PLUGIN_ROOT={value}\nexport CLAUDE_PLUGIN_ROOT\n")


def confirm_writable(target: Path, reported: str) -> None:
    if not writer_target_allowed(target):
        raise ValueError(f"output path not under allowed session root: {reported}")
    if not safe_output_parent(target):
        raise OSError(f"output parent is not a writable directory: {target.parent}")


# --- design-tmpdir validation (frozen from the #8057 owner) -------------------


def split_ancestor_tail(candidate: str) -> tuple[str, str]:
    path = candidate.rstrip("/") or "/"
    tail = ""
    while not Path(path).exists() and path != "/":
        base = Path(path).name
        if base:
            tail = f"{base}/{tail}" if tail else base
        path = str(Path(path).parent) or "/"
    return path, tail


def canonical_prefix(prefix: Path) -> str:
    try:
        resolved = prefix.resolve(strict=True) if prefix.is_dir() else prefix
    except OSError:
        resolved = prefix
    return f"{str(resolved).rstrip('/')}/"


def validate_design_tmpdir(candidate: str) -> tuple[bool, str]:
    if not candidate:
        return False, "design-tmpdir: path is required"
    if "\n" in candidate or "\r" in candidate:
        return False, "design-tmpdir: path must not contain newline or carriage return"
    if not candidate.startswith("/"):
        return False, "Invalid --design-tmpdir: must be an absolute path"
    if any(segment in {".", ".."} for segment in candidate.split("/") if segment):
        return False, "design-tmpdir: path must not contain '.' or '..' segments"
    ancestor, tail = split_ancestor_tail(candidate)
    try:
        resolved_ancestor = Path(ancestor).resolve(strict=True)
    except OSError:
        return False, "design-tmpdir: parent resolution failed"
    resolved = resolved_ancestor / tail if tail else resolved_ancestor
    cand = Path(candidate)
    if cand.exists():
        if cand.is_symlink() and not cand.is_dir():
            return False, "design-tmpdir: leaf symlink must resolve to a directory"
        if not cand.is_dir():
            return False, "design-tmpdir: path must name a directory"
        try:
            resolved = cand.resolve(strict=True)
        except OSError:
            if cand.is_symlink():
                return False, "design-tmpdir: leaf symlink must resolve to a directory"
    allow = [
        canonical_prefix(cache_sessions_root()),
        canonical_prefix(Path(os.environ["TMPDIR"])) if os.environ.get("TMPDIR") else "",
        canonical_prefix(Path(TMP_FALLBACK)),
    ]
    comparable = f"{str(resolved).rstrip('/')}/"
    if not any(prefix and comparable.startswith(prefix) for prefix in allow):
        return False, f"design-tmpdir: path not under allowlist after resolution: {resolved}"
    return True, ""


# --- verbs --------------------------------------------------------------------


def write_env_main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="session write-env", add_help=False)
    parser.add_argument("--output")
    parser.add_argument("--repo", default="")
    parser.add_argument("--repo-root", default="")
    parser.add_argument("--repo-unavailable")
    for flag in ("codex-present", "cursor-present", "codex-available", "cursor-available",
                 "claude-binary-found", "codex-binary-found", "cursor-binary-found", "auto-mode"):
        parser.add_argument(f"--{flag}", default="")
    parser.add_argument("--forked-target", default="false")
    for flag in ("timing-ledger", "token-session-id", "claude-source-file",
                 "prev-implement-tmpdir", "dynamic-archetypes", "run-id", "live-mutation-ok"):
        parser.add_argument(f"--{flag}", default="")
    parser.add_argument("--plugin-root-only", action="store_true")
    parser.add_argument("--value", default="")
    try:
        args = parser.parse_args(argv)
    except SystemExit:
        return 1
    try:
        if not args.output:
            raise ValueError("Missing required arguments: --output, --repo-unavailable")
        out_path = Path(args.output)
        if args.plugin_root_only:
            if validate_plugin_root_value(args.value):
                write_plugin_root_env(out_path, args.value)
            return 0
        if args.repo_unavailable is None:
            raise ValueError("Missing required arguments: --output, --repo-unavailable")
        for flag in ("codex_present", "cursor_present", "codex_available", "cursor_available",
                     "claude_binary_found", "codex_binary_found", "cursor_binary_found",
                     "auto_mode", "live_mutation_ok"):
            value = getattr(args, flag)
            if value:
                parse_bool_arg(value, f"--{flag.replace('_', '-')}")
        parse_bool_arg(args.forked_target, "--forked-target")
        if args.token_session_id and not _SAFE_ID_RE.match(args.token_session_id):
            raise ValueError("Invalid --token-session-id: must match ^[A-Za-z0-9_.-]{1,128}$")
        validate_path_arg_value(args.claude_source_file, "--claude-source-file")
        validate_path_arg_value(args.timing_ledger, "--timing-ledger")
        if args.prev_implement_tmpdir:
            validate_path_arg_value(args.prev_implement_tmpdir, "--prev-implement-tmpdir")
            if not args.prev_implement_tmpdir.startswith("/"):
                raise ValueError("Invalid --prev-implement-tmpdir: must be an absolute path")
        plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT", "")
        if plugin_root and not validate_plugin_root_value(plugin_root):
            raise ValueError("Invalid CLAUDE_PLUGIN_ROOT: must be an absolute path matching ^[A-Za-z0-9_./~+-]{1,512}$")
        if args.dynamic_archetypes and args.dynamic_archetypes not in {"0", "1"}:
            raise ValueError("Invalid --dynamic-archetypes: must be an integer from 0 to 1")
        if args.run_id and not _SAFE_RUN_ID_RE.match(args.run_id):
            raise ValueError("Invalid --run-id: must match ^[A-Za-z0-9._-]{1,128}$")
        repo_root = args.repo_root.strip() or fallback_repo_root()
        validate_repo_root_value(repo_root, "--repo-root")
        rows: list[tuple[str, str]] = [
            ("REPO", args.repo),
            ("REPO_UNAVAILABLE", args.repo_unavailable),
            ("FORKED_TARGET", args.forked_target),
            ("LARCH_EXTERNAL_HEALTH_CHECK_TIMEOUT", external_timeout()),
        ]
        for key, value in (
            ("CLAUDE_BINARY_FOUND", args.claude_binary_found),
            ("CODEX_BINARY_FOUND", args.codex_binary_found),
            ("CURSOR_BINARY_FOUND", args.cursor_binary_found),
            ("LARCH_AUTO_MODE", args.auto_mode),
            ("LARCH_TIMING_LEDGER", args.timing_ledger),
            ("LARCH_TOKEN_SESSION_ID", args.token_session_id),
            ("LARCH_CLAUDE_SOURCE_FILE", args.claude_source_file),
            ("PREV_IMPLEMENT_TMPDIR", args.prev_implement_tmpdir),
            ("LARCH_DYNAMIC_ARCHETYPES_MAX", args.dynamic_archetypes),
            ("LARCH_RUN_ID", args.run_id),
            ("LARCH_LIVE_MUTATION_OK", args.live_mutation_ok),
            ("REPO_ROOT", repo_root),
            ("LARCH_CLAUDE_PLUGIN_ROOT", plugin_root),
        ):
            if value:
                rows.append((key, value))
        validate_writer_keys(rows, WRITE_ENV_KEYS)
        validate_no_newlines(rows)
        if args.output == "/dev/null":
            return 0
        confirm_writable(out_path, args.output)
        atomic_write(out_path, kv_text(rows))
        if plugin_root:
            write_plugin_root_env(out_path.parent / "plugin-root.env", plugin_root)
        return 0
    except (OSError, ValueError) as error:
        print(f"ERROR={error}", file=sys.stderr)
        return 1


def design_run_launcher_text(pid: str, plugin_root: str) -> str:
    quoted = shlex.quote(plugin_root)
    return (
        "#!/usr/bin/env bash\n"
        "set -uo pipefail\n"
        f"PLUGIN_ROOT={quoted}\n"
        f'SESSION_ENV_PATH="$HOME/.cache/larch/sessions/current-design-env-{pid}.sh"\n'
        f"CLAUDE_PID={pid}\n"
        'if [ "$#" -lt 1 ]; then\n'
        "  printf '%s\\n' 'ERROR=missing design wrapper script name' >&2\n"
        "  exit 2\n"
        "fi\n"
        'script=$1\n'
        "shift\n"
        'case "$script" in\n'
        r'  ""|*/*|*..*|*\\*|*\;*|*\&*|*\|*|*\$*|*\`*|*\(*|*\)*|*\<*|*\>*|*[[:space:]]*)' "\n"
        "    printf '%s\\n' 'ERROR=invalid design wrapper script name' >&2\n"
        "    exit 2\n"
        "    ;;\n"
        "esac\n"
        'export CLAUDE_PLUGIN_ROOT="$PLUGIN_ROOT"\n'
        'case "$script" in\n'
        "  step0-*.sh|step0c.sh|step1d5.sh|step1d7.sh|step1e-reentry.sh|design-step0-parse.sh|design-step0-session.sh|design-step0-route.sh|design-step0-clarify-hard-halt.sh|design-step0-init.sh|design-step0-abort-cleanup.sh|design-step0-ap-continue.sh|design-step0c.sh|design-step1d5.sh|design-step1d7.sh|design-step1e-reentry.sh|design-step2b-drafter.sh|design-step2b-postplan.sh)\n"
        "    printf '%s\\n' 'ERROR=ported design wrapper must use bare verb name, not .sh' >&2\n"
        "    exit 2\n"
        "    ;;\n"
        '  design-step35-settle.sh)\n'
        '    exec "$PLUGIN_ROOT/scripts/larch.sh" design step35-settle --session-env-path "$SESSION_ENV_PATH" --claude-pid "$CLAUDE_PID" "$@"\n'
        '    ;;\n'
        '  design-step2b5.sh)\n'
        '    exec "$PLUGIN_ROOT/scripts/larch.sh" design step2b5 --session-env-path "$SESSION_ENV_PATH" --claude-pid "$CLAUDE_PID" "$@"\n'
        '    ;;\n'
        '  design-step6.sh)\n'
        '    exec "$PLUGIN_ROOT/scripts/larch.sh" design step6 --session-env-path "$SESSION_ENV_PATH" --claude-pid "$CLAUDE_PID" "$@"\n'
        '    ;;\n'
        '  design-step6-prelude.sh)\n'
        '    exec "$PLUGIN_ROOT/scripts/larch.sh" design step6-prelude --session-env-path "$SESSION_ENV_PATH" --claude-pid "$CLAUDE_PID" "$@"\n'
        '    ;;\n'
        '  design-step6-cleanup.sh)\n'
        '    exec "$PLUGIN_ROOT/scripts/larch.sh" design step6-cleanup --session-env-path "$SESSION_ENV_PATH" --claude-pid "$CLAUDE_PID" "$@"\n'
        '    ;;\n'
        '  design-step-validator-autofix.sh)\n'
        '    exec "$PLUGIN_ROOT/scripts/larch.sh" plan validator-autofix --session-env-path "$SESSION_ENV_PATH" --claude-pid "$CLAUDE_PID" "$@"\n'
        '    ;;\n'
        '  design-stage-terminal-state.sh)\n'
        '    exec "$PLUGIN_ROOT/scripts/larch.sh" design stage-terminal-state "$@"\n'
        '    ;;\n'
        '  design-failure-report.sh)\n'
        '    exec "$PLUGIN_ROOT/scripts/larch.sh" design failure-report "$@"\n'
        '    ;;\n'
        '  design-step-final-summary.sh)\n'
        '    exec "$PLUGIN_ROOT/scripts/larch.sh" design step-final-summary --session-env-path "$SESSION_ENV_PATH" --claude-pid "$CLAUDE_PID" "$@"\n'
        '    ;;\n'
        "  *.sh)\n"
        '    exec "$PLUGIN_ROOT/skills/design/scripts/$script" --session-env-path "$SESSION_ENV_PATH" --claude-pid "$CLAUDE_PID" "$@"\n'
        "    ;;\n"
        "  step0-parse|step0-session|step0-route|step0-clarify-hard-halt|step0-init|step0-abort-cleanup|step0-ap-continue|step0c)\n"
        '    exec "$PLUGIN_ROOT/scripts/larch.sh" design "$script" --session-env-path "$SESSION_ENV_PATH" --claude-pid "$CLAUDE_PID" "$@"\n'
        "    ;;\n"
        "  step1d5|step1d7|step1e-reentry)\n"
        '    exec "$PLUGIN_ROOT/scripts/larch.sh" design "$script" --session-env-path "$SESSION_ENV_PATH" --claude-pid "$CLAUDE_PID" "$@"\n'
        "    ;;\n"
        "  step2b-drafter|step2b-postplan|step3b-entry)\n"
        '    exec "$PLUGIN_ROOT/scripts/larch.sh" design "$script" --session-env-path "$SESSION_ENV_PATH" --claude-pid "$CLAUDE_PID" "$@"\n'
        "    ;;\n"
        "  step6|step6-prelude|step6-cleanup)\n"
        '    exec "$PLUGIN_ROOT/scripts/larch.sh" design "$script" --session-env-path "$SESSION_ENV_PATH" --claude-pid "$CLAUDE_PID" "$@"\n'
        "    ;;\n"
        "  *.*)\n"
        "    printf '%s\\n' 'ERROR=design verb must be bare and must not end in .sh' >&2\n"
        "    exit 2\n"
        "    ;;\n"
        "  *)\n"
        "    printf '%s\\n' 'ERROR=unknown design wrapper verb' >&2\n"
        "    exit 2\n"
        "    ;;\n"
        "esac\n"
    )


def implement_run_launcher_text(pid: str) -> str:
    return (
        "#!/usr/bin/env bash\n"
        "set -uo pipefail\n"
        f'POINTER="$HOME/.cache/larch/sessions/current-implement-env-{pid}.sh"\n'
        '[ -f "$POINTER" ] && [ ! -L "$POINTER" ] || { printf \'%s\\n\' "implement-run: missing current-env pointer: $POINTER" >&2; exit 2; }\n'
        'IMPLEMENT_TMPDIR=$(awk \'BEGIN{p="IMPLEMENT_TMPDIR="} index($0,p)==1{print substr($0,length(p)+1); found=1; exit} END{exit found ? 0 : 1}\' "$POINTER" 2>/dev/null) || { printf \'%s\\n\' "implement-run: IMPLEMENT_TMPDIR missing from pointer: $POINTER" >&2; exit 2; }\n'
        '[ -n "$IMPLEMENT_TMPDIR" ] || { printf \'%s\\n\' "implement-run: IMPLEMENT_TMPDIR empty in pointer: $POINTER" >&2; exit 2; }\n'
        'case "$IMPLEMENT_TMPDIR" in /*) ;; *) printf \'%s\\n\' "implement-run: IMPLEMENT_TMPDIR must be absolute: $IMPLEMENT_TMPDIR" >&2; exit 2 ;; esac\n'
        'LARCH_RUN_SH="$IMPLEMENT_TMPDIR/larch-run.sh"\n'
        '[ -f "$LARCH_RUN_SH" ] || { printf \'%s\\n\' "implement-run: missing larch-run.sh: $LARCH_RUN_SH" >&2; exit 2; }\n'
        '[ -x "$LARCH_RUN_SH" ] || { printf \'%s\\n\' "implement-run: larch-run.sh is not executable: $LARCH_RUN_SH" >&2; exit 2; }\n'
        "export IMPLEMENT_TMPDIR\n"
        f'export LARCH_CLAUDE_PID="${{LARCH_CLAUDE_PID:-{pid}}}"\n'
        'exec "$LARCH_RUN_SH" "$@"\n'
    )


def recover_prior_bool(prior_file: Path, key: str) -> str:
    if not prior_file.is_file():
        return ""
    pattern = re.compile(rf"^export {re.escape(key)}=(true|false)$")
    found = ""
    for line in read_kv_file_text(prior_file).splitlines():
        match = pattern.match(line)
        if match:
            found = match.group(1)
    return found


def recover_prior_design_value(prior_file: Path, key: str) -> str:
    if not prior_file.is_file():
        return ""
    found = ""
    for line in read_kv_file_text(prior_file).splitlines():
        parsed = parse_allowlisted_env_line(line, WRITE_DESIGN_ENV_KEYS, reject_newline_rhs=True)
        if parsed is not None and parsed[0] == key:
            found = parsed[1]
    return found


def write_design_env_main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="session write-design-env", add_help=False)
    for flag in ("output", "design-tmpdir", "session-id", "run-id", "codex-present",
                 "cursor-present", "codex-available", "cursor-available", "codex-binary-found",
                 "cursor-binary-found", "repo", "repo-root", "issue-number", "claude-pid",
                 "claude-source-file", "live-mutation-ok"):
        parser.add_argument(f"--{flag}", default="")
    try:
        args = parser.parse_args(argv)
    except SystemExit:
        return 1
    try:
        if not args.output or not args.design_tmpdir or not args.session_id:
            raise ValueError("Missing required arguments: --output, --design-tmpdir, --session-id")
        for flag in ("codex_present", "cursor_present", "codex_available", "cursor_available",
                     "codex_binary_found", "cursor_binary_found", "live_mutation_ok"):
            value = getattr(args, flag)
            if value:
                parse_bool_arg(value, f"--{flag.replace('_', '-')}")
        if args.issue_number and not args.issue_number.isdigit():
            raise ValueError("Invalid --issue-number: must be a non-negative integer")
        if not valid_repo_value(args.repo):
            raise ValueError("Invalid --repo: must match OWNER/REPO")
        if not _SAFE_ID_RE.match(args.session_id):
            raise ValueError("Invalid --session-id: must match ^[A-Za-z0-9_.-]{1,128}$")
        if args.claude_pid and not _PID_RE.match(args.claude_pid):
            raise ValueError("Invalid --claude-pid: must be a positive integer of at most 7 decimal digits")
        validate_path_arg_value(args.claude_source_file, "--claude-source-file")
        ok, message = validate_design_tmpdir(args.design_tmpdir)
        if not ok:
            raise ValueError(message)
        out_path = Path(args.output)
        if not out_path.is_absolute():
            raise ValueError("Invalid --output: must be an absolute path")
        confirm_writable(out_path, str(out_path))
        plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT", "")
        if plugin_root and not validate_plugin_root_value(plugin_root):
            raise ValueError("Invalid CLAUDE_PLUGIN_ROOT: must be an absolute path matching ^[A-Za-z0-9_./~+-]{1,512}$")
        if args.claude_pid and not plugin_root:
            raise ValueError("Missing CLAUDE_PLUGIN_ROOT: required when --claude-pid is set")
        rows: list[tuple[str, str]] = [
            ("DESIGN_TMPDIR", args.design_tmpdir),
            ("SESSION_TMPDIR", args.design_tmpdir),
            ("SESSION_ID", args.session_id),
        ]
        if args.repo:
            rows.append(("REPO", args.repo))
        repo_root = args.repo_root.strip() or recover_prior_design_value(out_path, "REPO_ROOT") or fallback_repo_root()
        if repo_root:
            validate_repo_root_value(repo_root, "--repo-root")
            rows.append(("REPO_ROOT", repo_root))
        if args.issue_number:
            rows.append(("ISSUE_NUMBER", args.issue_number))
        run_id = args.run_id.strip() or recover_prior_design_value(out_path, "LARCH_RUN_ID")
        if run_id:
            if not _SAFE_RUN_ID_RE.fullmatch(run_id):
                raise ValueError("Invalid --run-id: must match ^[A-Za-z0-9._-]{1,128}$")
            rows.append(("LARCH_RUN_ID", run_id))
        for key, flag, supplied in (
            ("CODEX_BINARY_FOUND", "--codex-binary-found", "--codex-binary-found" in argv),
            ("CURSOR_BINARY_FOUND", "--cursor-binary-found", "--cursor-binary-found" in argv),
        ):
            value = getattr(args, flag.removeprefix("--").replace("-", "_"))
            if not value and not supplied:
                value = recover_prior_bool(out_path, key)
            if value:
                parse_bool_arg(value, flag)
                rows.append((key, value))
        rows.append(("LARCH_EXTERNAL_HEALTH_CHECK_TIMEOUT", external_timeout()))
        if args.claude_source_file:
            rows.append(("LARCH_CLAUDE_SOURCE_FILE", args.claude_source_file))
        if plugin_root:
            rows.append(("CLAUDE_PLUGIN_ROOT", plugin_root))
        if args.live_mutation_ok:
            rows.append(("LARCH_LIVE_MUTATION_OK", args.live_mutation_ok))
        elif out_path.is_file() and recover_prior_design_value(out_path, "LARCH_LIVE_MUTATION_OK") == "true":
            rows.append(("LARCH_LIVE_MUTATION_OK", "true"))
        validate_writer_keys(rows, WRITE_DESIGN_ENV_KEYS)
        validate_no_newlines(rows)
        text = "#!/usr/bin/env bash\n# /design session env — generated by session_env.py. Do not edit.\n"
        text += "".join(f"export {key}={shlex.quote(value)}\n" for key, value in rows)
        atomic_write(out_path, text)
        pointer = design_pointer_path(args.claude_pid)
        if not args.claude_pid:
            print("WARNING=write-design-current-env.sh: --claude-pid omitted; using legacy current-design-env.sh symlink (transition shim; pass --claude-pid)", file=sys.stderr)
        ancestor = pointer.parent
        while True:
            if ancestor.is_symlink():
                raise OSError(f"refusing symlinked ancestor for design current-env link: {ancestor}")
            if ancestor == ancestor.parent:
                break
            ancestor = ancestor.parent
        pointer.parent.mkdir(parents=True, exist_ok=True)
        temporary = pointer.with_name(f".{pointer.name}.tmp.{os.getpid()}")
        with suppress(FileNotFoundError):
            temporary.unlink()
        temporary.symlink_to(out_path)
        temporary.replace(pointer)
        if args.claude_pid:
            launcher = sessions_dir() / f"design-run-{args.claude_pid}.sh"
            launcher.parent.mkdir(parents=True, exist_ok=True)
            assert_no_symlink_path_or_ancestors(launcher)
            atomic_write(launcher, design_run_launcher_text(args.claude_pid, plugin_root), mode=0o755)
        return 0
    except (OSError, ValueError) as error:
        print(f"ERROR={error}", file=sys.stderr)
        return 1


def write_implement_env_main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="session write-implement-env", add_help=False)
    parser.add_argument("--claude-pid", default="")
    parser.add_argument("--implement-tmpdir", default="")
    parser.add_argument("--cwd", default="")
    try:
        args = parser.parse_args(argv)
    except SystemExit:
        return 1
    try:
        if not _PID_RE.match(args.claude_pid):
            raise ValueError("Invalid --claude-pid: must be a positive integer of at most 7 decimal digits")
        tmpdir = Path(args.implement_tmpdir)
        if not tmpdir.is_absolute() or not tmpdir.is_dir():
            raise ValueError("Invalid --implement-tmpdir: must be an existing absolute directory")
        if not is_allowed_session_tmpdir(tmpdir):
            raise ValueError(f"implement-tmpdir: path must be under /tmp/, /private/tmp/, /var/folders/, or {cache_sessions_root()}/")
        cwd_path = Path(args.cwd)
        if not cwd_path.is_absolute():
            raise ValueError("Invalid --cwd: must be an absolute path")
        try:
            repo_cwd = str(cwd_path.resolve())
        except OSError:
            repo_cwd = str(cwd_path)
        rows = [("IMPLEMENT_TMPDIR", str(tmpdir)), ("REPO_CWD", repo_cwd), ("SKILL_KIND", "implement")]
        validate_no_newlines(rows)
        pointer = implement_pointer_path(args.claude_pid)
        assert_no_symlink_path_or_ancestors(pointer)
        pointer.parent.mkdir(parents=True, exist_ok=True)
        assert_no_symlink_path_or_ancestors(pointer)
        atomic_write(pointer, kv_text(rows))
        launcher = sessions_dir() / f"implement-run-{args.claude_pid}.sh"
        assert_no_symlink_path_or_ancestors(launcher)
        launcher.parent.mkdir(parents=True, exist_ok=True)
        assert_no_symlink_path_or_ancestors(launcher)
        atomic_write(launcher, implement_run_launcher_text(args.claude_pid), mode=0o755)
        return 0
    except (OSError, ValueError) as error:
        print(f"ERROR={error}", file=sys.stderr)
        return 1


def clear_implement_pointer_main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="session clear-implement-pointer", add_help=False)
    parser.add_argument("--claude-pid", default="")
    try:
        args = parser.parse_args(argv)
    except SystemExit:
        return 1
    try:
        if not _PID_RE.match(args.claude_pid):
            raise ValueError("Invalid --claude-pid: must be a positive integer of at most 7 decimal digits")
        target = implement_pointer_path(args.claude_pid)
        if target.exists() or target.is_symlink():
            target.unlink()
        return 0
    except (OSError, ValueError) as error:
        print(f"ERROR={error}", file=sys.stderr)
        return 1


def persist_run_flags_main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="session persist-run-flags", add_help=False)
    parser.add_argument("--implement-tmpdir", default="")
    parser.add_argument("--quick-mode", default="false")
    parser.add_argument("--no-issues", default="")
    parser.add_argument("--force-requested", default="false")
    parser.add_argument("--self-review-requested", default="false")
    parser.add_argument("--self-implement-requested", default="false")
    parser.add_argument("--difficulty-override", default="")
    try:
        args = parser.parse_args(argv)
        tmpdir = Path(args.implement_tmpdir)
        if not str(tmpdir):
            raise ValueError("--implement-tmpdir is required")
        if not tmpdir.is_dir():
            raise ValueError("--implement-tmpdir not a directory")
        rows = [
            ("QUICK_MODE", args.quick_mode),
            ("NO_ISSUES", args.no_issues),
            ("FORCE_REQUESTED", args.force_requested),
            ("SELF_REVIEW_REQUESTED", args.self_review_requested),
            ("SELF_IMPLEMENT_REQUESTED", args.self_implement_requested),
            ("DIFFICULTY_OVERRIDE", args.difficulty_override),
        ]
        for key, value in rows[:5]:
            if value not in _BOOL:
                raise ValueError(f"--{key.lower().replace('_', '-')} must be true or false")
        if args.difficulty_override and args.difficulty_override not in DIFFICULTIES:
            raise ValueError("--difficulty-override must be empty, TRIVIAL, MODERATE, or HARD")
        target = tmpdir / "run-flags.sh"
        confirm_writable(target, str(target))
        validate_writer_keys(rows, RUN_FLAG_KEYS)
        validate_no_newlines(rows)
        atomic_write(target, kv_text(rows))
        print("RUN_FLAGS_PERSISTED=true")
        return 0
    except (OSError, SystemExit, ValueError) as error:
        print(f"persist-implement-run-flags.sh: {error}", file=sys.stderr)
        return 2


def write_run_params_main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="session write-run-params", add_help=False)
    parser.add_argument("--output", default="")
    parser.add_argument("--partition-requested", default="")
    parser.add_argument("--brainstorm-requested", default="")
    parser.add_argument("--approve-requested", default="")
    parser.add_argument("--skip-approve-requested", default="")
    parser.add_argument("--difficulty", default="")
    try:
        args = parser.parse_args(argv)
    except SystemExit:
        return 2
    try:
        if not args.output:
            raise ValueError("missing required flag: --output")
        for flag in ("partition_requested", "brainstorm_requested", "approve_requested", "skip_approve_requested"):
            cli_flag = f"--{flag.replace('_', '-')}"
            if cli_flag not in argv:
                continue
            value = getattr(args, flag)
            if not value:
                raise ValueError(f"invalid {cli_flag}: requires a value")
            if value not in _BOOL:
                raise ValueError(f"invalid {cli_flag}: {value}")
        if args.difficulty and args.difficulty not in DIFFICULTIES:
            raise ValueError(f"invalid --difficulty: {args.difficulty}")
        out = Path(args.output)
        if not out.is_absolute():
            raise ValueError(f"--output must be absolute: {out}")
        if not writer_target_allowed(out):
            raise ValueError(f"output path not under allowed session root: {out}")
        if not out.parent.is_dir():
            print(f"write-run-params.sh: output directory not found: {out.parent}", file=sys.stderr)
            return 1
        if not safe_output_parent(out):
            raise OSError(f"output parent is not a writable directory: {out.parent}")
        payload = {
            "schema_version": 3,
            "partition_requested": args.partition_requested == "true",
            "brainstorm_requested": args.brainstorm_requested == "true",
            "approve_requested": args.approve_requested == "true",
            "skip_approve_requested": args.skip_approve_requested == "true",
            "difficulty_override": args.difficulty,
        }
        atomic_write(out, json.dumps(payload, indent=2, sort_keys=False) + "\n")
        print(f"RUN_PARAMS_WRITTEN={out}")
        return 0
    except (OSError, ValueError) as error:
        print(f"write-run-params.sh: {error}", file=sys.stderr)
        return 2


def restore_finalize_state_main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="session restore-finalize-state", add_help=False)
    parser.add_argument("--implement-tmpdir", default="")
    try:
        args = parser.parse_args(argv)
        if not args.implement_tmpdir:
            raise ValueError("--implement-tmpdir is required")
        tmpdir = Path(args.implement_tmpdir)
        if not tmpdir.is_dir():
            raise ValueError("--implement-tmpdir must exist")
        if not writer_target_allowed(tmpdir):
            raise ValueError(f"--implement-tmpdir not under allowed session root: {tmpdir}")
    except (SystemExit, ValueError) as error:
        print(f"restore-finalize-state.sh: {error}", file=sys.stderr)
        return 2
    state_file = tmpdir / "ship-pr-state.sh"
    finalize_file = tmpdir / "finalize-state.sh"
    bail_reason_file = tmpdir / "final-bail-reason.txt"
    if not state_file.is_file():
        print(f"restore-finalize-state.sh: warning: missing ship-pr state file: {state_file}", file=sys.stderr)
        return 1
    state = read_kv_raw(state_file)
    existing = read_kv_raw(finalize_file)
    rows: list[tuple[str, str]] = []
    keep_stall = existing.get("STALL_TRACKING", "") == "true"
    existing_stall_step = existing.get("STALL_STEP", "")
    for key in RESTORE_FINALIZE_KEYS:
        value = state.get(key, "")
        if keep_stall:
            if key == "STALL_TRACKING":
                value = "true"
            elif key == "STALL_STEP" and existing_stall_step:
                value = existing_stall_step
        if value == "":
            value = existing.get(key, RESTORE_FINALIZE_DEFAULTS.get(key, ""))
        rows.append((key, value))
    validate_no_newlines(rows)
    atomic_write(finalize_file, kv_text(rows))
    bail_reason = state.get("BAIL_REASON", "")
    atomic_write(bail_reason_file, bail_reason, create_parent=True)
    run_id = state.get("RUN_ID", "")
    if bail_reason and run_id:
        # The legacy verb derived the dispatcher from its own module location;
        # this reference sits one level below the same plugin root.
        root = Path(__file__).resolve().parents[1]
        subprocess.run(  # noqa: S603
            ["python3", str(root / "python" / "cli.py"), "run-log", "write",  # noqa: S607
             "--log-root", str(tmpdir / "larch-logs"), "--skill", "implement",
             "--run-id", run_id, "--batch", "final-bail-reason",
             "--input-file", str(bail_reason_file)],
            check=False, capture_output=True,
        )
    return 0


def resolve_trusted_design_env_main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="session resolve-trusted-design-env", add_help=False)
    parser.add_argument("--session-env-path", required=True)
    parser.add_argument("--claude-pid", default="")
    try:
        args = parser.parse_args(argv)
    except SystemExit:
        return 2
    if args.claude_pid and not _PID_RE.match(args.claude_pid):
        print("Invalid --claude-pid: must be a positive integer of at most 7 decimal digits", file=sys.stderr)
        return 2
    path = Path(args.session_env_path)
    if not args.claude_pid or not path.is_symlink():
        return 1
    if path != design_pointer_path(args.claude_pid):
        return 1
    ancestor = path.parent
    while True:
        if ancestor.is_symlink():
            return 1
        if ancestor == ancestor.parent:
            break
        ancestor = ancestor.parent
    resolved = path.resolve()
    if not resolved.is_file():
        return 1
    print(f"TRUSTED_SOURCE={resolved}")
    return 0


VERBS = {
    "write-env": write_env_main,
    "write-design-env": write_design_env_main,
    "write-implement-env": write_implement_env_main,
    "clear-implement-pointer": clear_implement_pointer_main,
    "persist-run-flags": persist_run_flags_main,
    "write-run-params": write_run_params_main,
    "restore-finalize-state": restore_finalize_state_main,
    "resolve-trusted-design-env": resolve_trusted_design_env_main,
}


def main() -> int:
    if len(sys.argv) < 2 or sys.argv[1] not in VERBS:
        print(f"unknown verb: {sys.argv[1:2]}", file=sys.stderr)
        return 64
    return VERBS[sys.argv[1]](sys.argv[2:])


if __name__ == "__main__":
    raise SystemExit(main())
