#!/usr/bin/env bash
# /design session env — generated by write-design-current-env.sh. Do not edit.
export DESIGN_TMPDIR=<TMPDIR>
export SESSION_TMPDIR=<TMPDIR>
export SESSION_ID=53C92170-2F5E-4BD0-A869-F4C44BAF9A78
export ISSUE_NUMBER=3466
export CODEX_PRESENT=true
export CURSOR_PRESENT=true
export CODEX_AVAILABLE=true
export CURSOR_AVAILABLE=true
export LARCH_EXTERNAL_HEALTH_CHECK_TIMEOUT=30
export CLAUDE_PLUGIN_ROOT=<OPERATOR_REPO_PATH>/plugins/cache/larch-local/larch/47.0.70
