# pyright: reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnusedCallResult=false, reportOptionalMemberAccess=false, reportPrivateUsage=false, reportUnusedImport=false
"""Agent launcher helpers, CLI entrypoints, and failure classification.

Implementation is split across sibling modules by responsibility:
- _types: shared types, constants, IO utilities
- _launch_failure: failure classification, model args
- _failure_diag: usage parsing, failure diagnostics
- _run_external: external agent runner, shared launcher helpers
- _auth: cursor auth, probe helpers, reviewer check, degraded tools
- _drafter: drafter and negotiation launchers
- _ci_launcher: CI and implement launchers
- _review_launcher: review launcher (codex, cursor)
- _claude_runner: claude subprocess runner and waterfall
"""

from __future__ import annotations

# pylint: disable=W0614,W0611,W0401  # wildcard and named imports are intentional re-exports for backward compat
from larch.agents._types import *  # noqa: F403
from larch.agents._launch_failure import *  # noqa: F403
from larch.agents._failure_diag import *  # noqa: F403
from larch.agents._run_external import *  # noqa: F403
from larch.agents._auth import *  # noqa: F403
from larch.agents._drafter import *  # noqa: F403
from larch.agents._ci_launcher import *  # noqa: F403
from larch.agents._review_launcher import *  # noqa: F403
from larch.agents._claude_runner import *  # noqa: F403

# Private symbols not exported by __all__ (or no __all__) — explicit re-exports
# so callers using `from larch.agents.agents import _foo` continue to work.
from larch.agents._types import (  # noqa: F401
    _PARSE_RE,
    _REFUSAL_RE,
    _QUOTA_RE,
    _CLAUDE_AUTH_FAST_FAIL_WINDOW,
    _CLAUDE_DEGRADED_AUTH_RE,
    _CLAUDE_STDERR_SCAN_TAIL_BYTES,
    _AUTH_RE,
    _SAFE_META_PATH_RE,
    _CTRL_RE,
    _PLUGIN_ROOT,
    _PY_CLI,
    _CURSOR_AUTH_MAX_ATTEMPTS,
    _MAX_CONTEXT_FILES,
    _MAX_CLAUDE_TIMEOUT,
    _DEFAULT_CURSOR_CI_STALL_THRESHOLD,
    _TOML_CLOSED_STRING_DELIMITER_COUNT,
    _AUTH_RETRY_RC,
    _PROBE_NO_RETRY_RC,
    _CURSOR_PREFLIGHT_AUTH_RC,
    _CLAUDE_REVIEW_READ_ONLY_PREAMBLE,
    _CURSOR_DEGRADED_OUTPUT_TOKEN_FLOOR,
    _CURSOR_DEGRADED_RESULT_BYTES_CEILING,
    _CURSOR_NO_WORK_INPUT_TOKEN_FLOOR,
    _err,
    _emit,
    _emit_kv,
    _read_text,
    _write,
    _append,
    _parse_positive_or_zero_int,
    _is_positive_int,
    _valid_model_token,
    _validate_meta_path,
    _sanitize_tool_label,
    _json_array,
    _plugin_root,
    _env_int,
)
from larch.agents._launch_failure import (  # noqa: F401
    _fallback_launcher_exit,
    _parse_launcher_exit_value,
    _read_launcher_done,
    _launcher_failure_class_from_text,
)
from larch.agents._failure_diag import (  # noqa: F401
    _truncate_utf8_bytes,
    _failed_agent_tail_lines_default,
    _tail_redacted,
    _write_stderr_tail,
    _vendor_failure_diag_cap,
    _failure_diag_section_body,
    _compose_failure_diag,
    _review_failure_auth_paths,
    _implement_failure_auth_paths,
    _num,
    _dig,
    _first_not_none,
    _has_tokenish,
    _usage_row,
    _stderr_tail_from_less_specific_carrier,
    _failure_diagnostic_source_candidates,
)
from larch.agents._run_external import (  # noqa: F401
    _positive_int_env,
    _nonnegative_float_env,
    _cursor_ci_stall_sidecar_dir,
    _git_status_excerpt,
    _tree_latest_mtime,
    _stall_channel_progress,
    _emit_elapsed_minute_if_needed,
    _terminate_child_processes_first,
    _write_cursor_ci_stall_artifacts,
    _prepare_run_external_agent_files,
    _positive_int_ctx,
    _emit_claude_subprocess_failure_fields,
    _record_usage_from_events,
    _mirror_codex_quota_from_events,
    _CODEX_POLICY_REJECTION_TAIL_BYTES,
    _CODEX_POLICY_REJECTION_EXCERPT_BYTES,
    _CODEX_EXEC_COMMAND_FAILED_RE,
    _CODEX_POLICY_BLOCKED_RE,
    _codex_policy_rejection_excerpt,
    _read_tail_update,
    _codex_policy_watch_path,
    _stop_policy_rejected_process,
    _codex_policy_rejection_fast_fail,
    _policy_rejection_marker_present,
    _codex_env_key_enabled,
    _codex_auth_args,
    _strip_codex_config,
    _prepare_codex_home,
    _ci_failure_source,
    _resolve_execution_issues_log,
    _append_ci_failure,
    _append_vendor_failure_diagnostics,
    _write_preflight_bundle,
    _trust_config_arg,
    _git_toplevel,
    _read_keepalive_clone_path,
    _clone_path_from_session_tmpdir,
    _clone_path_from_parent_walk,
    _resolve_review_codex_workdir,
    _auth_retry_limit,
    _is_unclassified_empty_startup_failure,
    _temporary_env,
    _record_launch_timing,
    _finalize_launch,
    _post_codex_events,
    _emit_token_record_if_present,
    _record_usage_from_events_and_emit_token,
    _write_timeout_stall_json,
    _run_external_agent_with_auth_retries,
    _record_cursor_usage_from_output,
    _under,
    _promote_inner_done,
    _CODEX_REVIEW_STRICT_PREAMBLE,
    _CURSOR_SANDBOX_ENFORCEMENT_LINE,
    _CURSOR_REVIEW_STRICT_PREAMBLE,
    _REVIEW_MAX_TRANSIENT_RETRIES,
    _COLLECTOR_NS_STRONG_HEADER,
)
from larch.agents._auth import (  # noqa: F401
    _max_transient_probe_retries,
    _max_timeout_probe_retries,
    _probe_tmpdir,
    _probe_user,
    _probe_stamp_path,
    _codex_probe_stamp_kind,
    _read_fresh_probe_stamp,
    _write_probe_stamp,
    _temporary_environ,
    _run_probe_command,
    _CursorProbeSetup,
    _cursor_probe_setup_chain,
    _cursor_probe_cleanup_private_config_dir,
    _run_one_cursor_probe,
    _run_one_codex_probe,
    _run_codex_probes,
    _run_cursor_probes,
    _norm_bool,
    _norm_tristate,
    _tool_state,
    _state_phrase,
    _read_plugin_version_best_effort,
)
from larch.agents._drafter import (  # noqa: F401
    _negotiation_base,
    _positions,
    _plan_contains_standalone_scout_manifest,
    _validate_drafter_timeout,
    _reject_control_or_dotdot,
    _canonical_existing_file_for_drafter,
    _canonical_existing_dir_for_drafter,
    _canonical_output_for_drafter,
    _write_drafter_status_file,
    _write_drafter_dirty_tree_sidecar,
    _filter_drafter_scout,
    _write_dialectic_pending,
    _launch_codex_exec_inprocess,
    _drafter_token_raw,
)
from larch.agents._ci_launcher import (  # noqa: F401
    _validate_ci_args,
    _validate_conflict_files_csv,
    _validate_failure_log_path,
    _read_failure_context,
    _ci_parser,
    _ci_prompt,
    _implement_parser,
    _validate_implement_common,
    _path_under,
    _canonical_existing_nonsymlink_dir,
    _validate_codex_implement_paths,
    _hydrate_implement_session_env,
    _implement_resume_block,
    _strip_frontmatter_body,
    _implement_prompt,
    _emit_implement_launcher_envelope,
    _implement_token_budget_hit,
    _append_implement_launch_failure,
    _record_implement_timing,
    _record_cursor_implement_usage,
    _validate_lint_fix_args,
    _emit_ci_launcher_result,
    _append_implement_failure_if_nonzero,
    _safe_codex_home_dir,
)
from larch.agents._review_launcher import (  # noqa: F401
    _review_parser,
    _review_coerce_risk,
    _review_validate_args,
    _review_session_env_path,
    _review_specialist_render_args,
    _review_render_specialist_prompt,
    _review_read_prompt_file,
    _review_codex_compact_sentinel_offset,
    _review_read_codex_prompt_sentinel,
    _review_resolve_prompt,
    _review_write_codex_prompt_sidecar,
    _review_append_launch_failure,
    _review_append_outer_meta,
    _review_cursor_has_structured_findings,
    _review_cursor_normalize_no_issues,
    _review_cursor_postprocess,
    _review_emit_launcher_result,
    _review_failure_source,
    _review_record_timing,
    _review_run_with_retries,
    _review_launch_codex,
    _review_launch_cursor,
    _review_run_wrapper_attempt,
    _review_capture_cursor_dirty_baseline,
    _review_write_cursor_dirty_tree_from_baseline,
    _review_effective_token_cap,
    _review_check_budget_or_write_cap_hit,
    _review_apply_session_token_env,
    _review_write_clean_readonly_dirty_tree,
    _review_run_test_trap_after_inner_done_if_enabled,
    _review_setup_cursor_config_dir,
    _review_cleanup_cursor_config_dir,
)
from larch.agents._claude_runner import (  # noqa: F401
    _canonical,
    _validate_context_file,
    _validate_prompt_file,
    _validate_claude_output,
    _root_allowed_for_context,
    _read_file_tail_text,
    _run_claude_with_stdin,
    _claude_token_raw,
    _record_claude_sub_usage,
    _record_claude_ci_usage,
    _render_context_files,
    _with_claude_read_only_preamble,
    _DEFAULT_SCRIPTS_DIR,
    _TOKEN_SIDECAR_ENV_UNSET,
    LaunchFn,
)
