#!/usr/bin/env bash
# /design session env — generated by write-design-current-env.sh. Do not edit.
export DESIGN_TMPDIR=<TMPDIR>
export SESSION_TMPDIR=<TMPDIR>
export SESSION_ID=83BB588F-41BA-489D-8691-BFCBBBC1DE78
export CODEX_PRESENT=true
export CURSOR_PRESENT=true
export CODEX_AVAILABLE=true
export CURSOR_AVAILABLE=true
export CLAUDE_PLUGIN_ROOT=<OPERATOR_REPO_PATH>/plugins/cache/larch-local/larch/42.5.1
# sketch-collect (collect-agent-results.51841)
export LARCH_BREADCRUMB_STREAM="<TMPDIR>/breadcrumbs/collect-agent-results.collect-agent-results.51841.ndjson"
export LARCH_DONE_SENTINEL="<TMPDIR>/breadcrumbs/collect-agent-results.collect-agent-results.51841.done.pjiqRa"
export LARCH_STATUS_FILE="<TMPDIR>/breadcrumbs/collect-agent-results.collect-agent-results.51841.status.YMdy5o"
export LARCH_QUIET_LOG_FILE="<TMPDIR>/breadcrumbs/collect-agent-results.collect-agent-results.51841.quiet.F1jlIM"
export LARCH_BREADCRUMBS_SURFACED_FILE="<TMPDIR>/breadcrumbs/collect-agent-results.collect-agent-results.51841.surfaced.7fdkUe"
# /larch:issue invocation
export ISSUE_TMPDIR="<TMPDIR>"
export REPO="character-ai/larch"
export SENTINEL_PATH="<TMPDIR>/oos-issue-sentinel"
export SENTINEL_PATH_EXPLICIT="true"
export INPUT_FILE="<TMPDIR>/oos-combined.md"
export TITLE_PREFIX="[OOS]"
export BLOCKED_BY_ISSUE="2790"
export INTRA_BATCH_DEPS_FILE="<TMPDIR>/oos-intra-batch-deps.tsv"
export BLOCKED_BY_ISSUE_STATE="open"
export BLOCKED_BY_ISSUE_ID="4515172751"
export BLOCKED_BY_ISSUE_TITLE="[DESIGNING] [OOS] Finish breadcrumb propagation rollout (issue #2749 follow-up)"
export BLOCKED_BY_ISSUE_URL="https://github.com/character-ai/larch/issues/2790"
