#!/usr/bin/env bash
# /design session env — generated by session_env.py. Do not edit.
export DESIGN_TMPDIR=<TMPDIR>
export SESSION_TMPDIR=<TMPDIR>
export SESSION_ID=7830915E-E3DF-4FAF-8A4F-F7A76092CB83
export REPO=character-ai/larch
export ISSUE_NUMBER=4776
export CODEX_BINARY_FOUND=true
export CURSOR_BINARY_FOUND=true
export LARCH_EXTERNAL_HEALTH_CHECK_TIMEOUT=60
export CLAUDE_PLUGIN_ROOT=<OPERATOR_REPO_PATH>/plugins/cache/larch-local/larch/51.3.1
