#!/usr/bin/env bash
# /design session env — generated by write-design-current-env.sh. Do not edit.
export DESIGN_TMPDIR=<TMPDIR>
export SESSION_TMPDIR=<TMPDIR>
export SESSION_ID=0248EAB3-5EAA-4057-993E-8E9FC9809735
export REPO=character-ai/larch
export ISSUE_NUMBER=3771
export CODEX_PRESENT=true
export CURSOR_PRESENT=false
export CODEX_AVAILABLE=true
export CURSOR_AVAILABLE=false
export CODEX_BINARY_FOUND=true
export CURSOR_BINARY_FOUND=true
export LARCH_EXTERNAL_HEALTH_CHECK_TIMEOUT=30
export CLAUDE_PLUGIN_ROOT=<OPERATOR_REPO_PATH>/plugins/cache/larch-local/larch/49.0.0
