//! Black-box contracts for the small developer-tooling Rust selectors.

use std::{fs, path::Path, process::Command as StdCommand};

use assert_cmd::Command;
use predicates::prelude::*;
use tempfile::{Builder, TempDir};

fn larch() -> Command {
    Command::cargo_bin("larch").expect("larch binary should build")
}

fn git(root: &Path, arguments: &[&str]) {
    let status = StdCommand::new("git")
        .args(arguments)
        .current_dir(root)
        .status()
        .expect("git should run");
    assert!(status.success(), "git {arguments:?} failed");
}

fn repository() -> TempDir {
    repository_named("larch-developer-tooling-")
}

fn repository_named(prefix: &str) -> TempDir {
    let directory = Builder::new()
        .prefix(prefix)
        .tempdir()
        .expect("temporary repository");
    git(directory.path(), &["init", "-q", "-b", "main"]);
    directory
}

fn write(root: &Path, relative: &str, contents: &[u8]) {
    let path = root.join(relative);
    fs::create_dir_all(path.parent().expect("fixture parent")).expect("create fixture parent");
    fs::write(path, contents).expect("write fixture");
}

#[test]
fn alias_generate_matches_the_legacy_yaml_contract() {
    larch()
        .args([
            "alias",
            "generate",
            "--name",
            "q",
            "--target",
            "implement",
            "--target-dir",
            "/tmp/repo/skills/q",
            "--flags",
            "--foo \"bar\"",
            "--version",
            "1.2.3",
        ])
        .assert()
        .success()
        .stdout(
            r#"---
# larch-run-lifecycle: shared-v1 skill=q
name: q
description: "Alias for /implement --foo \"bar\" (created by /alias)"
argument-hint: "<arguments>"
allowed-tools: Bash(*scripts/larch.sh:*), Read, Skill
---

**MANDATORY: Follow the complete shared lifecycle contract in `${CLAUDE_PLUGIN_ROOT}/skills/shared/run-lifecycle.md` with declared skill `q`.**

**MANDATORY: READ ENTIRE FILE before composing user-facing prose: `${CLAUDE_PLUGIN_ROOT}/skills/shared/readability-style.md`.**

Auto-generated alias created by larch /alias. Invokes /implement with preset flags.

## Usage

/q <arguments> is equivalent to /implement --foo "bar" <arguments>

## Behavior

Invoke the Skill tool:
- Try skill: "implement" first (bare name). If no skill matches, try skill: "larch:implement" (fully-qualified plugin name).
- args: --lifecycle-parent-context "$CONTEXT_FILE" --foo "bar" $ARGUMENTS

After the Skill tool loads /implement, the child skill MUST begin execution at its Step 0 (session setup). Do not investigate the codebase, plan, or implement anything before Step 0 completes.

Generated by larch /alias v1.2.3
"#,
        );
}

#[test]
fn alias_generate_without_flags_or_version_is_a_byte_golden() {
    larch()
        .args([
            "alias",
            "generate",
            "--name",
            "q",
            "--target",
            "research",
            "--target-dir",
            "/tmp/repo/skills/q",
        ])
        .assert()
        .success()
        .stdout(
            r#"---
# larch-run-lifecycle: shared-v1 skill=q
name: q
description: "Alias for /research (created by /alias)"
argument-hint: "<arguments>"
allowed-tools: Bash(*scripts/larch.sh:*), Read, Skill
---

**MANDATORY: Follow the complete shared lifecycle contract in `${CLAUDE_PLUGIN_ROOT}/skills/shared/run-lifecycle.md` with declared skill `q`.**

**MANDATORY: READ ENTIRE FILE before composing user-facing prose: `${CLAUDE_PLUGIN_ROOT}/skills/shared/readability-style.md`.**

Auto-generated alias created by larch /alias. Invokes /research with preset flags.

## Usage

/q <arguments> is equivalent to /research <arguments>

## Behavior

Invoke the Skill tool:
- Try skill: "research" first (bare name). If no skill matches, try skill: "larch:research" (fully-qualified plugin name).
- args: --lifecycle-parent-context "$CONTEXT_FILE" $ARGUMENTS

Generated by larch /alias
"#,
        );
}

#[test]
fn alias_target_resolution_uses_worktree_private_and_consumer_routes() {
    let repository = repository_named("alias root $() ");
    let root = repository.path();
    let canonical_root = fs::canonicalize(root).expect("canonical fixture root");
    write(root, ".claude-plugin/plugin.json", b"{}");
    write(root, "skills/implement/SKILL.md", b"# implement\n");

    larch()
        .args(["alias", "resolve-target", "--alias-name", "my-alias"])
        .current_dir(root)
        .assert()
        .success()
        .stdout(predicate::str::contains(format!(
            "REPO_ROOT={}\n",
            canonical_root.display()
        )))
        .stdout(predicate::str::contains("PLUGIN_REPO=true\n"))
        .stdout(predicate::str::contains(format!(
            "TARGET_DIR={}/skills/my-alias\n",
            canonical_root.display()
        )));

    larch()
        .args([
            "alias",
            "resolve-target",
            "--alias-name",
            "my-alias",
            "--private",
        ])
        .current_dir(root)
        .assert()
        .success()
        .stdout(predicate::str::contains(format!(
            "TARGET_DIR={}/.claude/skills/my-alias\n",
            canonical_root.display()
        )));

    let consumer = repository_named("consumer root [] ");
    let consumer_root = consumer.path();
    let canonical_consumer = fs::canonicalize(consumer_root).expect("canonical consumer root");
    larch()
        .args(["alias", "resolve-target", "--alias-name", "my-alias"])
        .current_dir(consumer_root)
        .assert()
        .success()
        .stdout(predicate::str::contains(format!(
            "REPO_ROOT={}\nPLUGIN_REPO=false\nTARGET_DIR={}/.claude/skills/my-alias\n",
            canonical_consumer.display(),
            canonical_consumer.display()
        )));
}

#[test]
fn alias_target_resolution_rejects_invalid_names_and_missing_repository() {
    let outside = TempDir::new().expect("temporary non-repository");
    larch()
        .args(["alias", "resolve-target", "--alias-name", "not_valid"])
        .current_dir(outside.path())
        .assert()
        .failure()
        .stderr("ERROR: alias-name 'not_valid' is invalid (must match ^[a-z][a-z0-9-]*$)\n");

    larch()
        .args(["alias", "resolve-target", "--alias-name", "valid"])
        .current_dir(outside.path())
        .assert()
        .failure()
        .stderr("ERROR: not in a git repository\n");
}

#[test]
fn residual_bash_paths_preserve_manifest_order_and_git_intersection() {
    let repository = repository_named("residual root $() ");
    let root = repository.path();
    write(
        root,
        "scripts/residual-bash-paths.txt",
        b"# retained shell entrypoints\n\nscripts/tracked.sh\n scripts/space $(meta).sh \nscripts/untracked.sh\n",
    );
    write(root, "scripts/tracked.sh", b"#!/usr/bin/env bash\n");
    write(root, "scripts/space $(meta).sh", b"#!/usr/bin/env bash\n");
    write(root, "scripts/untracked.sh", b"#!/usr/bin/env bash\n");
    git(
        root,
        &[
            "add",
            "scripts/residual-bash-paths.txt",
            "scripts/tracked.sh",
            "scripts/space $(meta).sh",
        ],
    );

    larch()
        .args([
            "residual-bash",
            "paths",
            "--root",
            &root.display().to_string(),
            "--check-exists",
        ])
        .assert()
        .success()
        .stdout("scripts/tracked.sh\nscripts/space $(meta).sh\nscripts/untracked.sh\n");
    larch()
        .args([
            "residual-bash",
            "paths",
            "--root",
            &root.display().to_string(),
            "--intersect-git",
            "--null-delimited",
        ])
        .assert()
        .success()
        .stdout(b"scripts/tracked.sh\0scripts/space $(meta).sh\0scripts/untracked.sh\0" as &[u8]);
}

#[test]
fn residual_bash_paths_reject_invalid_and_duplicate_manifest_rows() {
    let directory = TempDir::new().expect("temporary manifest root");
    let root = directory.path();
    write(
        root,
        "scripts/residual-bash-paths.txt",
        b"scripts/kept.sh\nscripts/kept.sh\n",
    );
    write(root, "scripts/kept.sh", b"#!/usr/bin/env bash\n");
    larch()
        .args([
            "residual-bash",
            "paths",
            "--root",
            &root.display().to_string(),
        ])
        .assert()
        .code(2)
        .stderr(predicate::str::contains("duplicate residual bash path"));

    write(
        root,
        "scripts/residual-bash-paths.txt",
        b"node_modules/vendor.sh\n",
    );
    larch()
        .args([
            "residual-bash",
            "paths",
            "--root",
            &root.display().to_string(),
        ])
        .assert()
        .code(2)
        .stderr("ERROR: excluded residual bash path: 'node_modules/vendor.sh'\n");

    write(
        root,
        "scripts/residual-bash-paths.txt",
        b"scripts/../escape.sh\n",
    );
    larch()
        .args([
            "residual-bash",
            "paths",
            "--root",
            &root.display().to_string(),
        ])
        .assert()
        .code(2)
        .stderr("ERROR: invalid residual bash path: 'scripts/../escape.sh'\n");

    write(
        root,
        "scripts/residual-bash-paths.txt",
        b"scripts/missing.sh\n",
    );
    larch()
        .args([
            "residual-bash",
            "paths",
            "--root",
            &root.display().to_string(),
            "--check-exists",
        ])
        .assert()
        .code(2)
        .stderr(predicate::str::contains("missing residual bash path under"));
}

#[test]
fn verify_skill_called_covers_sentinel_stdout_and_malformed_modes() {
    let directory = TempDir::new().expect("temporary verification root");
    let root = directory.path();
    write(root, "sentinel", b"ok\n");
    write(root, "empty-sentinel", b"");
    write(root, "stdout.txt", b"alpha\nrelease-42\n");
    larch()
        .args([
            "verify",
            "skill-called",
            "--sentinel-file",
            &root.join("sentinel").display().to_string(),
        ])
        .assert()
        .success()
        .stdout("VERIFIED=true\nREASON=ok\n");
    larch()
        .args([
            "verify",
            "skill-called",
            "--sentinel-file",
            &root.join("missing").display().to_string(),
        ])
        .assert()
        .success()
        .stdout("VERIFIED=false\nREASON=missing_path\n");
    larch()
        .args([
            "verify",
            "skill-called",
            "--sentinel-file",
            &root.join("empty-sentinel").display().to_string(),
        ])
        .assert()
        .success()
        .stdout("VERIFIED=false\nREASON=empty_file\n");
    larch()
        .args([
            "verify",
            "skill-called",
            "--stdout-line",
            "^release-[0-9]+$",
            "--stdout-file",
            &root.join("stdout.txt").display().to_string(),
        ])
        .assert()
        .success()
        .stdout("VERIFIED=true\nREASON=ok\n");
    larch()
        .args([
            "verify",
            "skill-called",
            "--stdout-line",
            "^absent$",
            "--stdout-file",
            &root.join("stdout.txt").display().to_string(),
        ])
        .assert()
        .success()
        .stdout("VERIFIED=false\nREASON=no_match\n");
    larch()
        .args([
            "verify",
            "skill-called",
            "--stdout-line",
            "[",
            "--stdout-file",
            &root.join("stdout.txt").display().to_string(),
        ])
        .assert()
        .failure()
        .stderr("ERROR: grep failed (exit 2) - regex may be malformed or file unreadable\n");
    larch()
        .args([
            "verify",
            "skill-called",
            "--stdout-line",
            "release",
            "--stdout-file",
            &root.join("missing-stdout.txt").display().to_string(),
        ])
        .assert()
        .success()
        .stdout("VERIFIED=false\nREASON=missing_stdout_file\n");
    larch()
        .args(["verify", "skill-called", "--commit-delta"])
        .assert()
        .failure()
        .stderr(
            "Usage: verify skill-called (--sentinel-file PATH | --stdout-line RE --stdout-file PATH | --commit-delta N --before-count N)\n",
        );
}

#[test]
fn verify_skill_called_covers_commit_delta_mode() {
    let repository = repository();
    let repository_root = repository.path();
    write(repository_root, "tracked.txt", b"one\n");
    git(repository_root, &["add", "tracked.txt"]);
    git(
        repository_root,
        &[
            "-c",
            "user.name=Fixture",
            "-c",
            "user.email=fixture@example.invalid",
            "commit",
            "-qm",
            "base",
        ],
    );
    git(repository_root, &["switch", "-q", "-c", "feature"]);
    write(repository_root, "tracked.txt", b"two\n");
    git(repository_root, &["add", "tracked.txt"]);
    git(
        repository_root,
        &[
            "-c",
            "user.name=Fixture",
            "-c",
            "user.email=fixture@example.invalid",
            "commit",
            "-qm",
            "change",
        ],
    );
    larch()
        .args([
            "verify",
            "skill-called",
            "--commit-delta",
            "1",
            "--before-count",
            "0",
        ])
        .current_dir(repository_root)
        .assert()
        .success()
        .stdout("VERIFIED=true\nREASON=ok\n");
    larch()
        .args([
            "verify",
            "skill-called",
            "--commit-delta",
            "0",
            "--before-count",
            "2",
        ])
        .current_dir(repository_root)
        .assert()
        .success()
        .stdout("VERIFIED=false\nREASON=commit_delta_mismatch\n");
}
