#[rustfmt::skip]
mod tests {
#![allow(clippy::cognitive_complexity, clippy::literal_string_with_formatting_args)] // Each test keeps one frozen filesystem transaction and embedded shell fixture readable end to end.
use std::{fs, path::{Path, PathBuf}, process::{Command, Output}};
#[cfg(unix)] use std::os::unix::fs::{PermissionsExt as _, symlink};
use tempfile::TempDir;

fn repo() -> PathBuf { Path::new(env!("CARGO_MANIFEST_DIR")).join("../..").canonicalize().expect("repo root") }
fn design(sandbox: &TempDir) -> PathBuf { let path=sandbox.path().join("design"); fs::create_dir(&path).expect("design"); path }
fn run(root: Option<&Path>, verb: &str, extra: &[&str], envs: &[(&str, &Path)]) -> Output {
    let mut command=Command::new(env!("CARGO_BIN_EXE_larch")); command.args(["plan-review",verb]).env("LARCH_BINARY",env!("CARGO_BIN_EXE_larch"));
    if let Some(root)=root { command.arg("--design-tmpdir").arg(root); }
    command.args(extra).env("CLAUDE_PLUGIN_ROOT",repo()).env("LARCH_QUIET_DISABLE","1");
    for (key,value) in envs { command.env(key,value); }
    command.output().expect("run larch")
}
fn out(output:&Output)->String { String::from_utf8_lossy(&output.stdout).into_owned() }
fn err(output:&Output)->String { String::from_utf8_lossy(&output.stderr).into_owned() }
fn text(path:impl AsRef<Path>)->String { fs::read_to_string(path).expect("read text") }
#[cfg(unix)] fn script(path:&Path, body:&str) { fs::write(path,format!("#!/usr/bin/env bash\nset -eu\n{body}\n")).expect("write script"); let mut mode=fs::metadata(path).expect("metadata").permissions(); mode.set_mode(0o755); fs::set_permissions(path,mode).expect("chmod"); }

#[test]
fn preview_and_finalize_bytes_are_frozen() {
    let missing=run(None,"preview",&[],&[]); assert!(missing.status.success()); assert_eq!(out(&missing),"**⚠ 3: DESIGN_TMPDIR missing or invalid; cannot present plan candidate for review**\n"); assert!(err(&missing).is_empty());
    let sandbox=TempDir::new().expect("sandbox"); let root=design(&sandbox); fs::write(root.join("plan.txt"),"# Plan\nbody\n").expect("plan");
    let preview=run(Some(&root),"preview",&[],&[]); assert!(preview.status.success()); assert_eq!(out(&preview),"## Plan Candidate for Review\n\n# Plan\nbody\n"); assert!(err(&preview).is_empty()); assert!(root.join(".step3-entry-plan-printed").is_file());
    let gatec=run(Some(&root),"preview",&["--variant","gatec"],&[]); assert_eq!(out(&gatec),"## Final Design Plan\n\n# Plan\nbody\n");
    let large=Command::new(env!("CARGO_BIN_EXE_larch")).args(["plan-review","preview","--design-tmpdir"]).arg(&root).args(["--variant","step2b"]).env("LARCH_DESIGN_PLAN_SUMMARY_THRESHOLD","0").output().expect("large preview"); assert_eq!(out(&large),"## Implementation Plan\n\nThe plan is very large. Showing the full plan body below.\n\n# Plan\nbody\n");
    let finalized=run(Some(&root),"finalize",&[],&[]); assert!(finalized.status.success()); assert_eq!(out(&finalized),"FINALIZE_PLAN_STATUS=ok\n"); assert_eq!(text(root.join("voting-tally.md")),"## Plan Review Tally\n\n");
    fs::remove_file(root.join("accepted-plan-findings.md")).expect("remove artifact"); fs::create_dir(root.join("accepted-plan-findings.md")).expect("invalid artifact"); let invalid=run(Some(&root),"finalize",&[],&[]); assert_eq!(invalid.status.code(),Some(1)); assert_eq!(out(&invalid),"FINALIZE_PLAN_STATUS=invalid-artifact\n");
}

#[test]
fn utility_and_persistence_transactions_are_exact() {
    let sandbox=TempDir::new().expect("sandbox"); let root=design(&sandbox); let retally=root.join("retally.env");
    fs::write(&retally,format!("VOTING_TALLY_FILE={}\nACCEPTED_COUNT=2\nIMPORTANT_ACCEPTED_COUNT=1\nSCOPE_ANCHOR_FILE={}\n",root.join("voting-tally.md").display(),root.join("plan-review-scope-anchor.txt").display())).expect("retally");
    fs::write(root.join(".step3-plan-review-result.env"),"ROUNDS_COMPLETED=2\nFINAL_ROUND_NUM=2\nROUND_NUM=7\n").expect("existing");
    let persisted=run(Some(&root),"persist-retally-env",&["--retally-stdout-file",retally.to_str().expect("path"),"--retally-input-anchor","unused","--tally-plan-review-status","ok","--loop-status","complete"],&[]); assert_eq!(out(&persisted),"PERSIST_RETALLY_STATUS=ok\n");
    let expected=format!("TALLY_PLAN_REVIEW_STATUS=ok\nLOOP_STATUS=complete\nVOTING_TALLY_FILE={}\nROUNDS_COMPLETED=2\nFINAL_ROUND_NUM=2\nACCEPTED_COUNT=2\nIMPORTANT_ACCEPTED_COUNT=1\n",root.join("voting-tally.md").display()); assert_eq!(text(root.join(".step3-plan-review-result.env")),format!("{expected}ROUND_NUM=7\n")); assert_eq!(text(root.join(".step3-review-result.env")),expected);
    let start=run(Some(&root),"persist-round-start-s",&["--round-num","2","--start-s","123"],&[]); assert!(start.status.success()); assert_eq!(text(root.join("plan-review/round-2/round-start-s")),"123\n"); let again=run(Some(&root),"persist-round-start-s",&["--round-num","2","--start-s","456"],&[]); assert!(again.status.success()); assert_eq!(text(root.join("plan-review/round-2/round-start-s")),"123\n");
    fs::write(root.join("params.json"),"{\"enabled\":true,\"string\":\"true\"}\n").expect("json"); let boolean=run(None,"json-get-bool",&["--path",root.join("params.json").to_str().expect("path"),"--key","enabled"],&[]); assert_eq!(out(&boolean),"true\n"); let typed=run(None,"json-get-bool",&["--path",root.join("params.json").to_str().expect("path"),"--key","string","--default","false"],&[]); assert_eq!(out(&typed),"false\n");
    let root_arg=root.to_str().expect("path"); let drift=run(None,"drift-baseline",&["write-once","--design-tmpdir",root_arg,"--plan-lines","10","--diff-lines","20"],&[]); assert!(drift.status.success()); assert_eq!(text(root.join("drift-baseline.env")),"BASELINE_PLAN_LINES=10\nBASELINE_DIFF_LINES=20\n");
    for (verb,name,expected) in [("round-artifact-included","round-summary.env",0),("round-artifact-included","debug.txt",1),("round-revise-artifact-included","revise.env",1),("round-revise-artifact-excluded","codex-output.txt",0)] { assert_eq!(run(None,verb,&[name],&[]).status.code(),Some(expected)); }
}

#[test]
fn argument_errors_and_known_argument_compatibility_are_exact() {
    let sandbox=TempDir::new().expect("sandbox"); let root=design(&sandbox);
    let known=run(Some(&root),"step35",&["--future-option","value"],&[]); assert!(known.status.success()); assert_eq!(out(&known),"APPROVE_REQUESTED=false\n"); assert!(err(&known).is_empty());
    let invalid_round=run(Some(&root),"persist-round-start-s",&["--round-num","x","--start-s","1"],&[]); assert_eq!(invalid_round.status.code(),Some(2)); assert!(out(&invalid_round).is_empty()); assert_eq!(err(&invalid_round),"usage: cli.py plan-review persist-round-start-s [-h] --design-tmpdir\n                                                DESIGN_TMPDIR --round-num\n                                                ROUND_NUM --start-s START_S\ncli.py plan-review persist-round-start-s: error: argument --round-num: invalid int value: 'x'\n");
    let invalid_choice=run(Some(&root),"continuation",&["--approve-requested","maybe"],&[]); assert_eq!(invalid_choice.status.code(),Some(2)); assert!(out(&invalid_choice).is_empty()); assert_eq!(err(&invalid_choice),"usage: cli.py plan-review continuation [-h] --design-tmpdir DESIGN_TMPDIR\n                                       --approve-requested {true,false}\ncli.py plan-review continuation: error: argument --approve-requested: invalid choice: 'maybe' (choose from 'true', 'false')\n");
    let invalid_drift=run(None,"drift-baseline",&["write-once","--design-tmpdir",root.to_str().expect("root"),"--plan-lines","x","--diff-lines","1"],&[]); assert_eq!(invalid_drift.status.code(),Some(1)); assert!(out(&invalid_drift).is_empty()); assert!(err(&invalid_drift).is_empty());
}

#[test]
fn step3_state_and_continuation_round_trip() {
    let sandbox=TempDir::new().expect("sandbox"); let root=design(&sandbox); fs::create_dir(root.join(".completed")).expect("completed");
    for name in ["step-3","step-3.5","step-3b","step-4","step-4b"] { fs::write(root.join(".completed").join(name),"").expect("sentinel"); }
    fs::write(root.join("review-round-count.txt"),"1\n").expect("count"); fs::write(root.join(".step3-reentry"),"").expect("reentry"); fs::write(root.join(".step3-round-1.phase"),"awaiting-apply\n").expect("phase"); fs::write(root.join(".step3-applied-finding-keys.tsv"),"1\tkey\n").expect("ledger");
    let direct=run(Some(&root),"step3-state",&["--direct-review-entry"],&[]); assert_eq!(out(&direct),"STEP3_STATE=direct-review-entry\nREVIEW_ROUND_COUNT=1\n"); for name in ["step-1e","step-2a","step-2b","step-2b.5"] { assert!(root.join(".completed").join(name).is_file()); } assert!(!root.join(".step3-round-1.phase").exists()); assert!(!root.join(".step3-applied-finding-keys.tsv").exists());
    let auto=run(Some(&root),"step3-state",&["--auto-continuation-entry"],&[]); assert_eq!(out(&auto),"STEP3_STATE=auto-continuation-entry\nREVIEW_ROUND_COUNT=1\n"); assert!(!root.join(".completed/step-3").exists());
    fs::write(root.join("plan.txt"),"# Plan\n\ndiff_lines: 1\n").expect("plan"); fs::write(root.join(".step3-review-result.env"),"LOOP_STATUS=complete\nTALLY_PLAN_REVIEW_STATUS=ok\nDEGRADED_PANEL=0\n").expect("result");
    let continuation=run(Some(&root),"continuation",&["--approve-requested","false"],&[]); assert!(continuation.status.success()); assert_eq!(out(&continuation),"PLAN_REVIEW_CONTINUE=false\nPLAN_REVIEW_CONTINUE_REASON=small-clean\nREVIEW_ROUND_COUNT=1\nREVIEW_ROUND_CAP=2\nPANEL_TIER=\nACCEPTED_COUNT=0\nNIT_ACCEPTED_COUNT=0\nNON_NIT_ACCEPTED_COUNT=0\nHIGH_ACCEPTED_COUNT=0\nNEW_HIGH_ACCEPTED_COUNT=0\nNEW_NON_NIT_ACCEPTED_COUNT=0\nDUPLICATE_ACCEPTED_COUNT=0\nDEGRADED_PANEL=0\nSTRUCTURAL_OR_LARGE_CHANGE=false\n"); assert_eq!(text(root.join(".step3-applied-finding-keys.tsv")),"");
}

#[cfg(unix)]
#[test]
fn loop_transcript_and_resume_state_are_byte_stable() {
    let sandbox=TempDir::new().expect("sandbox"); let root=design(&sandbox); fs::write(root.join("plan.txt"),"# Plan\n\ndiff_lines: 1\n").expect("plan"); fs::write(root.join("run-params.json"),"{\"approve_requested\":true}\n").expect("params");
    let round=sandbox.path().join("round.sh"); script(&round,"printf '%s\\n' 'LOOP_STATUS=complete' 'TALLY_PLAN_REVIEW_STATUS=ok' 'ACCEPTED_COUNT=1' 'DEGRADED_PANEL=0'\nprintf '%s\\n' '### FINDING_1: Required' '- **Severity**: major' '- **Concern**: Primary path fails.' >\"$DESIGN_TMPDIR/accepted-plan-findings.md\"");
    let first=run(Some(&root),"run",&["--mode","loop","--no-preview"],&[("RUN_STEP3_PLAN_REVIEW_LOOP_SH",&round)]); assert!(first.status.success(),"{}",err(&first)); let expected="LOOP_STATUS=complete\nTALLY_PLAN_REVIEW_STATUS=ok\nACCEPTED_COUNT=1\nDEGRADED_PANEL=0\nNEXT_ACTION=gate-b\nSTEP3_REVIEW_LOOP_STATUS=per-round-approval-required\nROUNDS_COMPLETED=1\nFINAL_ROUND_NUM=1\nACCEPTED_COUNT=1\nDEGRADED_PANEL=0\nPLAN_REVIEW_CONTINUE_REASON=\nREASON=\n"; assert_eq!(out(&first),expected); assert_eq!(text(root.join(".step3-round-1.phase")),"awaiting-apply\n");
    let second=run(Some(&root),"run",&["--mode","loop","--starting-round","1","--no-preview"],&[("RUN_STEP3_PLAN_REVIEW_LOOP_SH",&round)]); assert!(second.status.success()); assert_eq!(out(&second),"NEXT_ACTION=gate-b\nSTEP3_REVIEW_LOOP_STATUS=per-round-approval-required\nROUNDS_COMPLETED=1\nFINAL_ROUND_NUM=1\nACCEPTED_COUNT=0\nDEGRADED_PANEL=0\nPLAN_REVIEW_CONTINUE_REASON=\nREASON=\n"); assert_eq!(text(root.join(".step3-round-1.phase")),"awaiting-apply\n");
}

#[cfg(unix)]
#[test]
fn native_pruned_round_records_transcript_stage_argv_and_artifacts() {
    let sandbox=TempDir::new().expect("sandbox"); let root=design(&sandbox).canonicalize().expect("canonical design"); fs::write(root.join("plan.txt"),"# Plan\n\ndiff_lines: 1\n").expect("plan"); fs::write(root.join("run-params.json"),"{}\n").expect("params"); fs::write(root.join("difficulty-rating.json"),"{\"applied_tier\":\"MODERATE\",\"panel_tier\":\"MODERATE\",\"audit_evaluated\":true,\"audit_upgrade\":null,\"escalations\":[]}\n").expect("difficulty");
    let plugin=sandbox.path().join("plugin"); fs::create_dir_all(plugin.join("scripts")).expect("scripts"); fs::create_dir_all(plugin.join("python")).expect("python"); let launcher=plugin.join("scripts/larch.sh"); script(&launcher,"root=\"${DESIGN_TMPDIR:?}\"\n[[ \"${1:-}\" == timing ]] || printf '%s\\n' \"$*\" >>\"$root/native-stage-argv.log\"\ncase \"${1:-} ${2:-}\" in\n  'plan-review panel-dispatch') printf '%s\\n' 'PANEL_PRUNED_EMPTY=true' ;;\n  'plan-review continuation') printf '%s\\n' 'PLAN_REVIEW_CONTINUE=false' 'PLAN_REVIEW_CONTINUE_REASON=converged-pruned-empty' ;;\nesac"); fs::write(plugin.join("python/cli.py"),"import sys\nif sys.argv[1:3] != ['difficulty', 'resolve-panel']:\n    raise SystemExit(2)\nprint('STATUS=ok')\nprint('PANEL_TIER=MODERATE')\nprint('ESCALATED_ROUND=false')\n").expect("python fixture");
    let native=run(Some(&root),"run",&["--mode","loop","--no-preview"],&[("CLAUDE_PLUGIN_ROOT",&plugin),("DESIGN_TMPDIR",&root)]); assert!(native.status.success(),"{}",err(&native));
    let tally=root.join("voting-tally.md"); let expected=format!("PANEL_PRUNED_EMPTY=true\nTALLY_PLAN_REVIEW_STATUS=ok\nAGGREGATOR_STATUS=skipped-pruned-empty\nACCEPTED_COUNT=0\nDEGRADED_PANEL=0\nVOTING_TALLY_FILE={}\nLOOP_STATUS=zero-findings-degraded-panel\nNEXT_ACTION=step3b\nLOOP_STATUS=zero-findings-degraded-panel\nROUNDS_COMPLETED=1\nREVIEW_ROUND_COUNT=1\nPANEL_PRUNED_EMPTY=true\nTALLY_PLAN_REVIEW_STATUS=ok\nACCEPTED_COUNT=0\nDEGRADED_PANEL=0\n",tally.display()); assert_eq!(out(&native),expected);
    let expected_argv=format!("plan-review panel-dispatch --design-tmpdir {} --round-num 1 --prune-round-num 1 --plan-file {}/plan.txt --feature-file {}/feature-description.txt --codex-present false --cursor-present false --timeout 1860 --tier MODERATE --escalated-round false\nprogress write-design-round-meta --round-dir {}/plan-review/round-1\nplan-review continuation --design-tmpdir {} --approve-requested false\n",root.display(),root.display(),root.display(),root.display(),root.display()); assert_eq!(text(root.join("native-stage-argv.log")),expected_argv);
    assert_eq!(text(root.join("plan-review/round-1/round-summary.env")),"LOOP_STATUS=zero-findings-degraded-panel\nCOLLECT_OK_COUNT=0\nCOLLECT_FAILURE_COUNT=0\nTALLY_PLAN_REVIEW_STATUS=ok\nAGGREGATOR_STATUS=skipped-pruned-empty\nACCEPTED_COUNT=0\nDEGRADED_PANEL=0\n"); assert_eq!(text(root.join("plan-review/round-1/reviewer-status.tsv")),"slot\tstatus\telapsed\n"); assert_eq!(text(root.join(".step3-review-result.env")),"NEXT_ACTION=step3b\nLOOP_STATUS=zero-findings-degraded-panel\nROUNDS_COMPLETED=1\nREVIEW_ROUND_COUNT=1\nPANEL_PRUNED_EMPTY=true\nTALLY_PLAN_REVIEW_STATUS=ok\nACCEPTED_COUNT=0\nDEGRADED_PANEL=0\nDEGRADED_PANEL_WARNING=\nINVALID_SLOT_PANEL_WARNING=\nREASON=\n"); assert!(root.join(".completed/step-3").is_file()); assert!(root.join(".completed/step-3.5").is_file());
}

#[cfg(unix)]
#[test]
fn loop_status_materialization_replaces_dangling_links_and_preserves_override_bytes() {
    let sandbox=TempDir::new().expect("sandbox"); let root=design(&sandbox); fs::write(root.join("plan.txt"),"# Plan\n\ndiff_lines: 1\n").expect("plan"); fs::write(root.join("run-params.json"),"{\"approve_requested\":true}\n").expect("params"); let round_dir=root.join("plan-review/round-1"); fs::create_dir_all(&round_dir).expect("round");
    let output=round_dir.join("cursor-plan-arch-output.txt"); fs::write(root.join("plan-review-slots.ndjson"),format!("{{\"slot\":\"cursor-plan-arch\",\"tool\":\"cursor\",\"output\":\"{}\",\"prompt_file\":\"{}\"}}\n",output.display(),root.join("cursor.prompt").display())).expect("manifest"); symlink("/nonexistent/reviewer-status.tsv",round_dir.join("reviewer-status.tsv")).expect("status link"); fs::write(root.join(".step3-report-panel-failed.recorded"),"").expect("evidence sentinel");
    let terminal=sandbox.path().join("terminal.sh"); script(&terminal,"printf '%s\\n' 'LOOP_STATUS=panel-failed' 'TALLY_PLAN_REVIEW_STATUS=panel-failed' 'AGGREGATOR_STATUS=skipped' 'DEGRADED_PANEL=1'; exit 1"); let failed=run(Some(&root),"run",&["--mode","loop","--no-preview"],&[("RUN_STEP3_PLAN_REVIEW_LOOP_SH",&terminal)]); assert!(failed.status.success(),"{}",err(&failed)); let status=round_dir.join("reviewer-status.tsv"); assert!(!status.is_symlink()); assert_eq!(text(&status),"slot\tstatus\telapsed\nCursor-Arch\tskipped\t\n"); assert_eq!(text(root.join("latest-reviewer-status.tsv")),text(&status)); assert_eq!(text(root.join("reviewer-status-table.txt")),"📊 Reviewers: | Cursor-Arch: ⊘ |\n");

    let sandbox2=TempDir::new().expect("second sandbox"); let root2=design(&sandbox2); fs::write(root2.join("plan.txt"),"# Plan\n\ndiff_lines: 1\n").expect("plan"); fs::write(root2.join("run-params.json"),"{\"approve_requested\":true}\n").expect("params"); let target=root2.join("old-table.txt"); fs::write(&target,"old\n").expect("target"); symlink(&target,root2.join("reviewer-status-table.txt")).expect("stable link"); let authored=sandbox.path().join("authored.sh"); script(&authored,"mkdir -p \"$DESIGN_TMPDIR/plan-review/round-1\"\nprintf 'slot\\tstatus\\telapsed\\nCodex-Arch\\tfailed\\t2m\\n' >\"$DESIGN_TMPDIR/plan-review/round-1/reviewer-status.tsv\"\nprintf '%s\\n' 'LOOP_STATUS=complete' 'TALLY_PLAN_REVIEW_STATUS=ok' 'AGGREGATOR_STATUS=ok' 'ACCEPTED_COUNT=1' 'DEGRADED_PANEL=0'"); let complete=run(Some(&root2),"run",&["--mode","loop","--no-preview"],&[("RUN_STEP3_PLAN_REVIEW_LOOP_SH",&authored)]); assert!(complete.status.success(),"{}",err(&complete)); assert_eq!(text(root2.join("latest-reviewer-status.tsv")),"slot\tstatus\telapsed\nCodex-Arch\tfailed\t2m\n"); assert!(!root2.join("reviewer-status-table.txt").is_symlink()); assert_eq!(text(root2.join("reviewer-status-table.txt")),"📊 Reviewers: | Codex-Arch: ❌ 2m |\n");
}

#[cfg(unix)]
#[test]
fn completed_gate_b_round_timing_is_idempotent() {
    let sandbox=TempDir::new().expect("sandbox"); let root=design(&sandbox); fs::write(root.join("plan.txt"),"# Plan\n\ndiff_lines: 1\n").expect("plan"); fs::write(root.join("run-params.json"),"{}\n").expect("params"); let round_dir=root.join("plan-review/round-1"); fs::create_dir_all(&round_dir).expect("round"); fs::write(round_dir.join("round-start-s"),"1\n").expect("start"); fs::write(root.join(".gate-b-postapply-ready-1"),"").expect("ready"); fs::write(root.join("timing-ledger.tsv"),"v1\tvendor\t3\tdesign\t-\tcodex\tcodex-plan-requirements\t2\t3\t1\tcodex.out\t0\tcomplete\n").expect("ledger");
    let round=sandbox.path().join("round-zero.sh"); script(&round,"printf '%s\\n' 'LOOP_STATUS=complete' 'TALLY_PLAN_REVIEW_STATUS=ok' 'AGGREGATOR_STATUS=ok' 'ACCEPTED_COUNT=0' 'DEGRADED_PANEL=0'"); let continuation=sandbox.path().join("continuation.sh"); script(&continuation,"printf '%s\\n' 'PLAN_REVIEW_CONTINUE=false' 'PLAN_REVIEW_CONTINUE_REASON=small-clean'"); let envs=[("RUN_STEP3_PLAN_REVIEW_LOOP_SH",round.as_path()),("RUN_STEP3_CONTINUATION_SH",continuation.as_path())]; let first=run(Some(&root),"run",&["--mode","loop","--no-preview"],&envs); assert!(first.status.success(),"{}",err(&first)); let second=run(Some(&root),"run",&["--mode","loop","--starting-round","1","--no-preview"],&envs); assert!(second.status.success(),"{}",err(&second)); let ledger=text(root.join("timing-ledger.tsv")); let rows=ledger.lines().map(|line|line.split('\t').collect::<Vec<_>>()).collect::<Vec<_>>(); assert_eq!(rows.iter().filter(|row|row.len()>=13&&row[1]=="vendor"&&row[6]=="gate-b-apply"&&row[10]=="gate-b-apply-round-1.out").count(),1,"{ledger}"); assert_eq!(rows.iter().filter(|row|row.len()>=6&&row[1]=="round"&&row[3]=="design"&&row[5]=="1").count(),1,"{ledger}");
}

#[test]
fn normalize_and_session_entry_contracts_are_exact() {
    let sandbox=TempDir::new().expect("sandbox"); let root=design(&sandbox); fs::create_dir(root.join("bgjob")).expect("bgjob"); fs::write(root.join("bgjob/design-step3-review.result.env"),"BGJOB_RC=0\nNEXT_ACTION=step3b\nSTEP3_REVIEW_LOOP_STATUS=complete\nLOOP_STATUS=complete\nROUNDS_COMPLETED=2\nFINAL_ROUND_NUM=2\nACCEPTED_COUNT=0\nDEGRADED_PANEL_WARNING='one warning'\n").expect("result");
    let read=run(Some(&root),"normalize-status",&["--read-result-env"],&[]); assert!(read.status.success()); assert_eq!(out(&read),"READ_RESULT_ENV_STATUS=ok\nBGJOB_RC=0\nNEXT_ACTION=step3b\nSTEP3_REVIEW_LOOP_STATUS=complete\nLOOP_STATUS=complete\nROUNDS_COMPLETED=2\nFINAL_ROUND_NUM=2\nACCEPTED_COUNT=0\nDEGRADED_PANEL_WARNING=one warning\nINVALID_SLOT_PANEL_WARNING=\nREASON=\n");
    fs::write(root.join("plan.txt"),"# Plan\n").expect("plan"); let source=root.join("source-env.sh"); fs::write(&source,format!("export DESIGN_TMPDIR='{}'\nexport CLAUDE_PLUGIN_ROOT='{}'\nexport ISSUE_NUMBER='8449'\n",root.display(),repo().display())).expect("session");
    let source_arg=source.to_str().expect("path"); let entry=run(None,"step3-entry-preview",&["--session-env-path",source_arg,"--claude-pid","8449"],&[]); assert!(entry.status.success(),"{}",err(&entry)); assert_eq!(out(&entry),"## Plan Candidate for Review\n\n# Plan\n\n"); let again=run(None,"step3-entry-preview",&["--session-env-path",source_arg,"--claude-pid","8449"],&[]); assert!(again.status.success()); assert!(out(&again).is_empty());

    let sandbox2=TempDir::new().expect("second sandbox"); let cwd=sandbox2.path(); fs::write(cwd.join(".pause-requested"),"").expect("pause sentinel"); let missing=Command::new(env!("CARGO_BIN_EXE_larch")).args(["plan-review","step3-entry-preview"]).current_dir(cwd).env("CLAUDE_PLUGIN_ROOT",repo()).env("LARCH_BINARY",env!("CARGO_BIN_EXE_larch")).env_remove("DESIGN_TMPDIR").env_remove("ISSUE_NUMBER").output().expect("missing preview"); assert!(missing.status.success()); assert_eq!(out(&missing),"**⚠ 3: DESIGN_TMPDIR missing or invalid; cannot present plan candidate for review**\n\n"); assert!(err(&missing).is_empty());

    let recovery_root=design(&sandbox2); let stdout_file=recovery_root.join("loop.stdout"); fs::write(&stdout_file,"WARN=stdout warning\nLOOP_STATUS=complete\nTALLY_PLAN_REVIEW_STATUS=ok\nROUNDS_COMPLETED=1\nFINAL_ROUND_NUM=1\nACCEPTED_COUNT=0\n").expect("stdout recovery"); let recovered=run(Some(&recovery_root),"normalize-status",&["--stdout-file",stdout_file.to_str().expect("stdout path"),"--loop-rc","0"],&[]); assert!(recovered.status.success(),"{}",err(&recovered)); assert_eq!(out(&recovered),"WARN=stdout warning\nNEXT_ACTION=step3b\nSTEP3_REVIEW_LOOP_STATUS=complete\nLOOP_STATUS=complete\nFINAL_ROUND_NUM=1\nTALLY_PLAN_REVIEW_STATUS=ok\nROUNDS_COMPLETED=1\nACCEPTED_COUNT=0\n"); assert_eq!(err(&recovered),"**⚠ Step 3: could not read step3 review result env; recovering from plan-review stdout when possible**\n"); assert!(!out(&recovered).contains("BGJOB_RC="));
}

#[cfg(unix)]
#[test]
fn result_envelopes_and_completion_markers_fail_closed() {
    let sandbox=TempDir::new().expect("sandbox"); let root=design(&sandbox);
    let missing=run(Some(&root),"run",&["--read-result-env"],&[]); assert_eq!(missing.status.code(),Some(1)); assert!(err(&missing).contains("result env is not a regular file"));
    fs::create_dir(root.join(".step3-review-result.env")).expect("invalid result env"); let directory=run(Some(&root),"run",&["--read-result-env"],&[]); assert_eq!(directory.status.code(),Some(1));
    fs::remove_dir(root.join(".step3-review-result.env")).expect("remove result dir"); symlink(root.join("missing-result"),root.join(".step3-review-result.env")).expect("result symlink"); let link=run(Some(&root),"run",&["--read-result-env"],&[]); assert_eq!(link.status.code(),Some(1)); fs::remove_file(root.join(".step3-review-result.env")).expect("remove link");
    fs::write(root.join(".step3-review-result.env"),b"NEXT_ACTION=first\r\nLOOP_STATUS=bad\r\nNEXT_ACTION=second\nLOOP_STATUS=complete\nNEXT_ACTION=third\nSECRET=drop\n").expect("strict result"); let strict=run(Some(&root),"run",&["--read-result-env"],&[]); assert!(strict.status.success(),"{}",err(&strict)); assert_eq!(out(&strict),"NEXT_ACTION=second\nNEXT_ACTION=third\nLOOP_STATUS=complete\n"); fs::remove_file(root.join(".step3-review-result.env")).expect("remove strict result");

    fs::write(root.join("plan.txt"),"# Plan\n\ndiff_lines: 1\n").expect("plan"); fs::create_dir_all(root.join(".completed/step-3")).expect("invalid marker"); let terminal=sandbox.path().join("terminal.sh"); script(&terminal,"printf '%s\\n' 'LOOP_STATUS=panel-failed' 'TALLY_PLAN_REVIEW_STATUS=panel-failed' 'AGGREGATOR_STATUS=skipped' 'DEGRADED_PANEL=1'"); let marker=run(Some(&root),"run",&["--mode","loop","--no-preview"],&[("RUN_STEP3_PLAN_REVIEW_LOOP_SH",&terminal)]); assert_eq!(marker.status.code(),Some(1)); assert!(err(&marker).contains("refusing invalid completion marker"));

    let sandbox3=TempDir::new().expect("third sandbox"); let root3=design(&sandbox3); fs::write(root3.join("plan.txt"),"# Plan\n\ndiff_lines: 1\n").expect("plan"); let outside=sandbox3.path().join("outside"); fs::create_dir(&outside).expect("outside"); symlink(&outside,root3.join(".completed")).expect("completion parent link"); let escaped=run(Some(&root3),"run",&["--mode","loop","--no-preview"],&[("RUN_STEP3_PLAN_REVIEW_LOOP_SH",&terminal)]); assert_eq!(escaped.status.code(),Some(1)); assert!(err(&escaped).contains("refusing invalid completion directory")); assert!(!outside.join("step-3").exists());

    let sandbox2=TempDir::new().expect("second sandbox"); let root2=design(&sandbox2); fs::write(root2.join("plan.txt"),"# Plan\n\ndiff_lines: 1\n").expect("plan"); fs::write(root2.join("run-params.json"),"{\"approve_requested\":true}\n").expect("params"); fs::create_dir(root2.join(".step3-review-result.env")).expect("invalid envelope"); let round=sandbox2.path().join("round.sh"); script(&round,"printf '%s\\n' 'LOOP_STATUS=complete' 'TALLY_PLAN_REVIEW_STATUS=ok' 'AGGREGATOR_STATUS=ok' 'ACCEPTED_COUNT=1' 'DEGRADED_PANEL=0'\nprintf '%s\\n' '### FINDING_1: Required' '- **Severity**: major' '- **Concern**: Primary path fails.' >\"$DESIGN_TMPDIR/accepted-plan-findings.md\""); let envelope=run(Some(&root2),"run",&["--mode","loop","--no-preview"],&[("RUN_STEP3_PLAN_REVIEW_LOOP_SH",&round)]); assert_eq!(envelope.status.code(),Some(1)); assert!(err(&envelope).contains("plan-review run:"));
}

#[test]
fn continuation_seeds_canonical_difficulty_sources() {
    let accepted="### FINDING_1: First\n- **Severity**: major\n- **Concern**: First required path fails.\n\n### FINDING_2: Second\n- **Severity**: major\n- **Concern**: Second required path fails.\n";
    let sandbox=TempDir::new().expect("sandbox"); let raw_root=design(&sandbox); fs::write(raw_root.join("review-round-count.txt"),"1\n").expect("count"); fs::write(raw_root.join(".step3-review-result.env"),"LOOP_STATUS=complete\nTALLY_PLAN_REVIEW_STATUS=ok\nDEGRADED_PANEL=0\n").expect("result"); fs::write(raw_root.join("accepted-plan-findings.md"),accepted).expect("findings"); fs::write(raw_root.join("plan.txt"),"# Plan\n\ndiff_lines: 1\n").expect("plan"); fs::write(raw_root.join("design-difficulty-rating.raw.json"),"{\"predicted_tier\":\"HARD\",\"confidence\":\"high\",\"rationale\":\"raw design rating\"}\n").expect("raw rating"); let raw=run(Some(&raw_root),"continuation",&["--approve-requested","false"],&[]); assert!(raw.status.success(),"{}",err(&raw)); assert!(out(&raw).contains("PANEL_TIER=HARD\n")); let raw_record:serde_json::Value=serde_json::from_str(&text(raw_root.join("difficulty-rating.json"))).expect("raw record"); assert_eq!(raw_record["design_tier"],"HARD"); assert_eq!(raw_record["rationale"],"raw design rating");

    let sandbox2=TempDir::new().expect("second sandbox"); let plan_root=design(&sandbox2); fs::write(plan_root.join("review-round-count.txt"),"1\n").expect("count"); fs::write(plan_root.join(".step3-review-result.env"),"LOOP_STATUS=complete\nTALLY_PLAN_REVIEW_STATUS=ok\nDEGRADED_PANEL=0\n").expect("result"); fs::write(plan_root.join("accepted-plan-findings.md"),accepted).expect("findings"); fs::write(plan_root.join("plan.txt"),"# Plan\n\ndifficulty: MODERATE\ndiff_lines: 1\n").expect("plan"); let planned=run(Some(&plan_root),"continuation",&["--approve-requested","false"],&[]); assert!(planned.status.success(),"{}",err(&planned)); let plan_record:serde_json::Value=serde_json::from_str(&text(plan_root.join("difficulty-rating.json"))).expect("plan record"); assert_eq!(plan_record["design_tier"],"MODERATE"); assert_eq!(plan_record["rationale"],"design plan metadata"); assert!(!plan_root.join(".plan-review-difficulty-seed.json").exists());

    let sandbox3=TempDir::new().expect("third sandbox"); let clean_root=design(&sandbox3); fs::write(clean_root.join("review-round-count.txt"),"1\n").expect("count"); fs::write(clean_root.join(".step3-review-result.env"),"LOOP_STATUS=complete\nTALLY_PLAN_REVIEW_STATUS=ok\nDEGRADED_PANEL=0\n").expect("result"); fs::write(clean_root.join("plan.txt"),"# Plan\n\ndifficulty: TRIVIAL\ndiff_lines: 1\n").expect("plan"); let clean=run(Some(&clean_root),"continuation",&["--approve-requested","false"],&[]); assert!(clean.status.success(),"{}",err(&clean)); assert!(out(&clean).contains("PLAN_REVIEW_CONTINUE_REASON=small-clean\n")); let clean_record:serde_json::Value=serde_json::from_str(&text(clean_root.join("difficulty-rating.json"))).expect("clean record"); assert_eq!(clean_record["design_tier"],"TRIVIAL"); assert!(clean_record["audit_evaluated"].is_boolean());
}

#[cfg(unix)]
#[test]
fn continuation_fails_when_hard_escalation_cannot_be_persisted() {
    let sandbox=TempDir::new().expect("sandbox"); let root=design(&sandbox); fs::write(root.join("review-round-count.txt"),"1\n").expect("count"); fs::write(root.join(".step3-review-result.env"),"LOOP_STATUS=complete\nTALLY_PLAN_REVIEW_STATUS=ok\nDEGRADED_PANEL=0\n").expect("result"); fs::write(root.join("accepted-plan-findings.md"),"### FINDING_1: First\n- **Severity**: major\n- **Concern**: First required path fails.\n\n### FINDING_2: Second\n- **Severity**: major\n- **Concern**: Second required path fails.\n").expect("findings"); fs::write(root.join("plan.txt"),"# Plan\n\ndiff_lines: 1\n").expect("plan"); let record="{\"schema_version\":3,\"predicted_tier\":\"MODERATE\",\"applied_tier\":\"MODERATE\",\"panel_tier\":\"MODERATE\",\"round_cap\":2,\"codex_model_role\":\"review\",\"audit_evaluated\":true,\"audit_upgrade\":null,\"override_source\":\"none\",\"escalations\":[]}\n"; fs::write(root.join("difficulty-rating.json"),record).expect("difficulty"); let mut locked=fs::metadata(&root).expect("metadata").permissions(); locked.set_mode(0o555); fs::set_permissions(&root,locked).expect("lock root"); let failed=run(Some(&root),"continuation",&["--approve-requested","false"],&[]); let mut restored=fs::metadata(&root).expect("locked metadata").permissions(); restored.set_mode(0o700); fs::set_permissions(&root,restored).expect("restore root"); assert_eq!(failed.status.code(),Some(1)); assert!(out(&failed).is_empty()); assert!(!err(&failed).is_empty()); assert_eq!(text(root.join("difficulty-rating.json")),record);
}
}
