#!/usr/bin/env bash
# /design session env — generated by write-design-current-env.sh. Do not edit.
export DESIGN_TMPDIR=<TMPDIR>
export SESSION_TMPDIR=<TMPDIR>
export SESSION_ID=EE0C588A-F596-48E0-A1A1-8F71C7BA3517
export ISSUE_NUMBER=3209
export CODEX_PRESENT=false
export CURSOR_PRESENT=true
export CODEX_AVAILABLE=false
export CURSOR_AVAILABLE=true
export CLAUDE_PLUGIN_ROOT=<OPERATOR_REPO_PATH>/plugins/cache/larch-local/larch/47.0.3
