#!/usr/bin/env bash
# /design session env — generated by write-design-current-env.sh. Do not edit.
export DESIGN_TMPDIR=<TMPDIR>
export SESSION_TMPDIR=<TMPDIR>
export SESSION_ID=993D3FDA-9ADD-4654-961F-78BA03B488EE
export ISSUE_NUMBER=2991
export CODEX_PRESENT=true
export CURSOR_PRESENT=false
export CODEX_AVAILABLE=true
export CURSOR_AVAILABLE=false
export CLAUDE_PLUGIN_ROOT=<OPERATOR_REPO_PATH>/plugins/cache/larch-local/larch/42.5.39
