#!/usr/bin/env bash
# /design session env — generated by session_env.py. Do not edit.
export DESIGN_TMPDIR=<TMPDIR>
export SESSION_TMPDIR=<TMPDIR>
export SESSION_ID=EA44CFE0-C433-4C98-A669-BF61BE0A036A
export REPO=character-ai/larch
export ISSUE_NUMBER=5876
export CODEX_BINARY_FOUND=true
export CURSOR_BINARY_FOUND=true
export LARCH_EXTERNAL_HEALTH_CHECK_TIMEOUT=60
export CLAUDE_PLUGIN_ROOT=<OPERATOR_REPO_PATH>/plugins/cache/larch-local/larch/52.1.15
