//! Rust owner for composing review finding artifacts into the published JSONL.
#[rustfmt::skip]
mod implementation {
#![allow(clippy::possible_missing_else)]
// The frozen artifact parser stays compact enough for #8445's explicit line budget.
use std::{ collections::BTreeMap, ffi::OsString, fs, io::Read as _, path::{Path, PathBuf}, process::ExitCode, };
use larch_adapters::{PathIntent, TemporaryRoot, open_confined_read};
use larch_core::{ ensure_ascii_json, redact, review::is_security_block_text, split_text_lines, };
use regex::Regex;
use serde_json::{Value, json};
use crate::{ argparse_compat::{absolute_path, parse_required_with_help}, launcher_support::write_confined_checked, runtime_entrypoint::run_verified_larch, };
const USAGE: &str = "usage: compose-findings [-h] [--design-artifacts-dir DESIGN_ARTIFACTS_DIR]\n                        [--implement-tmpdir IMPLEMENT_TMPDIR] --issue ISSUE\n                        --output OUTPUT [--archive-dir ARCHIVE_DIR]\n                        [--archive-threshold ARCHIVE_THRESHOLD]";
const HELP: &str = "usage: compose-findings [-h] [--design-artifacts-dir DESIGN_ARTIFACTS_DIR]\n                        [--implement-tmpdir IMPLEMENT_TMPDIR] --issue ISSUE\n                        --output OUTPUT [--archive-dir ARCHIVE_DIR]\n                        [--archive-threshold ARCHIVE_THRESHOLD]\n\noptions:\n  -h, --help            show this help message and exit\n  --design-artifacts-dir DESIGN_ARTIFACTS_DIR\n  --implement-tmpdir IMPLEMENT_TMPDIR\n  --issue ISSUE\n  --output OUTPUT\n  --archive-dir ARCHIVE_DIR\n  --archive-threshold ARCHIVE_THRESHOLD";
const ONE_BY_ONE_SKIP_MARKER: &str = "rejected by user during one-by-one review";
const FOCUS_AREAS: &[&str] = &[ "code-quality", "risk-integration", "correctness", "architecture", "security", ];
#[derive(Default)]
struct ComposeArguments { design_dir: Option<PathBuf>, implement_dir: Option<PathBuf>, issue: String, output: Option<PathBuf>, }
struct ArtifactRoot(TemporaryRoot);
#[derive(Clone, Copy)]
enum ArtifactKind { PlanAccepted, PlanRejected, CodeAccepted, CodeRejected, CodeOos, }
impl ArtifactKind { const fn phase(self) -> &'static str { match self { Self::PlanAccepted | Self::PlanRejected => "plan-review", Self::CodeAccepted | Self::CodeRejected | Self::CodeOos => "code-review", } } const fn outcome(self) -> &'static str { match self { Self::PlanAccepted | Self::CodeAccepted => "accepted",
            Self::PlanRejected | Self::CodeRejected => "rejected", Self::CodeOos => "out_of_scope", } } }
impl ArtifactRoot { fn resolve(path: Option<&Path>, label: &str) -> Result<Option<Self>, String> { let Some(path) = path else { return Ok(None) }; let metadata = match fs::symlink_metadata(path) { Ok(value) => value,
            Err(error) if matches!(error.kind(), std::io::ErrorKind::NotFound | std::io::ErrorKind::NotADirectory) => return Ok(None), Err(error) => return Err(format!("cannot inspect {label}: {error}")), }; if metadata.file_type().is_symlink() || !metadata.is_dir() {
            return Err(format!("{label} must name a non-symlink directory")); } let absolute = absolute_path(path).map_err(|error| format!("cannot resolve {label}: {error}"))?; TemporaryRoot::resolve(Some(&absolute)).map(Self).map(Some).map_err(|error| format!("cannot resolve {label}: {error}")) }
    fn path(&self) -> &Path { self.0.path() } fn read(&self, path: &Path) -> Result<String, String> { match fs::symlink_metadata(path) { Err(error) if matches!(error.kind(), std::io::ErrorKind::NotFound | std::io::ErrorKind::NotADirectory) => return Ok(String::new()),
            Err(error) => return Err(format!("cannot inspect artifact {}: {error}", path.display())), Ok(_) => {} } let confined = self.0.confine(path, PathIntent::Read).map_err(|error| format!("cannot read artifact {}: {error}", path.display()))?;
        let mut file = open_confined_read(&confined).map_err(|error| format!("cannot read artifact {}: {error}", path.display()))?; let mut bytes = Vec::new(); file.read_to_end(&mut bytes).map_err(|error| format!("cannot read artifact {}: {error}", path.display()))?; Ok(String::from_utf8_lossy(&bytes).into_owned()) } }
fn child_directories(parent: &Path, prefix: &str) -> Result<Vec<PathBuf>, String> { let entries = match fs::read_dir(parent) { Ok(value) => value, Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(Vec::new()),
        Err(error) => return Err(format!("cannot list artifact directory {}: {error}", parent.display())), }; let mut paths = Vec::new(); for entry in entries { let entry = entry.map_err(|error| format!("cannot list artifact directory {}: {error}", parent.display()))?;
        if !entry.file_name().to_string_lossy().starts_with(prefix) { continue; } let metadata = fs::symlink_metadata(entry.path()).map_err(|error| format!("cannot inspect artifact directory {}: {error}", entry.path().display()))?;
        if metadata.file_type().is_symlink() { return Err(format!("artifact directory must not be a symlink: {}", entry.path().display())); } if !metadata.is_dir() { continue; } paths.push(entry.path()); } paths.sort(); Ok(paths) }
fn filter_gate_b(root: &Path, accepted: &Path, rejected: &Path) -> Result<String, String> { let arguments = [ OsString::from("plan-review"), OsString::from("filter-gate-b-skipped"), OsString::from("--design-tmpdir"), root.as_os_str().to_owned(), OsString::from("--accepted"), accepted.as_os_str().to_owned(),
        OsString::from("--rejected"), rejected.as_os_str().to_owned(), ]; let output = run_verified_larch(&arguments)?; if !output.status().success() { let stderr = String::from_utf8_lossy(output.stderr()).trim().to_owned(); return Err(if stderr.is_empty() { "filter-gate-b-skipped failed".to_owned() } else { stderr });
    } Ok(String::from_utf8_lossy(output.stdout()).into_owned()) }
/// Compose public review finding records from staged review artifacts.
#[allow(clippy::too_many_lines)] // Artifact precedence and final JSONL emission are one compatibility transaction.
pub fn compose_findings(arguments: &[OsString]) -> ExitCode { let args = match parse_arguments(arguments) { Ok(args) => args, Err(code) => return code, }; if !args.issue.bytes().all(|byte| byte.is_ascii_digit()) { return fail(&format!( "invalid value for --issue: '{}' (expected non-negative integer)", args.issue )); }
    let Some(output) = args.output else { return fail("the following arguments are required: --output"); }; let design = match ArtifactRoot::resolve(args.design_dir.as_deref(), "design-artifacts-dir") { Ok(value) => value, Err(error) => return fail(&error), };
    let implement = match ArtifactRoot::resolve(args.implement_dir.as_deref(), "implement-tmpdir") { Ok(value) => value, Err(error) => return fail(&error), }; let design_map = match build_design_reviewer_map(design.as_ref()) { Ok(value) => value, Err(error) => return fail(&error), }; let mut records = Vec::new();
    if let Some(design) = design.as_ref() { let all = design.path().join("accepted-plan-findings-all.md"); let fallback = design.path().join("accepted-plan-findings.md"); let all_text = match design.read(&all) { Ok(value) => value, Err(error) => return fail(&error) };
        let (accepted, mut accepted_text) = if all_text.is_empty() { (fallback.clone(), match design.read(&fallback) { Ok(value) => value, Err(error) => return fail(&error) }) } else { (all, all_text) }; let rejected = design.path().join("rejected-findings.md");
        let rejected_text = match design.read(&rejected) { Ok(value) => value, Err(error) => return fail(&error) }; if !accepted_text.is_empty() && rejected_text.contains(ONE_BY_ONE_SKIP_MARKER) {
            accepted_text = match filter_gate_b(design.path(), &accepted, &rejected) { Ok(value) => value, Err(error) => return fail(&error) }; } parse_artifact( &accepted_text, ArtifactKind::PlanAccepted, "", &args.issue, &design_map, &mut records, ); parse_artifact( &rejected_text, ArtifactKind::PlanRejected, "",
            &args.issue, &design_map, &mut records, ); } if let Some(implement) = implement.as_ref() { let round_dirs = match child_directories(implement.path(), "round-") { Ok(value) => value, Err(error) => return fail(&error) }; let mut rejected_found = false; for round in round_dirs { let round_num = round
                .file_name() .and_then(|value| value.to_str()) .and_then(|value| value.strip_prefix("round-")) .unwrap_or(""); let accepted_text = match implement.read(&round.join("accepted-findings.md")) { Ok(value) => value, Err(error) => return fail(&error) }; parse_artifact( &accepted_text,
                ArtifactKind::CodeAccepted, round_num, &args.issue, &design_map, &mut records, ); let oos_text = match implement.read(&round.join("oos.md")) { Ok(value) => value, Err(error) => return fail(&error) }; parse_artifact( &oos_text, ArtifactKind::CodeOos, round_num, &args.issue, &design_map, &mut records, );
            let full = round.join("rejected-findings-full.md"); let rejected = round.join("rejected-findings.md"); let full_text = match implement.read(&full) { Ok(value) => value, Err(error) => return fail(&error) };
            let rejected_text = match implement.read(&rejected) { Ok(value) => value, Err(error) => return fail(&error) }; if !full_text.is_empty() { rejected_found = true; parse_artifact( &full_text, ArtifactKind::CodeRejected, round_num, &args.issue, &design_map, &mut records, ); } else if !rejected_text.is_empty() {
                rejected_found = true; parse_artifact( &rejected_text, ArtifactKind::CodeRejected, round_num, &args.issue, &design_map, &mut records, ); } } if !rejected_found { let full = implement.path().join("rejected-findings-full.md");
            let full_text = match implement.read(&full) { Ok(value) => value, Err(error) => return fail(&error) }; let rejected = implement.path().join("rejected-findings.md");
            let rejected_text = if full_text.is_empty() { match implement.read(&rejected) { Ok(value) => value, Err(error) => return fail(&error) } } else { full_text }; parse_artifact( &rejected_text, ArtifactKind::CodeRejected, "", &args.issue, &design_map, &mut records, ); } } let mut rendered = String::new();
    for record in records { let Ok(line) = serialize_ascii_json(&record) else { return fail("could not serialize composed finding record"); }; rendered.push_str(&line); rendered.push('\n'); } if let Err(error) = write_confined_checked(&output, &rendered) { return fail(&format!("cannot write output: {error}")); }
    emit("COMPOSED", "true"); emit("OUTPUT", output.to_string_lossy().as_ref()); emit("FINDINGS_TOTAL", &records_len(&rendered).to_string()); emit("MODE", "jsonl"); ExitCode::SUCCESS }
fn records_len(rendered: &str) -> usize { split_text_lines(rendered) .into_iter() .filter(|line| !line.trim().is_empty()) .count() }
/// Match Python's `json.dumps(..., ensure_ascii=True)` wire representation.
///
/// `serde_json` emits non-ASCII scalars directly. The retired composer used
/// Python's default ASCII-only JSON encoder, so use the shared translator for
/// its escaped, UTF-16-surrogate-pair representation.
fn serialize_ascii_json(record: &Value) -> Result<String, serde_json::Error> { let rendered = serde_json::to_string(record)?; Ok(ensure_ascii_json(&rendered)) }
fn parse_arguments(arguments: &[OsString]) -> Result<ComposeArguments, ExitCode> { let parsed = parse_required_with_help(arguments, "compose-findings", USAGE, HELP, &["--design-artifacts-dir", "--implement-tmpdir", "--issue", "--output", "--archive-dir", "--archive-threshold"], &[], &["--issue", "--output"])?;
    let value = |name: &str| parsed.value(name).map(|value| value.to_string_lossy().into_owned()).unwrap_or_default(); let design = value("--design-artifacts-dir"); let implement = value("--implement-tmpdir"); Ok(ComposeArguments { design_dir: (!design.is_empty()).then(|| PathBuf::from(design)),
        implement_dir: (!implement.is_empty()).then(|| PathBuf::from(implement)), issue: value("--issue"), output: Some(PathBuf::from(value("--output"))), }) }
fn fail(message: &str) -> ExitCode { emit("FAILED", "true"); emit("ERROR", message); ExitCode::from(2) }
fn emit(key: &str, value: &str) { println!("{key}={value}"); }
#[allow(clippy::too_many_lines)] // The retired parser's ordered heading cases stay contiguous for parity review.
fn parse_artifact( text: &str, kind: ArtifactKind, round_num: &str, issue: &str, design_map: &BTreeMap<String, String>, records: &mut Vec<Value>, ) { if text.trim().is_empty() { return; } let canonical = Regex::new(r"^###\s+(FINDING_(?:[0-9]+|[A-Za-z_][0-9A-Za-z_]*)):\s*(.*)$") .expect("accepted heading regex");
    let plan_rejected = Regex::new(r"^###\s+\[Plan\s+Review\]\s+(.+)$").expect("plan rejected regex"); let code_rejected = Regex::new(r"^###\s+\[(rejected|Code\s+Review)\]\s+(.+)$").expect("code rejected regex"); let oos = Regex::new(r"^###\s+OOS_[0-9A-Za-z_]+:\s*(.*)$").expect("oos regex");
    let legacy_oos = Regex::new(r"^###\s+FINDING_[0-9A-Za-z_]+:\s*\[OUT_OF_SCOPE\]\s*(.*)$") .expect("legacy oos regex"); let mut pending_id = String::new(); let mut pending_title = String::new(); let mut pending_reviewer = String::new(); let mut pending_lines = Vec::new(); let mut counter = 0_usize;
    let flush = |pending_id: &mut String, pending_title: &mut String, pending_reviewer: &mut String, pending_lines: &mut Vec<String>, records: &mut Vec<Value>| { if pending_id.is_empty() { return; } let mut body = pending_lines.join("\n"); if !pending_title.is_empty() { body = format!("## {pending_title}\n\n{body}"); }
        let reviewer = if pending_reviewer.is_empty() { extract_reviewer(&body).unwrap_or_else(|| "panel".to_owned()) } else { pending_reviewer.clone() }; if !(matches!(kind, ArtifactKind::CodeOos) && is_security_block_text(&body)) { records.push(record( pending_id, kind, round_num, issue, design_map, &reviewer, &body,
            )); } pending_id.clear(); pending_title.clear(); pending_reviewer.clear(); pending_lines.clear(); }; for line in split_text_lines(text) { match kind { ArtifactKind::PlanAccepted | ArtifactKind::CodeAccepted => { if let Some(captures) = canonical.captures(line) { flush( &mut pending_id, &mut pending_title,
                        &mut pending_reviewer, &mut pending_lines, records, ); captures .get(1) .map_or("", |value| value.as_str()) .clone_into(&mut pending_id); captures .get(2) .map_or("", |value| value.as_str()) .clone_into(&mut pending_title); continue; } } ArtifactKind::PlanRejected => {
                if let Some(captures) = plan_rejected.captures(line) { flush( &mut pending_id, &mut pending_title, &mut pending_reviewer, &mut pending_lines, records, ); counter += 1; pending_id = synthetic_id("REJ_P", counter, round_num); captures .get(1) .map_or("", |value| value.as_str())
                        .clone_into(&mut pending_reviewer); continue; } } ArtifactKind::CodeRejected => { if let Some(captures) = code_rejected.captures(line) { flush( &mut pending_id, &mut pending_title, &mut pending_reviewer, &mut pending_lines, records, ); counter += 1;
                    pending_id = synthetic_id("REJ_C", counter, round_num); if captures.get(1).map_or("", |value| value.as_str()) == "Code Review" { captures .get(2) .map_or("", |value| value.as_str()) .clone_into(&mut pending_reviewer); } continue; } if !pending_id.is_empty() && line.starts_with("### ") {
                    pending_lines.push(line.to_owned()); continue; } } ArtifactKind::CodeOos => { if let Some(captures) = oos.captures(line).or_else(|| legacy_oos.captures(line)) { flush( &mut pending_id, &mut pending_title, &mut pending_reviewer, &mut pending_lines, records, ); counter += 1;
                    pending_id = synthetic_id("OOS_C", counter, round_num); captures .get(1) .map_or("", |value| value.as_str()) .clone_into(&mut pending_title); continue; } if !pending_id.is_empty() && line.starts_with("### ") { pending_lines.push(line.to_owned()); continue; } } } if line.starts_with("### ") { flush(
                &mut pending_id, &mut pending_title, &mut pending_reviewer, &mut pending_lines, records, ); continue; } if !pending_id.is_empty() { pending_lines.push(line.to_owned()); } } flush( &mut pending_id, &mut pending_title, &mut pending_reviewer, &mut pending_lines, records, ); }
fn record( item_id: &str, kind: ArtifactKind, round_num: &str, issue: &str, design_map: &BTreeMap<String, String>, reviewer: &str, body: &str, ) -> Value { let reviewer = if matches!( kind, ArtifactKind::PlanAccepted | ArtifactKind::PlanRejected ) { normalize_design_reviewer(reviewer, design_map) } else {
        reviewer.to_owned() }; let reviewer = redact(&reviewer).text().to_owned(); let body = redact(body).text().to_owned(); let strict = matches!(kind, ArtifactKind::CodeOos) || (matches!(kind, ArtifactKind::PlanAccepted) && kind.outcome() == "accepted"); let reviewer_slots = reviewer .split(',') .map(str::trim)
        .filter(|value| !value.is_empty()) .map(str::to_owned) .collect::<Vec<_>>(); let reviewer_slots = if reviewer_slots.is_empty() { vec!["panel".to_owned()] } else { reviewer_slots }; json!({ "id": item_id, "issue_number": issue, "phase": kind.phase(), "outcome": kind.outcome(), "schema_version": "2",
        "reviewer_slots": reviewer_slots, "round_num": round_num, "category": extract_category(&body, strict), "body_severity": extract_field(&body, "Severity", false), "focus_area": extract_field(&body, "Focus area", true), "prose_body": truncate_chars(&body, 2000), }) }
fn synthetic_id(prefix: &str, counter: usize, round: &str) -> String { if round.is_empty() { format!("{prefix}{counter}") } else { format!("{prefix}R{round}_{counter}") } }
fn extract_field(body: &str, field: &str, insensitive: bool) -> String { let pattern = if insensitive { format!(r"(?i)^[\s-]*\*\*{}\*\*:\s*(.*?)\s*$", regex::escape(field)) } else { format!(r"^[\s-]*\*\*{}\*\*:\s*(.*?)\s*$", regex::escape(field)) }; let regex = Regex::new(&pattern).expect("field regex");
    split_text_lines(body) .into_iter() .find_map(|line| { regex .captures(line) .and_then(|captures| captures.get(1).map(|value| value.as_str().to_owned())) }) .unwrap_or_default() }
fn extract_reviewer(body: &str) -> Option<String> { let patterns = [ r"^[\s-]*\*\*Reviewer\(s\)\*\*:\s*(.+)$", r"^[\s-]*\*\*Reviewers?\*\*:\s*(.+)$", r"^[\s-]*Reviewer\(s\):\s*(.+)$", r"^[\s-]*Reviewers?:\s*(.+)$", ]; for pattern in patterns { let regex = Regex::new(pattern).expect("reviewer regex");
        if let Some(value) = split_text_lines(body).into_iter().find_map(|line| { regex.captures(line).and_then(|captures| { captures .get(1) .map(|value| value.as_str().replace('*', "").trim().to_owned()) }) }) { return Some(value); } } None }
fn extract_category(body: &str, strict: bool) -> String { for line in split_text_lines(body) { if let Some(rest) = line .strip_prefix("### FINDING_") .and_then(|value| value.split_once(':').map(|(_, rest)| rest.trim())) { let parts = rest.split(':').map(str::trim).collect::<Vec<_>>();
            let candidate = if parts.len() >= 3 || parts .first() .is_some_and(|value| FOCUS_AREAS.contains(value)) { parts.first().copied().unwrap_or("") } else { "" }; if !candidate.is_empty() && (!strict || FOCUS_AREAS.contains(&candidate)) { return candidate.to_owned(); } }
        if let Some(mut candidate) = line.strip_prefix("## ").map(str::trim) { if let Some(bold) = candidate .strip_prefix("**") .and_then(|value| value.split_once("**").map(|(value, _)| value)) { candidate = bold; } else { candidate = candidate .split_once(':') .map_or(candidate, |(value, _)| value) .trim(); }
            if !candidate.is_empty() && (!strict || FOCUS_AREAS.contains(&candidate)) { return candidate.to_owned(); } } if let Some(rest) = line.strip_prefix("## ") { let mut candidate = rest.trim(); if candidate.starts_with("**") { candidate = candidate .strip_prefix("**") .and_then(|value| value.split("**").next())
                    .unwrap_or(candidate); } else { candidate = candidate.split(':').next().unwrap_or(candidate).trim(); } if !candidate.is_empty() && (!strict || FOCUS_AREAS.contains(&candidate)) { return candidate.to_owned(); } } } String::new() }
fn truncate_chars(value: &str, max: usize) -> String { value.chars().take(max).collect() }
fn build_design_reviewer_map(design: Option<&ArtifactRoot>) -> Result<BTreeMap<String, String>, String> { let mut mapping = BTreeMap::new(); let Some(design) = design else { return Ok(mapping); }; let rounds = design.path().join("plan-review"); let mut manifests = Vec::new();
    let mut round_paths = child_directories(&rounds, "round-")? .into_iter() .filter(|path| Regex::new(r"^round-[0-9]+$").expect("round regex").is_match(path.file_name().and_then(|value| value.to_str()).unwrap_or(""))) .map(|path| path.join("plan-review-slots.ndjson")) .collect::<Vec<_>>();
    round_paths.sort_by_key(|path| numeric_round(path.parent().and_then(Path::file_name).and_then(|value| value.to_str()).unwrap_or(""))); manifests.extend(round_paths); manifests.push(design.path().join("plan-review-slots.ndjson")); for manifest in manifests { for line in split_text_lines(&design.read(&manifest)?) {
            let Ok(Value::Object(row)) = serde_json::from_str::<Value>(line) else { continue; }; let output = row.get("output").and_then(Value::as_str).unwrap_or(""); let base = Path::new(output) .file_name() .and_then(|value| value.to_str()) .unwrap_or("");
            let slot = row.get("slot").and_then(Value::as_str).unwrap_or(""); if !base.is_empty() { if !slot.is_empty() { mapping .entry(slot.to_owned()) .or_insert_with(|| base.to_owned()); } let human = human_label(slot); if !human.is_empty() { mapping.entry(human).or_insert_with(|| base.to_owned()); } } } }
    let mut labels = vec![design.path().join("plan-review-prune-label-map.tsv")]; labels.extend(child_directories(&rounds, "")?.into_iter().map(|path| path.join("plan-review-prune-label-map.tsv"))); for label in labels { for line in split_text_lines(&design.read(&label)?) {
            let fields = line.split('\t').collect::<Vec<_>>(); if fields.len() >= 2 { let slot = fields[0].trim(); let label = fields[1].trim(); if let Some(output) = mapping.get(slot).cloned() && !label.is_empty() { mapping.entry(label.to_owned()).or_insert(output); } } } } Ok(mapping) }
fn numeric_round(name: &str) -> u64 { name.strip_prefix("round-") .and_then(|value| value.parse().ok()) .unwrap_or(0) }
fn human_label(slot: &str) -> String { for (prefix, label, dynamic) in [ ("dyn-cursor-plan-", "Cursor-dyn-", true), ("dyn-codex-plan-", "Codex-dyn-", true), ("cursor-plan-", "Cursor-", false), ("codex-plan-", "Codex-", false), ("claude-plan-", "Claude-", false), ] { if let Some(rest) = slot.strip_prefix(prefix) {
            return if dynamic { format!("{label}{rest}") } else { format!( "{label}{}", rest.split(['_', ' ']) .filter(|part| !part.is_empty()) .map(|part| { let mut chars = part.chars(); chars .next() .map(|first| { first.to_ascii_uppercase().to_string() + chars.as_str() }) .unwrap_or_default() }) .collect::<String>()
                ) }; } } slot.to_owned() }
fn normalize_design_reviewer(value: &str, mapping: &BTreeMap<String, String>) -> String { if mapping.is_empty() { return value.to_owned(); } let values = value .split(',') .map(str::trim) .filter(|part| !part.is_empty()) .map(|part| { mapping .get(part) .cloned() .unwrap_or_else(|| part.to_owned()) })
        .collect::<Vec<_>>(); if values.is_empty() { value.to_owned() } else { values.join(",") } }
}

pub use implementation::compose_findings;
