#!/usr/bin/env bash
# /design session env — generated by write-design-current-env.sh. Do not edit.
export DESIGN_TMPDIR=<TMPDIR>
export SESSION_TMPDIR=<TMPDIR>
export SESSION_ID=DFA9A8F4-5566-449B-9A64-6F67820903D2
export CODEX_PRESENT=true
export CURSOR_PRESENT=false
export CODEX_AVAILABLE=true
export CURSOR_AVAILABLE=false
export CLAUDE_PLUGIN_ROOT=<OPERATOR_REPO_PATH>/plugins/cache/larch-local/larch/42.0.20
