#!/usr/bin/env bash
# /design session env — generated by session_env.py. Do not edit.
export DESIGN_TMPDIR=<TMPDIR>
export SESSION_TMPDIR=<TMPDIR>
export SESSION_ID=6757EE44-C463-45E9-B2D8-B02514EDFDD1
export REPO=character-ai/larch
export ISSUE_NUMBER=4771
export CODEX_BINARY_FOUND=true
export CURSOR_BINARY_FOUND=true
export LARCH_EXTERNAL_HEALTH_CHECK_TIMEOUT=60
export CLAUDE_PLUGIN_ROOT=<OPERATOR_REPO_PATH>/plugins/cache/larch-local/larch/51.3.0
