# pyright: reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnusedCallResult=false, reportOptionalSubscript=false, reportOptionalMemberAccess=false, reportPossiblyUnboundVariable=false, reportUnnecessaryComparison=false, reportUnknownLambdaType=false, reportArgumentType=false
"""Tests for alias helper entrypoints."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import alias_skill
import proc


def _result(argv: list[str], returncode: int = 0, stdout: str = "", stderr: str = "") -> proc.CommandResult:
    return proc.CommandResult(tuple(argv), returncode, stdout, stderr, 0.0)


def test_resolve_target_plugin_and_private(monkeypatch: Any, tmp_path: Path, capsys: Any) -> None:
    (tmp_path / ".claude-plugin").mkdir()
    (tmp_path / ".claude-plugin/plugin.json").write_text("{}", encoding="utf-8")
    (tmp_path / "skills/implement").mkdir(parents=True)
    (tmp_path / "skills/implement/SKILL.md").write_text("x", encoding="utf-8")

    monkeypatch.setattr(alias_skill.proc, "run", lambda argv, **_: _result(argv, stdout=f"{tmp_path}\n"))
    assert alias_skill.resolve_target_main(["--alias-name", "my-alias"]) == 0
    assert f"TARGET_DIR={tmp_path}/skills/my-alias" in capsys.readouterr().out
    assert alias_skill.resolve_target_main(["--alias-name", "my-alias", "--private"]) == 0
    assert f"TARGET_DIR={tmp_path}/.claude/skills/my-alias" in capsys.readouterr().out


def test_generate_yaml_escapes(capsys: Any) -> None:
    assert alias_skill.generate_main(["--name", "q", "--target", "implement", "--flags", '--foo "bar"', "--version", "1.2.3"]) == 0
    out = capsys.readouterr().out
    assert 'description: "Alias for /implement --foo \\"bar\\" (created by /alias)"' in out
    assert '/q <arguments> is equivalent to /implement --foo "bar" <arguments>' in out
    assert "Generated by larch /alias v1.2.3" in out
