#!/usr/bin/env bash
# Generate static reviewer agent body files from agents/reviewer-*.md.
#
# Usage:
#   bash scripts/generate-pre-rendered-reviewer-prompts.sh
#   bash scripts/generate-pre-rendered-reviewer-prompts.sh --check

set -euo pipefail
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd -P)"
AGENTS_DIR="$REPO_ROOT/agents"
OUTPUT_DIR="$AGENTS_DIR/pre-rendered"
# shellcheck source=scripts/lib-quiet.sh
source "$SCRIPT_DIR/lib-quiet.sh"
larch_quiet_init

MODE="write"
if [[ "${1:-}" == "--check" ]]; then
  MODE="check"
elif [[ -n "${1:-}" ]]; then
  larch_err "Usage: $0 [--check]"
  exit 2
fi

sha256_file() {
  local path="$1"
  if command -v shasum >/dev/null 2>&1; then
    LC_ALL=C shasum -a 256 "$path" 2>/dev/null | awk '{print $1}'
  elif command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$path" | awk '{print $1}'
  else
    larch_err "generate-pre-rendered-reviewer-prompts.sh: no SHA-256 tool found (shasum or sha256sum)"
    exit 2
  fi
}

extract_body() {
  local source="$1"
  awk 'BEGIN{n=0} /^---[[:space:]]*$/{n++; if(n==2){found=1; next}} found{print}' "$source"
}

TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/larch-pre-rendered-reviewers.XXXXXX")"
trap 'rm -rf "$TMP_DIR"' EXIT
EXPECTED_DIR="$TMP_DIR/pre-rendered"
mkdir -p "$EXPECTED_DIR"

found=false
while IFS= read -r agent_file; do
  found=true
  base=$(basename "$agent_file" .md)
  body_file="$EXPECTED_DIR/${base}-body.txt"
  if ! extract_body "$agent_file" > "$body_file"; then
    larch_err "generate-pre-rendered-reviewer-prompts.sh: failed to extract body from ${agent_file#"$REPO_ROOT"/}"
    exit 1
  fi
  if [[ ! -s "$body_file" ]]; then
    larch_err "generate-pre-rendered-reviewer-prompts.sh: empty body in ${agent_file#"$REPO_ROOT"/}"
    exit 1
  fi
done < <(find "$AGENTS_DIR" -maxdepth 1 -type f -name 'reviewer-*.md' | sort)

if [[ "$found" != "true" ]]; then
  larch_err "generate-pre-rendered-reviewer-prompts.sh: no agents/reviewer-*.md files found"
  exit 1
fi

{
  printf '# Generated by scripts/generate-pre-rendered-reviewer-prompts.sh. Do not edit.\n'
  while IFS= read -r body_file; do
    rel="agents/pre-rendered/$(basename "$body_file")"
    printf '%s  %s\n' "$(sha256_file "$body_file")" "$rel"
  done < <(find "$EXPECTED_DIR" -maxdepth 1 -type f -name 'reviewer-*-body.txt' | sort)
} > "$EXPECTED_DIR/.manifest"

if [[ "$MODE" == "check" ]]; then
  if [[ ! -d "$OUTPUT_DIR" ]]; then
    larch_err "agents/pre-rendered is missing. Run: bash scripts/generate-pre-rendered-reviewer-prompts.sh"
    exit 1
  fi
  if ! diff -ru "$OUTPUT_DIR" "$EXPECTED_DIR"; then
    larch_err ""
    larch_err "agents/pre-rendered is out of sync with agents/reviewer-*.md."
    larch_err "Run: bash scripts/generate-pre-rendered-reviewer-prompts.sh"
    exit 1
  fi
  exit 0
fi

mkdir -p "$OUTPUT_DIR"
find "$OUTPUT_DIR" -maxdepth 1 -type f \( -name 'reviewer-*-body.txt' -o -name '.manifest' \) -exec rm -f {} +
while IFS= read -r expected_file; do
  target="$OUTPUT_DIR/$(basename "$expected_file")"
  tmp=$(mktemp "${target}.tmp.XXXXXX")
  cp "$expected_file" "$tmp"
  mv "$tmp" "$target"
done < <(find "$EXPECTED_DIR" -maxdepth 1 -type f \( -name 'reviewer-*-body.txt' -o -name '.manifest' \) | sort)

emit_breadcrumb "Wrote $OUTPUT_DIR"
