#!/usr/bin/env bash
# Resolve an active larch implement/review session from Claude hook stdin.

set -euo pipefail
LC_ALL=C

if ! command -v jq >/dev/null 2>&1; then
    exit 0
fi

INPUT=$(cat) || exit 0
HOOK_CWD=$(printf '%s' "$INPUT" | jq -r '.cwd // empty' 2>/dev/null) || exit 0
# Note: jq's .session_id is intentionally NOT consulted — Claude's hook
# session_id (transcript namespace) and larch's keepalive SESSION_ID
# (uuidgen, generated by session-setup.sh) are different namespaces and
# never match in production. Bind on cwd + TTL only.

if [[ -z "$HOOK_CWD" ]]; then
    exit 0
fi

# Accept the canonical XDG cache root AND the /tmp fallback that
# session-setup.sh uses when the cache root is unwritable. macOS resolves
# /tmp -> /private/tmp; mktemp may emit either form.
declare -a SESSIONS_ROOTS=()
SESSIONS_ROOTS+=("${XDG_CACHE_HOME:-${HOME:-/tmp}/.cache}/larch/sessions")
SESSIONS_ROOTS+=("/tmp")
SESSIONS_ROOTS+=("/private/tmp")

now=$(date +%s 2>/dev/null || echo 0)
ttl=${LARCH_ACTIVE_SESSION_TTL_SECONDS:-21600}
[[ "$ttl" =~ ^[0-9]+$ ]] || ttl=21600

best=""
best_mtime=0
best_prefix=""

declare -a CANDIDATE_DIRS=()
for root in "${SESSIONS_ROOTS[@]}"; do
    [[ -d "$root" ]] || continue
    for dir in "$root"/claude-implement-* "$root"/claude-review-*; do
        [[ -d "$dir" ]] || continue
        CANDIDATE_DIRS+=("$dir")
    done
done

for dir in "${CANDIDATE_DIRS[@]}"; do
    keepalive="$dir/.larch-keepalive"
    [[ -f "$keepalive" ]] || continue

    match=$(awk -F= -v cwd="$HOOK_CWD" '
        $1 == "CLONE_PATH" {
            v = substr($0, index($0, "=") + 1)
            if (v == cwd) cwd_ok = 1
        }
        END {
            if (cwd_ok) print "ok"
        }
    ' "$keepalive" 2>/dev/null || true)
    [[ "$match" == "ok" ]] || continue

    mtime=$(stat -c %Y "$keepalive" 2>/dev/null) \
        || mtime=$(stat -f %m "$keepalive" 2>/dev/null) \
        || continue
    [[ "$mtime" =~ ^[0-9]+$ ]] || continue
    if (( ttl > 0 )); then
        (( now > 0 )) || continue
        (( (now - mtime) < ttl )) || continue
    fi

    prefix=$(basename "$dir")
    prefix=${prefix%%-*}-${prefix#*-}
    prefix=${prefix%-*}
    case "$(basename "$dir")" in
        claude-implement-*) prefix="claude-implement" ;;
        claude-review-*) prefix="claude-review" ;;
        *) continue ;;
    esac

    if (( mtime > best_mtime )); then
        best_mtime=$mtime
        best=$dir
        best_prefix=$prefix
    elif (( mtime == best_mtime )) && [[ -n "$best" && "$dir" < "$best" ]]; then
        best=$dir
        best_prefix=$prefix
    elif (( mtime == best_mtime )) && [[ -z "$best" ]]; then
        best=$dir
        best_prefix=$prefix
    fi
done

if [[ -n "$best" ]]; then
    printf 'PREFIX=%s TMPDIR=%s\n' "$best_prefix" "$best"
fi
