# shellcheck shell=bash
# lib-timing-kinds.sh — Canonical timing task-kind allow-list.

# shellcheck disable=SC2034
TIMING_TASK_KINDS_ALLOWED=(
    codex-review
    cursor-review
    codex-review-generic
    cursor-review-generic
    codex-implement
    cursor-implement
    codex-ci-fix
    cursor-ci-fix
    claude-ci-fix
    claude-review
    codex-sketch-arch
    codex-sketch-edge
    codex-sketch-innovation
    codex-sketch-pragmatic
    cursor-sketch-arch
    cursor-sketch-edge
    cursor-sketch-innovation
    cursor-sketch-pragmatic
    codex-sketch-generic
    cursor-sketch-generic
    cursor-brainstorm
    codex-brainstorm
    codex-plan-arch
    codex-plan-edge
    codex-plan-innovation
    codex-plan-pragmatic
    codex-plan-requirements
    cursor-plan-arch
    cursor-plan-edge
    cursor-plan-innovation
    cursor-plan-pragmatic
    cursor-plan-requirements
    codex-plan-voter
    cursor-plan-voter
    claude-plan-voter
    claude-code-voter
    claude-plan-generic
    claude-decomp-generic
    claude-voter-1-parse-retry
    codex-plan-autofix
    cursor-plan-autofix
    codex-review-voter
    cursor-review-voter
    claude-phase3-security
    claude-phase3-correctness
    claude-phase3-edge-cases
    claude-phase3-testing
    claude-phase3-aggregator
    scout-dynamic-archetypes
    cursor-specialist-structure
    cursor-specialist-correctness
    cursor-specialist-testing
    cursor-specialist-security
    cursor-specialist-edge-cases
    cursor-specialist-plan-fidelity
    codex-specialist-structure
    codex-specialist-correctness
    codex-specialist-testing
    codex-specialist-security
    codex-specialist-edge-cases
    codex-specialist-plan-fidelity
    codex-debate-thesis
    codex-debate-antithesis
    cursor-debate-thesis
    cursor-debate-antithesis
    cursor-debate-thesis-retry1
    cursor-debate-antithesis-retry1
    codex-debate-thesis-retry1
    codex-debate-antithesis-retry1
    claude-debate-thesis-retry2
    claude-debate-antithesis-retry2
    codex-judge
    cursor-judge
    codex-exec
    vendor-misc
)
