#!/usr/bin/env bash
# Combined /implement rebase checkpoint + post-rebase phantom probe.
# See scripts/rebase-checkpoint-probe.md for argv, exit codes, and KV grammar.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib-quiet.sh
source "$SCRIPT_DIR/lib-quiet.sh"
# shellcheck source=scripts/lib-phantom-probe.sh
source "$SCRIPT_DIR/lib-phantom-probe.sh"

usage() {
    printf 'usage: %s <step-prefix> <short-name> [--base-remote <name>] [--base-ref <branch>] [--forked-target true|false]\n' "$(basename "$0")" >&2
    exit 2
}

step_prefix="${1:-}"
short_name="${2:-}"
if [ -z "$step_prefix" ] || [ -z "$short_name" ]; then
    usage
fi
shift 2

base_remote=""
base_ref=""
forked_target="false"
while [ $# -gt 0 ]; do
    case "$1" in
        --base-remote)
            [ $# -ge 2 ] || usage
            base_remote="$2"
            shift 2
            ;;
        --base-ref)
            [ $# -ge 2 ] || usage
            base_ref="$2"
            shift 2
            ;;
        --forked-target)
            [ $# -ge 2 ] || usage
            forked_target="$2"
            case "$forked_target" in true|false) ;; *) usage ;; esac
            shift 2
            ;;
        *) usage ;;
    esac
done

larch_err "→ rebase-probe: ${step_prefix} ${short_name}"

rebase_args=(--no-push --skip-if-pushed --keep-on-conflict)
if [ "$forked_target" = "true" ]; then
    [ -n "$base_remote" ] || base_remote=upstream
    [ -n "$base_ref" ] || base_ref=main
fi
if [ -n "$base_remote" ]; then
    rebase_args+=(--base-remote "$base_remote")
fi
if [ -n "$base_ref" ]; then
    rebase_args+=(--base-ref "$base_ref")
fi

rb_stdout=$(mktemp)
rb_stderr=$(mktemp)
conflict_paths=$(mktemp)
trivial_paths=$(mktemp)
nontrivial_paths=$(mktemp)
trap 'rm -f "$rb_stdout" "$rb_stderr" "$conflict_paths" "$trivial_paths" "$nontrivial_paths"' EXIT

_run_rebase_push() {
    : >"$rb_stdout"
    : >"$rb_stderr"
    set +e
    LARCH_QUIET_DISABLE=1 "${SCRIPT_DIR}/rebase-push.sh" "$@" >"$rb_stdout" 2>"$rb_stderr"
    local rb_rc=$?
    return "$rb_rc"
}

_is_trivial_conflict_file() {
    case "$1" in
        larch-logs/*) return 0 ;;
        *) return 1 ;;
    esac
}

_resolve_trivial_conflict_file() {
    local path="$1" checkout_rc rm_rc add_rc

    # During a rebase, --ours is the upstream/base side. Run-log artifacts are
    # generated by larch, so the upstream/base version is authoritative.
    set +e
    git checkout --ours -- "$path" >/dev/null 2>&1
    checkout_rc=$?
    set -e
    if [ "$checkout_rc" -ne 0 ]; then
        set +e
        git rm -f -- "$path" >/dev/null 2>&1
        rm_rc=$?
        set -e
        if [ "$rm_rc" -ne 0 ]; then
            larch_err "WARN rebase-probe: failed to resolve trivial conflict ${path}"
            return 1
        fi
        return 0
    fi

    set +e
    git add -- "$path" >/dev/null 2>&1
    add_rc=$?
    set -e
    if [ "$add_rc" -ne 0 ]; then
        larch_err "WARN rebase-probe: failed to stage trivial conflict ${path}"
        return 1
    fi
    return 0
}

_join_conflict_file() {
    local file="$1" line joined
    joined=""
    while IFS= read -r line || [ -n "$line" ]; do
        [ -n "$line" ] || continue
        if [ -n "$joined" ]; then
            joined="${joined},${line}"
        else
            joined="$line"
        fi
    done <"$file"
    printf '%s' "$joined"
}

_current_unmerged_conflict_files() {
    git diff --name-only --diff-filter=U 2>/dev/null | tr '\n' ',' | sed 's/,$//'
}

set +e
_run_rebase_push "${rebase_args[@]}"
rc=$?
set -e

_rebase_sanitize() {
    printf '%s' "$1" | tr '\n' ' ' | sed 's/[[:space:]]\{1,\}/ /g' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'
}

_parse_conflict_files() {
    local line cf
    cf=""
    while IFS= read -r line || [ -n "$line" ]; do
        case "$line" in
            CONFLICT_FILES=*) cf="${line#CONFLICT_FILES=}" ;;
        esac
    done <"$rb_stdout"
    if [ -z "$cf" ]; then
        cf=$(git diff --name-only --diff-filter=U 2>/dev/null | tr '\n' ',' | sed 's/,$//')
    fi
    printf '%s' "$cf"
}

_parse_rebase_error() {
    local line err
    err=""
    while IFS= read -r line || [ -n "$line" ]; do
        case "$line" in
            REBASE_ERROR=*) err="${line#REBASE_ERROR=}"; printf '%s' "$err"; return 0 ;;
        esac
    done <"$rb_stdout"
    while IFS= read -r line || [ -n "$line" ]; do
        case "$line" in
            REBASE_ERROR=*) err="${line#REBASE_ERROR=}"; printf '%s' "$err"; return 0 ;;
        esac
    done <"$rb_stderr"
    return 1
}

cf=""
cf_ready=false
if [ "$rc" -eq 1 ]; then
    trivial_iterations=0
    while [ "$rc" -eq 1 ]; do
        if [ "$trivial_iterations" -ge 50 ]; then
            larch_err "WARN rebase-probe: trivial conflict pre-pass hit iteration cap; surfacing current conflicts"
            cf=$(_parse_conflict_files)
            cf_ready=true
            break
        fi
        trivial_iterations=$((trivial_iterations + 1))

        cf=$(_parse_conflict_files)
        cf_ready=true
        if [ -z "$cf" ]; then
            break
        fi

        : >"$conflict_paths"
        : >"$trivial_paths"
        : >"$nontrivial_paths"
        printf '%s' "$cf" | tr ',' '\n' >"$conflict_paths"

        has_conflict_path=false
        has_trivial=false
        has_nontrivial=false
        while IFS= read -r path || [ -n "$path" ]; do
            [ -n "$path" ] || continue
            has_conflict_path=true
            if _is_trivial_conflict_file "$path"; then
                printf '%s\n' "$path" >>"$trivial_paths"
                has_trivial=true
            else
                printf '%s\n' "$path" >>"$nontrivial_paths"
                has_nontrivial=true
            fi
        done <"$conflict_paths"

        if [ "$has_conflict_path" != "true" ]; then
            cf=""
            cf_ready=true
            break
        fi

        resolve_failed=false
        if [ "$has_trivial" = "true" ]; then
            while IFS= read -r path || [ -n "$path" ]; do
                [ -n "$path" ] || continue
                if ! _resolve_trivial_conflict_file "$path"; then
                    resolve_failed=true
                    break
                fi
            done <"$trivial_paths"
        fi

        if [ "$resolve_failed" = "true" ]; then
            cf=$(_current_unmerged_conflict_files)
            cf_ready=true
            break
        fi

        if [ "$has_nontrivial" = "true" ]; then
            cf=$(_join_conflict_file "$nontrivial_paths")
            cf_ready=true
            break
        fi

        set +e
        _run_rebase_push --continue --no-push --keep-on-conflict
        rc=$?
        set -e
    done
fi

if [ "$rc" -eq 0 ]; then
    # SKIPPED_ALREADY_PUSHED before SKIPPED_ALREADY_FRESH (precedence).
    if grep -Fx "SKIPPED_ALREADY_PUSHED=true" "$rb_stdout" >/dev/null 2>&1; then
        emit_kv SKIPPED_ALREADY_PUSHED "true"
        emit_kv REBASE_OUTCOME "skipped"
    elif grep -Fx "SKIPPED_ALREADY_FRESH=true" "$rb_stdout" >/dev/null 2>&1; then
        emit_kv SKIPPED_ALREADY_FRESH "true"
        emit_kv REBASE_OUTCOME "skipped"
    else
        emit_kv REBASE_OUTCOME "ok"
    fi
    emit_kv ROUTE "continue"
    phantom_probe_with_warn "${step_prefix}-post-rebase"
    exit 0
fi

if [ "$rc" -eq 1 ]; then
    if [ "$cf_ready" != "true" ]; then
        cf=$(_parse_conflict_files)
    fi
    emit_kv REBASE_OUTCOME "conflict"
    emit_kv CONFLICT_FILES "$cf"
    emit_kv ROUTE "conflict"
    exit 1
fi

if [ "$rc" -eq 3 ]; then
    if raw_err=$(_parse_rebase_error); then
        :
    else
        raw_err=""
    fi
    emit_kv REBASE_OUTCOME "failed"
    emit_kv REBASE_ERROR "$(_rebase_sanitize "${raw_err:-rebase-failed}")"
    emit_kv ROUTE "bail"
    exit 3
fi

emit_kv REBASE_OUTCOME "failed"
emit_kv REBASE_ERROR "unexpected-rc-${rc}"
emit_kv ROUTE "bail"
exit "$rc"
