#!/usr/bin/env bash
# write-design-current-env.sh — Write a sourceable /design session-env file
# and refresh the stable symlink consumers source from every Bash block.
#
# Usage:
#   write-design-current-env.sh --output <path> \
#                               --design-tmpdir <path> \
#                               --session-id <id> \
#                               [--codex-present <true|false>] \
#                               [--cursor-present <true|false>] \
#                               [--codex-available <true|false>] \
#                               [--cursor-available <true|false>] \
#                               [--issue-number <n>]
#
# Output: writes a sourceable bash file at --output (atomic temp+mv), then
# updates a stable symlink at ~/.cache/larch/sessions/current-design-env.sh
# pointing at --output (atomic ln -sfn). Values are shell-quoted via
# printf '%q' so paths containing spaces or shell metacharacters survive
# round-tripping through `source`.
#
# Single-runner contract: only one /design may run per repository at a time
# (mirrors the /implement single-runner invariant). Concurrent runs clobber
# the symlink and corrupt downstream Bash blocks.
#
# Exit codes: 0 success, 1 invalid args.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib-quiet.sh
source "$SCRIPT_DIR/lib-quiet.sh"
larch_quiet_init

OUTPUT=""
DESIGN_TMPDIR_ARG=""
SESSION_ID=""
CODEX_PRESENT=""
CURSOR_PRESENT=""
CODEX_AVAILABLE=""
CURSOR_AVAILABLE=""
ISSUE_NUMBER=""
CLAUDE_PLUGIN_ROOT_VALUE="${CLAUDE_PLUGIN_ROOT:-}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output)           OUTPUT="$2"; shift 2 ;;
    --design-tmpdir)    DESIGN_TMPDIR_ARG="$2"; shift 2 ;;
    --session-id)       SESSION_ID="$2"; shift 2 ;;
    --codex-present)    CODEX_PRESENT="$2"; shift 2 ;;
    --cursor-present)   CURSOR_PRESENT="$2"; shift 2 ;;
    --codex-available)  CODEX_AVAILABLE="$2"; shift 2 ;;
    --cursor-available) CURSOR_AVAILABLE="$2"; shift 2 ;;
    --issue-number)     ISSUE_NUMBER="$2"; shift 2 ;;
    *) larch_err "ERROR=Unknown argument: $1"; exit 1 ;;
  esac
done

if [[ -z "$OUTPUT" || -z "$DESIGN_TMPDIR_ARG" || -z "$SESSION_ID" ]]; then
  larch_err "ERROR=Missing required arguments: --output, --design-tmpdir, --session-id"
  exit 1
fi

validate_bool() {
  local flag_name="$1" val="$2"
  if [[ -n "$val" && "$val" != "true" && "$val" != "false" ]]; then
    larch_err "ERROR=Invalid --${flag_name}: must be true or false"
    exit 1
  fi
}
validate_bool codex-present "$CODEX_PRESENT"
validate_bool cursor-present "$CURSOR_PRESENT"
validate_bool codex-available "$CODEX_AVAILABLE"
validate_bool cursor-available "$CURSOR_AVAILABLE"

if [[ -n "$ISSUE_NUMBER" && ! "$ISSUE_NUMBER" =~ ^[0-9]+$ ]]; then
  larch_err "ERROR=Invalid --issue-number: must be a non-negative integer"
  exit 1
fi

if [[ ! "$SESSION_ID" =~ ^[A-Za-z0-9_.-]{1,128}$ ]]; then
  larch_err "ERROR=Invalid --session-id: must match ^[A-Za-z0-9_.-]{1,128}$"
  exit 1
fi

if [[ "$DESIGN_TMPDIR_ARG" != /* ]]; then
  larch_err "ERROR=Invalid --design-tmpdir: must be an absolute path"
  exit 1
fi

if [[ "$OUTPUT" != /* ]]; then
  larch_err "ERROR=Invalid --output: must be an absolute path"
  exit 1
fi

build_export() {
  local key="$1" val="$2"
  printf 'export %s=%q\n' "$key" "$val"
}

{
  printf '#!/usr/bin/env bash\n'
  printf '# /design session env — generated by write-design-current-env.sh. Do not edit.\n'
  build_export DESIGN_TMPDIR "$DESIGN_TMPDIR_ARG"
  build_export SESSION_TMPDIR "$DESIGN_TMPDIR_ARG"
  build_export SESSION_ID "$SESSION_ID"
  [[ -n "$ISSUE_NUMBER" ]] && build_export ISSUE_NUMBER "$ISSUE_NUMBER"
  [[ -n "$CODEX_PRESENT" ]] && build_export CODEX_PRESENT "$CODEX_PRESENT"
  [[ -n "$CURSOR_PRESENT" ]] && build_export CURSOR_PRESENT "$CURSOR_PRESENT"
  [[ -n "$CODEX_AVAILABLE" ]] && build_export CODEX_AVAILABLE "$CODEX_AVAILABLE"
  [[ -n "$CURSOR_AVAILABLE" ]] && build_export CURSOR_AVAILABLE "$CURSOR_AVAILABLE"
  [[ -n "$CLAUDE_PLUGIN_ROOT_VALUE" ]] && build_export CLAUDE_PLUGIN_ROOT "$CLAUDE_PLUGIN_ROOT_VALUE"
} > "${OUTPUT}.tmp.$$"

mv "${OUTPUT}.tmp.$$" "$OUTPUT"

SYMLINK_DIR="${HOME}/.cache/larch/sessions"
SYMLINK_PATH="${SYMLINK_DIR}/current-design-env.sh"
mkdir -p "$SYMLINK_DIR"
ln -sfn "$OUTPUT" "$SYMLINK_PATH"
