"""CLI entrypoint for /report-tokens."""

from __future__ import annotations

import argparse
import os
import shutil
import sys
import tempfile
from datetime import UTC, datetime
from pathlib import Path

from larch.core import config
from larch.core import proc
from larch.core import redact
from larch.errors import ShipError
from larch.report.report_tokens_cost import display_rates, price_run
from larch.report.report_tokens_issue import post_issue
from larch.report.report_tokens_models import DisplayRates, ReportSection, Skill
from larch.report.report_tokens_plot import plot
from larch.report.report_tokens_render import render, title_for_skill
from larch.report.report_tokens_scan import ScanResult, scan


def env_flag_enabled(name: str) -> bool:
    value = os.environ.get(name, "").strip().lower()
    return value not in ("", "0", "false", "no")


def _actual_spend() -> float | None:
    raw = os.environ.get(config.ENV_LARCH_REPORT_TOKENS_ACTUAL_SPEND, "").strip()
    if not raw:
        return None
    try:
        return float(raw)
    except ValueError:
        print("Warning: LARCH_REPORT_TOKENS_ACTUAL_SPEND is not numeric; ignoring", file=sys.stderr)
        return None


def _scan_reports(skill: Skill, *, repo_override: str | None, resolve_repo: bool) -> ScanResult:
    try:
        return scan(proc, skill=skill, repo_override=repo_override, resolve_repo=resolve_repo)
    except TypeError as exc:
        if "resolve_repo" not in str(exc):
            raise
        return scan(proc, skill=skill, repo_override=repo_override)


def _path_is_under(path: Path, root: Path) -> bool:
    try:
        _ = path.resolve().relative_to(root.resolve())
    except OSError:
        return False
    except ValueError:
        return False
    return True


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Analyze token costs from larch run logs.")
    _ = parser.add_argument("--skill", choices=("design", "implement"), required=True)
    _ = parser.add_argument("--no-issue", action="store_true")
    _ = parser.add_argument("--no-plot", action="store_true")
    _ = parser.add_argument("--plot-from", help=argparse.SUPPRESS)
    args = parser.parse_args(argv)
    if args.plot_from is not None:
        parser.error("--plot-from has been removed; scan committed larch-logs instead")
    return args


def _write_empty_report(temp_root: Path) -> bool:
    print(redact.redact("## Report Tokens Analysis"))
    print()
    print(redact.redact("No parseable token reports found."))
    cache_path = temp_root / "report-cache.ndjson"
    _ = cache_path.write_text("", encoding="utf-8")
    print(redact.redact(f"Cache JSON: {cache_path}"))
    return _path_is_under(cache_path, temp_root)


def _print_analysis(*, analysis: str, plot_paths: list[Path], no_plot: bool) -> None:
    print(redact.redact(analysis))
    if plot_paths:
        print(redact.redact("\nPlots written to:"))
        for path in plot_paths:
            print(redact.redact(f"- {path}"))
    elif no_plot:
        print(redact.redact("\nPlot generation disabled."))
    else:
        print(redact.redact("\nNo plots generated by plot subprocess."))


def _post_report_if_requested(*, no_issue: bool, scanned: ScanResult, sections: list[ReportSection], skill: Skill) -> int | None:
    if no_issue:
        return None
    if not scanned.repo_slug:
        print("ERROR: could not resolve GitHub repo owner/name; rerun with --no-issue or LARCH_REPORT_TOKENS_REPO", file=sys.stderr)
        return config.EXIT_BAIL
    timestamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    try:
        post_issue(
            proc,
            repo=scanned.repo_slug,
            title=title_for_skill(skill, timestamp=timestamp),
            sections=sections,
            skill=skill,
        )
    except ShipError:
        return config.EXIT_BAIL
    return None


def _main_with_temp_root(*, args: argparse.Namespace, temp_root: Path, repo_override: str | None) -> tuple[int, bool]:
    skill: Skill = args.skill
    no_issue = bool(args.no_issue) or env_flag_enabled(config.ENV_LARCH_REPORT_TOKENS_NO_ISSUE)
    no_plot = bool(args.no_plot) or env_flag_enabled(config.ENV_LARCH_REPORT_TOKENS_NO_PLOT)
    try:
        scanned = _scan_reports(skill, repo_override=repo_override, resolve_repo=not no_issue)
    except ShipError as exc:
        print(str(exc), file=sys.stderr)
        return config.EXIT_BAIL, False
    if not scanned.records:
        return config.EXIT_OK, _write_empty_report(temp_root)

    priced = tuple(price_run(proc, record=record) for record in scanned.records)
    actual_spend: float | None = _actual_spend()
    if actual_spend is not None:
        print(
            "Warning: actual spend was provided; it is printed to stdout but omitted from posted issues unless explicitly enabled.",
            file=sys.stderr,
        )
    include_actual = env_flag_enabled(config.ENV_LARCH_REPORT_TOKENS_POST_ACTUAL_SPEND)
    rates: DisplayRates = display_rates()
    analysis, sections, cache_path = render(
        skill=skill,
        records=priced,
        rates_display=rates,
        actual_spend=actual_spend,
        include_actual_spend_in_issue=include_actual,
        temp_root=temp_root,
    )
    cache_advertised = _path_is_under(Path(cache_path), temp_root) and f"Cache JSON: {cache_path}" in analysis
    plot_paths = plot(proc, skill=skill, records=priced, plot_parent_dir=temp_root, no_plot=no_plot)
    preserve_temp_root = bool(plot_paths) or cache_advertised
    _print_analysis(analysis=analysis, plot_paths=plot_paths, no_plot=no_plot)
    post_rc = _post_report_if_requested(no_issue=no_issue, scanned=scanned, sections=sections, skill=skill)
    if post_rc is not None:
        return post_rc, preserve_temp_root
    return config.EXIT_OK, preserve_temp_root


def main(argv: list[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    temp_root = Path(tempfile.mkdtemp(prefix="larch-report-tokens."))
    preserve_temp_root = False
    repo_override: str | None = os.environ.get(config.ENV_LARCH_REPORT_TOKENS_REPO)
    try:
        rc, preserve_temp_root = _main_with_temp_root(args=args, temp_root=temp_root, repo_override=repo_override)
        return rc
    finally:
        if not preserve_temp_root:
            shutil.rmtree(temp_root, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())
