#!/usr/bin/env bash
# Dispatch /design ACTION records to mechanical helper scripts.

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd -P)

DESIGN_TMPDIR=""
ACTION_FILE=""
RESUME_FROM=""

usage() {
    cat >&2 <<'USAGE'
usage: design-driver.sh --design-tmpdir DIR [--action-file FILE] [--resume-from STEP]
USAGE
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --design-tmpdir)
            DESIGN_TMPDIR="${2:?--design-tmpdir requires a value}"
            shift 2
            ;;
        --action-file)
            ACTION_FILE="${2:?--action-file requires a value}"
            shift 2
            ;;
        --resume-from)
            RESUME_FROM="${2:?--resume-from requires a value}"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "design-driver.sh: unknown argument: $1" >&2
            usage
            exit 2
            ;;
    esac
done

if [[ -z "$DESIGN_TMPDIR" ]]; then
    echo "design-driver.sh: --design-tmpdir is required" >&2
    usage
    exit 2
fi
if [[ -n "$ACTION_FILE" && ! -r "$ACTION_FILE" ]]; then
    echo "design-driver.sh: --action-file is missing or unreadable: $ACTION_FILE" >&2
    exit 2
fi
mkdir -p "$DESIGN_TMPDIR/.completed"

normalize_step() {
    printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9._-' '-'
}

extract_args() {
    local line="$1"
    case "$line" in
        *' ARGS='*) printf '%s' "${line#* ARGS=}" ;;
        *) printf '%s' "" ;;
    esac
}

run_action() {
    local action="$1"
    shift
    case "$action" in
        CLASSIFY)
            "$SCRIPT_DIR/classify-issue.sh" "$@"
            ;;
        EMIT_PLAN)
            "$SCRIPT_DIR/emit-plan.sh" --design-tmpdir "$DESIGN_TMPDIR" "$@"
            ;;
        TALLY)
            "$SCRIPT_DIR/tally-plan-review.sh" --design-tmpdir "$DESIGN_TMPDIR" "$@"
            ;;
        FINALIZE)
            "$SCRIPT_DIR/finalize-plan.sh" --design-tmpdir "$DESIGN_TMPDIR" "$@"
            ;;
        *)
            return 64
            ;;
    esac
}

resume_seen=false
[[ -z "$RESUME_FROM" ]] && resume_seen=true

process_line() {
    local line="$1" action args_text sentinel rc step_name
    [[ -z "$line" ]] && return 0
    case "$line" in
        ACTION=*) ;;
        *)
            printf 'ACTION_PASSTHROUGH=%s\n' "$line"
            return 0
            ;;
    esac

    action="${line#ACTION=}"
    action="${action%% *}"
    case "$action" in
        CLASSIFY|EMIT_PLAN|TALLY|FINALIZE) ;;
        *)
            printf 'ACTION_PASSTHROUGH=%s\n' "$line"
            return 0
            ;;
    esac
    step_name=$(normalize_step "$action")
    sentinel="$DESIGN_TMPDIR/.completed/$step_name"

    # EMIT_PLAN is a re-runnable validation action (plan.txt may be revised
    # by accepted plan-review findings and must re-emit diff-lines.txt).
    # Do not skip it on replay, even when the sentinel exists.
    local no_sentinel=false
    [[ "$action" == "EMIT_PLAN" ]] && no_sentinel=true

    if [[ "$resume_seen" != "true" ]]; then
        if [[ "$action" == "$RESUME_FROM" || "$step_name" == "$(normalize_step "$RESUME_FROM")" ]]; then
            resume_seen=true
        elif [[ -f "$sentinel" && "$no_sentinel" != "true" ]]; then
            printf 'STEP_SKIPPED=%s REASON=completed-before-resume\n' "$action"
            return 0
        else
            printf 'STEP_SKIPPED=%s REASON=before-resume\n' "$action"
            return 0
        fi
    elif [[ -f "$sentinel" && "$no_sentinel" != "true" ]]; then
        printf 'STEP_SKIPPED=%s REASON=already-completed\n' "$action"
        return 0
    fi

    args_text=$(extract_args "$line")
    # ACTION records are generated by SKILL.md using plain, shell-like argv.
    # Paths in this workflow are absolute temp paths without spaces.
    read -r -a action_args <<< "$args_text"

    printf 'STEP_STARTED=%s\n' "$action"
    set +e
    run_action "$action" "${action_args[@]+"${action_args[@]}"}"
    rc=$?
    set -e

    if [[ "$rc" -eq 64 ]]; then
        printf 'ACTION_PASSTHROUGH=%s\n' "$line"
        return 0
    fi
    if [[ "$rc" -ne 0 ]]; then
        printf 'STEP_FAILED=%s REASON=exit-%s\n' "$action" "$rc"
        return "$rc"
    fi

    : > "$sentinel"
    printf 'STEP_COMPLETED=%s\n' "$action"
}

if [[ -n "$ACTION_FILE" ]]; then
    while IFS= read -r line || [[ -n "$line" ]]; do
        process_line "$line"
    done < "$ACTION_FILE"
else
    while IFS= read -r line || [[ -n "$line" ]]; do
        process_line "$line"
    done
fi
