"""Argparse-based subcommand dispatcher for larch Python runtime.

Canonical location; python/cli.py is the entry-point shim.
Direct-call convention: consumers invoke
    python3 "${CLAUDE_PLUGIN_ROOT}/python/cli.py" <domain> <verb> [args...]
No .sh shim files, ever. See docs/python-migration.md for the migration playbook.
"""

from __future__ import annotations

import argparse
import importlib
import os
import sys

_REGISTRY: dict[tuple[str, str], tuple[str, str]] = {
    ("agent", "model-args"): ("larch.agents.agents", "model_args_main"),
    ("agent", "read-claude-model"): ("larch.agents.agents", "read_claude_model_main"),
    ("agent", "cursor-auth-preflight"): ("larch.agents.agents", "cursor_auth_preflight_main"),
    ("agent", "cursor-wrap-prompt"): ("larch.agents.agents", "cursor_wrap_prompt_main"),
    ("agent", "external-tool-registry"): ("larch.agents.agents", "external_tool_registry_main"),
    ("agent", "check-reviewers"): ("larch.agents.agents", "check_reviewers_main"),
    ("agent", "collect-results"): ("larch.agents.collect_results", "collect_results_main"),
    ("agent", "dispatch-waterfall"): ("larch.agents.agent_waterfall", "dispatch_waterfall_main"),
    ("agent", "dispatch-voters"): ("larch.agents.agent_voters", "dispatch_voters_main"),
    ("agent", "run-negotiation-round"): ("larch.agents.agents", "run_negotiation_round_main"),
    ("agent", "degraded-tools-gate"): ("larch.agents.agents", "degraded_tools_gate_main"),
    ("status", "check"): ("larch.agents.agents", "status_check_main"),
    ("agent", "parse-codex-usage"): ("larch.agents.agents", "parse_codex_usage_main"),
    ("agent", "run-external-agent"): ("larch.agents.agents", "run_external_agent_main"),
    ("agent", "launch-review"): ("larch.agents.agents", "launch_review_main"),
    ("agent", "wait-reviewers"): ("larch.agents.review_dispatch", "wait_reviewers_main"),
    ("agent", "classify-diff"): ("larch.agents.review_dispatch", "classify_diff_main"),
    ("agent", "gather-branch-context"): ("larch.agents.review_dispatch", "gather_branch_context_main"),
    ("agent", "compose-collector-failure-log"): ("larch.agents.review_dispatch", "compose_collector_failure_log_main"),
    ("agent", "launch-codex-ci"): ("larch.agents.agents", "launch_codex_ci_main"),
    ("agent", "launch-codex-implement"): ("larch.agents.agents", "launch_codex_implement_main"),
    ("agent", "launch-codex-exec"): ("larch.agents.agents", "launch_codex_exec_main"),
    ("agent", "launch-codex-drafter"): ("larch.agents.agents", "launch_codex_drafter_main"),
    ("agent", "launch-claude-drafter"): ("larch.agents.agents", "launch_claude_drafter_main"),
    ("agent", "launch-cursor-ci"): ("larch.agents.agents", "launch_cursor_ci_main"),
    ("agent", "launch-cursor-implement"): ("larch.agents.agents", "launch_cursor_implement_main"),
    ("agent", "launch-claude-ci"): ("larch.agents.agents", "launch_claude_ci_main"),
    ("agent", "launch-claude-lint-fix"): ("larch.agents.agents", "launch_claude_lint_fix_main"),
    ("agent", "launch-claude-review"): ("larch.agents.agents", "launch_claude_review_main"),
    ("agent", "launch-claude-subprocess"): ("larch.agents.agents", "launch_claude_subprocess_main"),
    ("calibration-replay", "rebuild-ballot"): ("larch.calibration.calibration_replay", "rebuild_ballot_main"),
    ("calibration-replay", "run-replay"): ("larch.calibration.calibration_replay", "run_replay_main"),
    ("calibration-replay", "validate-manifest"): ("larch.calibration.calibration_replay", "validate_manifest_main"),
    ("checks", "run-relevant"): ("larch.implement.checks", "checks_run_relevant_main"),
    ("checks", "lint-fix"): ("larch.implement.checks", "checks_lint_fix_main"),
    ("checks", "repair-loop"): ("larch.implement.checks", "checks_repair_loop_main"),
    ("checks", "contains-pins"): ("larch.implement.checks", "check_contains_pins_main"),
    ("ci", "agentic-fix"): ("larch.implement.ci", "agentic_fix_main"),
    ("bootstrap", "invoke"): ("larch.state.bootstrap", "invoke_main"),
    ("bootstrap", "parse-routing"): ("larch.state.bootstrap", "parse_routing_main"),
    ("bootstrap", "resolve-non-interactive"): ("larch.state.bootstrap", "resolve_non_interactive_main"),
    ("admission", "gate"): ("larch.state.admission", "gate_main"),
    ("admission", "preflight"): ("larch.state.admission", "preflight_main"),
    ("admission", "fork-env"): ("larch.state.admission", "fork_env_main"),
    ("dirty-tree", "baseline"): ("larch.state.dirty_tree", "baseline_main"),
    ("dirty-tree", "checkpoint"): ("larch.state.dirty_tree", "checkpoint_main"),
    ("dirty-tree", "scope-check"): ("larch.state.dirty_tree", "scope_check_main"),
    ("dirty-tree", "scope-marker"): ("larch.state.dirty_tree", "scope_marker_main"),
    ("release", "classify-bump"): ("larch.release.version_bump", "classify_bump_main"),
    ("release", "prepare"): ("larch.release.release_prepare", "main"),
    ("release", "set-version"): ("larch.release.version_bump", "set_version_main"),
    ("residual-bash", "paths"): ("larch.core.residual_bash", "paths_main"),
    ("release", "finish"): ("larch.release.release_finish", "main"),
    ("release", "promote"): ("larch.release.promote_release", "promote_main"),
    ("release", "promote-latest"): ("larch.release.promote_release", "promote_latest_main"),
    ("plugin", "read-version"): ("larch.release.version_bump", "read_plugin_version_main"),
    ("verify", "main"): ("larch.core.verify_main", "main"),
    ("audit-runs", "preflight"): ("larch.issue.audit_runs", "preflight_main"),
    ("audit-runs", "resolve-prs"): ("larch.issue.audit_runs", "resolve_prs_main"),
    ("audit-runs", "map-runs"): ("larch.issue.audit_runs", "map_runs_main"),
    ("audit-runs", "scan-run"): ("larch.issue.audit_runs", "scan_run_main"),
    ("audit-runs", "compute-counters"): ("larch.issue.audit_runs", "compute_counters_main"),
    ("audit-runs", "title"): ("larch.issue.audit_runs", "title_main"),
    ("audit-runs", "title-match"): ("larch.issue.audit_runs", "title_match_main"),
    ("audit-runs", "pacific-timestamp"): ("larch.issue.audit_runs", "pacific_timestamp_main"),
    ("audit-runs", "close-priors"): ("larch.issue.audit_runs", "close_priors_main"),
    ("combine-issues", "fetch"): ("larch.issue.combine_issues", "fetch_main"),
    ("combine-issues", "fetch-deps"): ("larch.issue.combine_issues", "fetch_deps_main"),
    ("combine-issues", "plan-inherited"): ("larch.issue.combine_issues", "plan_inherited_main"),
    ("combine-issues", "close-eligible"): ("larch.issue.combine_issues", "close_eligible_main"),
    ("combine-issues", "list-open"): ("larch.issue.combine_issues", "list_open_main"),
    ("combine-issues", "prose-audit"): ("larch.issue.combine_issues", "prose_audit_main"),
    ("combine-issues", "plan-audit"): ("larch.issue.combine_issues", "plan_audit_main"),
    ("combine-issues", "apply"): ("larch.issue.combine_issues", "apply_main"),
    ("combine-issues", "close-sources"): ("larch.issue.combine_issues", "close_sources_main"),
    ("combine-issues", "close-stale"): ("larch.issue.combine_issues", "close_stale_main"),
    ("deps", "resolve-repo"): ("larch.issue.deps_audit", "resolve_repo_main"),
    ("deps", "fetch"): ("larch.issue.deps_audit", "fetch_main"),
    ("deps", "explicit-refs"): ("larch.issue.deps_audit", "explicit_refs_main"),
    ("deps", "write-proposals"): ("larch.issue.deps_audit", "write_proposals_main"),
    ("deps", "plan"): ("larch.issue.deps_audit", "plan_main"),
    ("deps", "apply"): ("larch.issue.deps_audit", "apply_main"),
    ("analyze-issues", "fetch"): ("larch.issue.analyze_issues", "fetch_main"),
    ("analyze-issues", "run"): ("larch.issue.analyze_issues", "run_main"),
    ("analyze-issues", "analyze"): ("larch.issue.analyze_issues", "analyze_main"),
    ("analyze-issues", "render-chart"): ("larch.rendering.render_chart", "render_chart_main"),
    ("rejected-analysis", "prepare"): ("larch.issue.rejected_analysis", "prepare_main"),
    ("rejected-analysis", "ingest-verdict"): ("larch.issue.rejected_analysis", "ingest_verdict_main"),
    ("rejected-analysis", "finalize"): ("larch.issue.rejected_analysis", "finalize_main"),
    ("rejected-analysis", "record"): ("larch.issue.rejected_analysis", "record_main"),
    ("blocker", "all-open"): ("larch.issue.blocker", "all_open_blockers_main"),
    ("tracking-issue", "read"): ("larch.issue.tracking_issue", "read_main"),
    ("tracking-issue", "create-issue"): ("larch.issue.tracking_issue", "create_issue_main"),
    ("tracking-issue", "append-comment"): ("larch.issue.tracking_issue", "append_comment_main"),
    ("tracking-issue", "rename"): ("larch.issue.tracking_issue", "rename_main"),
    ("tracking-issue", "mark-false-positive"): ("larch.issue.tracking_issue", "mark_false_positive_main"),
    ("tracking-issue", "upsert-summary"): ("larch.issue.tracking_issue", "upsert_summary_main"),
    ("implement", "step2-dispatch"): ("larch.implement.implement_dispatch", "step2_dispatch_main"),
    ("implement", "run-dispatch"): ("larch.implement.implement_dispatch", "run_dispatch_main"),
    ("implement", "recovery-paths"): ("larch.implement.implement_dispatch", "recovery_paths_main"),
    ("implement", "commit"): ("larch.implement.implement_dispatch", "commit_main"),
    ("implement", "commit-route"): ("larch.implement.implement_dispatch", "commit_route_main"),
    ("implement", "checks-commit-route"): ("larch.implement.implement_dispatch", "checks_commit_route_main"),
    ("implement", "checks-step5-resume"): ("larch.implement.implement_dispatch", "checks_step5_resume_main"),
    ("implement", "clone-tag"): ("larch.implement.implement_dispatch", "clone_tag_main"),
    ("implement", "kill-active-leg"): ("larch.implement.implement_dispatch", "kill_active_leg_main"),
    ("implement", "normalize-coder-scout"): ("larch.implement.implement_dispatch", "normalize_coder_scout_main"),
    ("implement", "step-0-bootstrap"): ("larch.implement.implement_dispatch", "step0_bootstrap_main"),
    ("implement", "step-0-degraded-gate"): ("larch.implement.implement_dispatch", "step0_degraded_gate_main"),
    ("implement", "step-2-entry"): ("larch.implement.implement_dispatch", "step2_entry_main"),
    ("implement", "step-2-post-dispatch"): ("larch.implement.implement_dispatch", "step2_post_dispatch_main"),
    ("implement", "step-5-review"): ("larch.implement.implement_dispatch", "step5_review_main"),
    ("implement", "step-5-resume"): ("larch.implement.implement_dispatch", "step5_resume_main"),
    ("implement", "step-6-entry"): ("larch.implement.implement_dispatch", "step6_entry_main"),
    ("implement", "step-8-python-guard"): ("larch.implement.implement_dispatch", "step8_python_guard_main"),
    ("implement", "step-8-seed-initial"): ("larch.implement.implement_dispatch", "step8_seed_initial_main"),
    ("implement", "step-8-ship"): ("larch.implement.implement_dispatch", "step8_ship_main"),
    ("implement", "step-8-oos-checkpoint"): ("larch.implement.implement_dispatch", "step8_oos_checkpoint_main"),
    ("implement", "step-18-gate-finalize"): ("larch.implement.implement_dispatch", "step_18_gate_finalize_main"),
    ("implement", "run-step-checks"): ("larch.implement.implement_dispatch", "run_step_checks_main"),
    ("architectural-guidelines", "read"): ("larch.core.architectural_guidelines", "read_main"),
    ("architectural-guidelines", "present-note"): ("larch.core.architectural_guidelines", "present_note_main"),
    ("architectural-guidelines", "materialize-diff"): ("larch.core.architectural_guidelines", "materialize_diff_main"),
    ("architectural-guidelines", "prepare"): ("larch.core.architectural_guidelines", "prepare_main"),
    ("architectural-guidelines", "write-staged-assessment"): ("larch.core.architectural_guidelines", "write_staged_assessment_main"),
    ("architectural-guidelines", "pin-note-from-staged"): ("larch.core.architectural_guidelines", "pin_note_from_staged_main"),
    ("architectural-guidelines", "invalidate"): ("larch.core.architectural_guidelines", "invalidate_main"),
    ("architectural-guidelines", "persist-design-assessment"): ("larch.core.architectural_guidelines", "persist_design_assessment_main"),
    ("issue", "state"): ("larch.issue.issue_query", "issue_state_main"),
    ("issue", "info"): ("larch.issue.issue_query", "issue_info_main"),
    ("issue", "context"): ("larch.issue.issue_query", "issue_context_main"),
    ("plan-block", "read"): ("larch.issue.issue_wire", "plan_block_read_main"),
    ("plan-block", "write"): ("larch.issue.issue_wire", "plan_block_write_main"),
    ("plan-block", "strip-body"): ("larch.issue.issue_wire", "plan_block_strip_body_main"),
    ("named-block", "write"): ("larch.issue.issue_wire", "named_block_write_main"),
    ("plan", "scope-paths"): ("larch.issue.issue_wire", "plan_scope_paths_main"),
    ("plan", "parse-commands"): ("larch.design.plan_quality", "parse_plan_commands_main"),
    ("plan", "validate-commands"): ("larch.design.plan_quality", "validate_plan_commands_main"),
    ("plan", "validate"): ("larch.design.plan_quality", "validate_plan_main"),
    ("plan", "check-size"): ("larch.design.plan_quality", "check_plan_size_main"),
    ("plan", "revise-waterfall"): ("larch.design.plan_quality", "revise_plan_with_waterfall_main"),
    ("plan", "auto-fix-commands"): ("larch.design.plan_quality", "auto_fix_plan_commands_main"),
    ("plan", "validator-autofix"): ("larch.design.plan_quality", "validator_autofix_main"),
    ("plan", "optional-trailers"): ("larch.design.plan_quality", "optional_trailers_main"),
    ("plan", "compose-goals-test"): ("larch.design.plan_quality", "compose_plan_goals_test_main"),
    ("plan", "step1-log"): ("larch.design.design_step_log", "step1_log_main"),
    ("plan-review", "run"): ("larch.review.plan_review", "run_main"),
    ("plan-review", "normalize-status"): ("larch.review.plan_review", "normalize_step3_status_main"),
    ("plan-review", "panel-dispatch"): ("larch.review.plan_review_panel", "dispatch_panel_main"),
    ("plan-review", "voter-dispatch"): ("larch.review.plan_review_panel", "dispatch_voters_main"),
    ("plan-review", "tally"): ("larch.review.plan_review", "tally_main"),
    ("plan-review", "emit"): ("larch.review.plan_review", "emit_main"),
    ("plan-review", "finalize"): ("larch.review.plan_review", "finalize_main"),
    ("plan-review", "preview"): ("larch.review.plan_review", "preview_main"),
    ("plan-review", "gate-b-counts"): ("larch.review.plan_review", "gate_b_counts_main"),
    ("plan-review", "gate-b-finding-line"): ("larch.review.plan_review", "gate_b_finding_line_main"),
    ("plan-review", "gate-b-dedup"): ("larch.review.plan_review", "gate_b_dedup_main"),
    ("plan-review", "persist-retally-env"): ("larch.review.plan_review", "persist_retally_env_main"),
    ("plan-review", "persist-round-start-s"): ("larch.review.plan_review", "persist_round_start_s_main"),
    ("plan-review", "step3-state"): ("larch.review.plan_review", "step3_state_main"),
    ("plan-review", "record-round-timing"): ("larch.review.plan_review", "record_round_timing_main"),
    ("plan-review", "continuation"): ("larch.review.plan_review", "continuation_main"),
    ("plan-review", "prelaunch-failure"): ("larch.review.plan_review", "prelaunch_failure_main"),
    ("plan-review", "step3-entry"): ("larch.review.plan_review", "step3_entry_main"),
    ("plan-review", "step3-mav"): ("larch.review.plan_review", "step3_mav_main"),
    ("plan-review", "step3b-entry"): ("larch.review.plan_review", "step3b_entry_main"),
    ("plan-review", "step3b-sanitize"): ("larch.review.plan_review", "step3b_sanitize_main"),
    ("plan-review", "step3b-tail"): ("larch.review.plan_review", "step3b_tail_main"),
    ("plan-review", "emit-rejected"): ("larch.review.plan_review", "emit_rejected_main"),
    ("plan-review", "step35"): ("larch.review.plan_review", "step35_main"),
    ("plan-review", "step35-settle"): ("larch.review.plan_review", "step35_settle_main"),
    ("plan-review", "json-get-bool"): ("larch.review.plan_review", "json_get_bool_main"),
    ("plan-review", "round-artifact-included"): ("larch.review.plan_review", "round_artifact_included_main"),
    ("plan-review", "round-revise-artifact-included"): ("larch.review.plan_review", "round_revise_artifact_included_main"),
    ("plan-review", "round-revise-artifact-excluded"): ("larch.review.plan_review", "round_revise_artifact_excluded_main"),
    ("plan-review", "drift-baseline"): ("larch.review.plan_review", "drift_baseline_main"),
    ("issue", "title-eligibility"): ("larch.issue.issue_wire", "issue_title_eligibility_main"),
    ("issue", "title-archival-jq"): ("larch.issue.issue_wire", "issue_title_archival_jq_main"),
    ("issue", "insert-signal-marker"): ("larch.issue.issue_wire", "issue_insert_signal_marker_main"),
    ("untrusted", "file-block"): ("larch.issue.issue_wire", "untrusted_file_block_main"),
    ("untrusted", "content-block"): ("larch.issue.issue_wire", "untrusted_content_block_main"),
    ("untrusted", "redact-stream"): ("larch.issue.issue_wire", "untrusted_redact_stream_main"),
    ("untrusted", "xml-escape-attr"): ("larch.issue.issue_wire", "untrusted_xml_escape_attr_main"),
    ("lint", "p3119-fence-absence"): ("larch.issue.issue_wire", "lint_p3119_main"),
    ("lint", "duplicate-code"): ("larch.lint.duplicate_code", "duplicate_code_main"),
    ("issue", "parse-input"): ("larch.issue.issue_create", "parse_input_main"),
    ("issue", "create-one"): ("larch.issue.issue_create", "create_one_main"),
    ("issue", "allocate-candidates"): ("larch.issue.issue_create", "allocate_candidates_main"),
    ("issue", "add-blocked-by"): ("larch.issue.issue_create", "add_blocked_by_main"),
    ("issue", "fetch-issue-details"): ("larch.issue.issue_create", "fetch_issue_details_main"),
    ("issue", "list-issues"): ("larch.issue.issue_create", "list_issues_main"),
    ("issue", "write-sentinel"): ("larch.issue.issue_create", "write_sentinel_main"),
    ("issue", "cleanup-failed"): ("larch.issue.issue_create", "cleanup_failed_main"),
    ("block-issue", "add-blocked-by"): ("larch.issue.issue_block", "add_blocked_by_main"),
    ("alias", "generate"): ("larch.core.alias_skill", "generate_main"),
    ("alias", "resolve-target"): ("larch.core.alias_skill", "resolve_target_main"),
    ("cleanup", "run"): ("larch.core.cleanup_skill", "run_main"),
    ("upgrade-larch", "run"): ("larch.core.upgrade_larch", "run_main"),
    ("upgrade-larch", "release-step7-root"): ("larch.core.upgrade_larch", "release_step7_root_main"),
    ("upgrade-larch", "sparse-dirs"): ("larch.core.upgrade_larch", "sparse_dirs_main"),
    ("forked-repo", "setup"): ("larch.core.forked_repo", "setup_main"),
    ("design", "parse-argv"): ("larch.design.design_argv", "parse_argv_main"),
    ("design", "step0-parse"): ("larch.design.design_lifecycle", "step0_parse_main"),
    ("design", "step0-session"): ("larch.design.design_lifecycle", "step0_session_main"),
    ("design", "step0-route"): ("larch.design.design_lifecycle", "step0_route_main"),
    ("design", "step0-clarify-hard-halt"): ("larch.design.design_lifecycle", "step0_clarify_hard_halt_main"),
    ("design", "step0-init"): ("larch.design.design_lifecycle", "step0_init_main"),
    ("design", "step0-abort-cleanup"): ("larch.design.design_lifecycle", "step0_abort_cleanup_main"),
    ("design", "step0-ap-continue"): ("larch.design.design_lifecycle", "step0_ap_continue_main"),
    ("design", "step0c"): ("larch.design.design_lifecycle", "step0c_main"),
    ("design", "step1d5"): ("larch.design.design_lifecycle", "step1d5_main"),
    ("design", "step1d7"): ("larch.design.design_lifecycle", "step1d7_main"),
    ("design", "step1e-reentry"): ("larch.design.design_lifecycle", "step1e_reentry_main"),
    ("design", "route"): ("larch.design.design_lifecycle", "route_main"),
    ("design", "init-runparams"): ("larch.design.design_lifecycle", "init_runparams_main"),
    ("design", "driver"): ("larch.design.design_lifecycle", "driver_main"),
    ("design", "read-result-env"): ("larch.design.design_lifecycle", "read_result_env_main"),
    ("design", "stage-terminal-state"): ("larch.design.design_lifecycle", "stage_terminal_state_main"),
    ("design", "failure-report"): ("larch.design.design_lifecycle", "failure_report_main"),
    ("design", "step-final-summary"): ("larch.design.design_lifecycle", "step_final_summary_main"),
    ("design", "step2b-drafter"): ("larch.design.design_lifecycle", "step2b_drafter_main"),
    ("design", "step2b-postplan"): ("larch.design.design_lifecycle", "step2b_postplan_main"),
    ("design", "dialectic-gatec"): ("larch.design.design_dialectic", "gatec_main"),
    ("design", "dialectic-manual"): ("larch.design.design_dialectic", "manual_main"),
    ("design", "dialectic-write-candidates"): ("larch.design.design_dialectic", "write_candidates_main"),
    ("design", "dialectic-promote-candidates"): ("larch.design.design_dialectic", "promote_candidates_main"),
    ("design", "dialectic-validate-candidates"): ("larch.design.design_dialectic", "validate_candidates_main"),
    ("design", "dialectic-clear-stale"): ("larch.design.design_dialectic", "clear_stale_main"),
    ("design", "step2b5"): ("larch.design.design_lifecycle", "step2b5_main"),
    ("design", "step5b-prepare"): ("larch.design.design_lifecycle", "step5b_prepare_main"),
    ("design", "step5b-annotate"): ("larch.design.design_lifecycle", "step5b_annotate_main"),
    ("design", "step5c"): ("larch.design.design_lifecycle", "step5c_main"),
    ("design", "step6"): ("larch.design.design_lifecycle", "step6_main"),
    ("design", "step6-prelude"): ("larch.design.design_lifecycle", "step6_prelude_main"),
    ("design", "step6-cleanup"): ("larch.design.design_lifecycle", "step6_cleanup_main"),
    ("design", "postplan-emit"): ("larch.design.design_postplan", "postplan_emit_main"),
    ("design", "publish"): ("larch.design.design_publish", "publish_main"),
    ("design", "clarify"): ("larch.design.clarify", "design_clarify_main"),
    ("design", "log-publish"): ("larch.design.design_log_publish_flow", "log_publish_main"),
    ("design", "pause-save"): ("larch.design.design_pause", "pause_save_main"),
    ("design", "pause-load"): ("larch.design.design_pause", "pause_load_main"),
    ("design", "render-final-summary"): ("larch.design.design_summary", "render_final_summary_main"),
    ("design", "file-oos-prepare"): ("larch.design.design_oos", "file_oos_prepare_main"),
    ("design", "file-oos-annotate"): ("larch.design.design_oos", "file_oos_annotate_main"),
    ("decompose", "prepare"): ("larch.design.decompose", "prepare_main"),
    ("decompose", "annotate"): ("larch.design.decompose", "annotate_main"),
    ("decompose", "close-original"): ("larch.design.decompose", "close_original_main"),
    ("decompose", "panel-dispatch"): ("larch.design.decompose", "panel_dispatch_main"),
    ("decompose", "aggregate"): ("larch.design.decompose", "aggregate_main"),
    ("scout", "dynamic-archetypes"): ("larch.design.plan_scout", "dynamic_archetypes_main"),
    ("scout", "plan-archetypes"): ("larch.design.plan_scout", "plan_archetypes_main"),
    ("scout", "filter-manifest"): ("larch.design.plan_scout", "filter_manifest_main"),
    ("external-defaults", "role"): ("larch.core.external_defaults", "role_main"),
    ("external-defaults", "resolve-vendor"): ("larch.core.external_defaults", "resolve_vendor_main"),
    ("external-defaults", "docs"): ("larch.core.external_defaults", "docs_main"),
    ("research", "validate-citations"): ("larch.research.research", "validate_citations_main"),
    ("research", "render-findings-batch"): ("larch.research.research", "render_findings_batch_main"),
    ("research", "run-planner"): ("larch.research.research", "run_research_planner_main"),
    ("research", "banner"): ("larch.research.research", "compute_research_banner_main"),
    ("eval", "validate-research-output"): ("larch.research.research_eval", "validate_research_output_main"),
    ("eval", "research"): ("larch.research.research_eval", "eval_research_main"),
    ("render", "specialist"): ("larch.rendering.rendering", "render_specialist_main"),
    ("render", "reviewer"): ("larch.rendering.rendering", "render_reviewer_main"),
    ("render", "lane-status"): ("larch.rendering.rendering", "render_lane_status_main"),
    ("render", "voter"): ("larch.rendering.rendering", "render_voter_main"),
    ("render", "plan-review"): ("larch.rendering.rendering", "render_plan_review_main"),
    ("render", "scope-anchor"): ("larch.rendering.rendering", "render_scope_anchor_main"),
    ("render", "findings-view"): ("larch.rendering.rendering", "render_findings_view_main"),
    ("voter-calibration", "snapshot"): ("larch.review.voting", "voter_calibration_snapshot_main"),
    ("scope-anchor", "relay-allowed"): ("larch.rendering.rendering", "scope_anchor_relay_allowed_main"),
    ("scope-anchor", "validate"): ("larch.rendering.rendering", "scope_anchor_validate_main"),
    ("scope-anchor", "retally-handoff"): ("larch.rendering.rendering", "scope_anchor_retally_handoff_main"),
    ("scope-anchor", "design-handoff"): ("larch.rendering.rendering", "scope_anchor_design_handoff_main"),
    # review panel_hard topology authority: specialists per vendor, Cursor + Codex.
    ("review", "gather-context"): ("larch.review.review_pipeline", "gather_context_main"),
    ("review", "dispatch-panel"): ("larch.review.review_pipeline", "dispatch_panel_main"),
    ("review", "collect-findings"): ("larch.review.review_pipeline", "collect_findings_main"),
    ("review", "check-reviewer-failure-threshold"): (
        "larch.review.review_pipeline",
        "check_reviewer_failure_threshold_main",
    ),
    ("review", "aggregate-findings"): ("larch.review.review_aggregate", "aggregate_findings_main"),
    ("review", "prune-nit-findings"): ("larch.review.review_aggregate", "prune_nit_findings_main"),
    ("review", "tally-code-votes"): ("larch.review.review_tally", "tally_code_votes_main"),
    ("review", "emit-tally"): ("larch.review.review_tally", "emit_tally_main"),
    ("review", "log-phase"): ("larch.review.review_tally", "log_phase_main"),
    ("review", "core"): ("larch.review.review_pipeline", "review_core_main"),
    ("review", "reviewer-prune"): ("larch.review.review_pipeline", "reviewer_prune_main"),
    ("review", "compose-findings"): ("larch.review.compose_review", "compose_findings_main"),
    ("review-and-fix", "apply-findings"): ("larch.review.review_and_fix", "apply_findings"),
    ("review-and-fix", "step5"): ("larch.review.review_and_fix", "step5"),
    ("review-and-fix", "check-changes"): ("larch.review.review_and_fix", "check_changes"),
    ("review-and-fix", "commit-fixes"): ("larch.review.review_and_fix", "commit_fixes"),
    ("review-and-fix", "write-rejected"): ("larch.review.review_and_fix", "write_rejected"),
    ("review-and-fix", "record-round-timing"): ("larch.review.review_and_fix", "record_round_timing"),
    ("review-and-fix", "write-self-review-tally"): ("larch.review.review_and_fix", "write_self_review_tally"),
    ("review-and-fix", "write-pre-self-review-snapshot"): ("larch.review.review_and_fix", "write_pre_self_review_snapshot"),
    ("mermaid", "sanitize"): ("larch.rendering.rendering", "mermaid_sanitize_main"),
    ("diagrams", "upsert"): ("larch.rendering.rendering", "diagrams_upsert_main"),
    ("generate", "code-reviewer-agent"): ("larch.rendering.rendering", "generate_code_reviewer_agent_main"),
    ("generate", "reviewer-plan-fidelity-agent"): ("larch.rendering.rendering", "generate_reviewer_plan_fidelity_agent_main"),
    ("generate", "reviewer-code-robustness-agent"): ("larch.rendering.rendering", "generate_reviewer_code_robustness_agent_main"),
    ("generate", "reviewer-security-structure-tests-agent"): ("larch.rendering.rendering", "generate_reviewer_security_structure_tests_agent_main"),
    ("generate", "pre-rendered-reviewer-prompts"): ("larch.rendering.rendering", "generate_pre_rendered_reviewer_prompts_main"),
    ("generate", "codex-implementer"): ("larch.rendering.rendering", "generate_codex_implementer_main"),
    ("generate", "cursor-implementer"): ("larch.rendering.rendering", "generate_cursor_implementer_main"),
    ("generate", "topology-docs"): ("larch.rendering.rendering", "generate_topology_docs_main"),
    ("generate", "check"): ("larch.rendering.rendering", "generate_check_main"),
    ("gantt", "render"): ("larch.rendering.gantt", "gantt_render_main"),
    ("ship", "design-log"): ("larch.design.design_log_ship", "main"),
    ("ship", "design-log-sweep"): ("larch.design.design_log_ship", "sweep_main"),
    ("ship", "pr"): ("larch.implement.ship", "main"),
    ("ship", "pre-driver"): ("larch.implement.implement_dispatch", "ship_pre_driver_main"),
    ("ship", "route-exit"): ("larch.implement.implement_dispatch", "ship_route_exit_main"),
    ("ship", "seed-initial-state"): ("larch.implement.ship", "seed_initial_state_main"),
    ("clarify", "state"): ("larch.design.clarify", "clarify_state_main"),
    ("clarify", "comment-fetch"): ("larch.design.clarify", "clarify_comment_fetch_main"),
    ("clarify", "comment-post"): ("larch.design.clarify", "clarify_comment_post_main"),
    ("clarify", "label"): ("larch.design.clarify", "clarify_label_main"),
    ("progress", "report"): ("larch.report.progress_report", "report_main"),
    ("progress", "render-phase-detail"): ("larch.report.progress_report", "render_phase_detail_main"),
    ("progress", "write-design-round-meta"): ("larch.report.progress_report", "write_design_round_meta_main"),
    ("progress", "write-implement-round-meta"): ("larch.report.progress_report", "write_implement_round_meta_main"),
    ("gc-run-logs", "run"): ("larch.report.gc_run_logs", "run_main"),
    ("report-tokens", "analyze"): ("larch.report.report_tokens_cli", "main"),
    ("token", "mark"): ("larch.report.tokens", "token_mark_main"),
    ("token", "record-vendor"): ("larch.report.tokens", "token_record_vendor_main"),
    ("token", "dump"): ("larch.report.tokens", "token_dump_main"),
    ("token", "report"): ("larch.report.tokens", "token_report_main"),
    ("token", "check-budget"): ("larch.report.tokens", "token_check_budget_main"),
    ("token", "claude-source"): ("larch.report.tokens", "token_claude_source_main"),
    ("token", "lane-write"): ("larch.report.tokens", "token_lane_write_main"),
    ("token", "lane-report"): ("larch.report.tokens", "token_lane_report_main"),
    ("token", "append-record"): ("larch.report.tokens", "token_append_record_main"),
    ("token", "record-vendor-sidecar"): ("larch.report.tokens", "token_record_vendor_sidecar_main"),
    ("token", "cost"): ("larch.report.tokens", "token_cost_main"),
    ("token", "render-cost-line"): ("larch.report.tokens", "token_render_cost_line_main"),
    ("token", "compute-pr-line-counts"): ("larch.report.tokens", "compute_pr_line_counts_main"),
    ("token", "compute-pr-lines"): ("larch.report.tokens", "compute_pr_lines_main"),
    ("token", "measure-md-cost"): ("larch.report.tokens", "measure_md_cost_main"),
    ("token", "measure-ngram-duplication"): ("larch.report.tokens", "measure_ngram_duplication_main"),
    ("token", "measure-references-heatmap"): ("larch.report.tokens", "measure_references_heatmap_main"),
    ("token", "measure-realized-cost"): ("larch.report.tokens", "measure_realized_cost_main"),
    ("timing", "mark"): ("larch.report.timing", "timing_mark_main"),
    ("timing", "record-vendor-task"): ("larch.report.timing", "timing_record_vendor_task_main"),
    ("timing", "record-round"): ("larch.report.timing", "timing_record_round_main"),
    ("timing", "dump"): ("larch.report.timing", "timing_dump_main"),
    ("timing", "report"): ("larch.report.timing", "timing_report_main"),
    ("timing", "harness-mark"): ("larch.report.timing", "timing_harness_mark_main"),
    ("timing", "telemetry-mark"): ("larch.report.timing", "timing_telemetry_mark_main"),
    ("timing", "task-kinds"): ("larch.report.timing", "timing_task_kinds_main"),
    ("lint", "retired-scripts"): ("larch.lint.migration_lint", "main"),
    ("lint", "literal-counts"): ("larch.lint.lint_literal_counts", "main"),
    ("lint", "no-raw-stderr-after-quiet-init"): (
        "larch.lint.lint_no_raw_stderr_after_quiet_init",
        "main",
    ),
    ("lint", "topology-rule-paths"): ("larch.lint.check_topology_rule_paths", "main"),
    ("lint", "mermaid-fences"): ("larch.lint.lint_mermaid_fences", "main"),
    ("lint", "skill-md-flag-signature"): ("larch.lint.lint_skill_md_flag_signature", "main"),
    ("lint", "readability-preamble"): ("larch.lint.lint_readability_preamble", "main"),
    ("lint", "gh-body-inline"): ("larch.lint.lint_gh_body_inline", "main"),
    ("lint", "complexity-baseline"): ("larch.lint.lint_complexity_baseline", "main"),
    ("lint", "keyword-only"): ("larch.lint.lint_keyword_only", "main"),
    ("lint", "subprocess-via-runner"): ("larch.lint.lint_subprocess_via_runner", "main"),
    ("lint", "env-via-config-constant"): ("larch.lint.lint_env_via_config_constant", "main"),
    ("lint", "pylint-shard"): ("larch.lint.pylint_sharding", "main"),
    ("lint", "codex-exec-auth"): ("larch.lint.lint_codex_exec_auth", "main"),
    ("lint", "consecutive-bash"): ("larch.lint.lint_consecutive_bash", "main"),
    ("lint", "skill-invocations"): ("larch.lint.lint_skill_invocations", "main"),
    ("lint", "run-log-run-id"): ("larch.lint.lint_run_log_run_id", "main"),
    ("voting", "findings-classification-header"): ("larch.review.voting", "findings_classification_header_main"),
    ("voting", "code-review-classification-header"): ("larch.review.voting", "code_review_classification_header_main"),
    ("voting", "vote-for-id"): ("larch.review.voting", "vote_for_id_main"),
    ("voting", "reviewer-for-block"): ("larch.review.voting", "reviewer_for_block_main"),
    ("voting", "is-security-block"): ("larch.review.voting", "is_security_block_main"),
    ("voting", "accept-finding"): ("larch.review.voting", "accept_finding_main"),
    ("voting", "classify-result"): ("larch.review.voting", "classify_result_main"),
    ("voting", "panel-tier"): ("larch.review.voting", "panel_tier_main"),
    ("voting", "split-ballot"): ("larch.review.voting", "split_ballot_main"),
    ("voting", "parse-judge-vote"): ("larch.review.voting", "parse_judge_vote_main"),
    ("voting", "parse-rate-check"): ("larch.review.voting", "parse_rate_check_main"),
    ("voting", "parse-rate-retry"): ("larch.review.voting", "parse_rate_retry_main"),
    ("voting", "parse-rate-diag-matches"): ("larch.review.voting", "parse_rate_diag_matches_main"),
    ("voting", "effective-judges"): ("larch.review.voting", "effective_judges_main"),
    ("voting", "degraded-warning"): ("larch.review.voting", "degraded_warning_main"),
    ("voting", "voter-status-block"): ("larch.review.voting", "voter_status_block_main"),
    ("voting", "write-tally"): ("larch.review.voting", "write_tally_main"),
    ("voting", "compose-tally-record"): ("larch.review.voting", "compose_tally_record_main"),
    ("voting", "false-positive-match"): ("larch.review.voting", "false_positive_match_main"),
    ("voting", "file-line-regex"): ("larch.review.voting", "file_line_regex_main"),
    ("voting", "ballot-parse"): ("larch.review.voting", "ballot_parse_main"),
    ("voting", "tally-vote"): ("larch.review.voting", "tally_vote_main"),
    ("voting", "scoreboard"): ("larch.review.voting", "scoreboard_main"),
    ("lint", "focus-area-enum"): ("larch.review.voting", "lint_focus_area_enum_main"),
    ("run-log", "init"): ("larch.report.run_logs", "larch_log_init_main"),
    ("run-log", "write"): ("larch.report.run_logs", "larch_log_write_main"),
    ("run-log", "write-round"): ("larch.report.run_logs", "larch_log_write_round_main"),
    ("run-log", "append"): ("larch.report.run_logs", "larch_log_append_main"),
    ("run-log", "exists"): ("larch.report.run_logs", "larch_log_exists_main"),
    ("run-log", "commit"): ("larch.report.run_logs", "larch_log_commit_main"),
    ("run-log", "manifest"): ("larch.report.run_logs", "larch_log_manifest_main"),
    ("run-log", "flush"): ("larch.report.run_logs", "larch_log_flush_main"),
    ("run-log", "refresh"): ("larch.report.run_logs", "refresh_run_logs_main"),
    ("run-log", "capture-transcript"): ("larch.report.run_logs", "capture_transcript_main"),
    ("run-log", "render-session-transcript"): ("larch.rendering.render_session_transcript", "main"),
    ("run-log", "cleanup-implement-logs"): ("larch.report.cleanup_implement_logs", "main"),
    ("run-log", "retro-v3-sweep"): ("larch.report.retro_v3_sweep", "main"),
    ("run-log", "verify-completeness"): ("larch.report.run_logs", "verify_completeness_main"),
    ("run-log", "append-failure"): ("larch.report.run_logs", "append_failure_main"),
    ("run-log", "append-entry"): ("larch.report.run_logs", "append_entry_main"),
    ("run-log", "publish-breadcrumbs"): ("larch.report.run_logs", "publish_breadcrumbs_main"),
    ("redact", "secrets"): ("larch.core.redact", "main_secrets"),
    ("redact", "tmpdir-paths"): ("larch.core.redact", "main_tmpdir_paths"),
    ("redact", "scrub-log-secrets"): ("larch.core.redact", "main_scrub_log_secrets"),
    ("redact", "scrub-submodule-paths"): ("larch.core.redact", "main_scrub_submodule_paths"),
    ("verify", "skill-called"): ("larch.core.verify_skill", "main"),
    ("oos", "materialize-manifest"): ("larch.issue.file_oos", "materialize_manifest_main"),
    ("oos", "file"): ("larch.issue.oos_filer", "cmd_file"),
    ("oos", "issue-cap"): ("larch.issue.file_oos", "issue_cap_main"),
    ("oos", "file-conflict-deps"): ("larch.issue.file_oos", "file_conflict_deps_main"),
    ("oos", "disposition-gate"): ("larch.issue.file_oos", "disposition_gate_main"),
    ("oos", "disposition-checkpoint"): ("larch.issue.file_oos", "disposition_checkpoint_main"),
    ("execution-issues", "append"): ("larch.issue.execution_issues", "append_execution_issue_main"),
    ("execution-issues", "flush"): ("larch.issue.execution_issues", "flush_execution_issues_main"),
    ("execution-issues", "flush-safety-net"): ("larch.issue.execution_issues", "flush_execution_issues_safety_net_main"),
    ("execution-issues", "refresh"): ("larch.issue.execution_issues", "refresh_execution_issues_main"),
    ("stall-recovery", "init-attempts"): ("larch.state.stall_recovery", "init_attempts_main"),
    ("stall-recovery", "classify"): ("larch.state.stall_recovery", "classify_main"),
    ("stall-recovery", "record-escalation"): ("larch.state.stall_recovery", "record_escalation_main"),
    ("stall-recovery", "normalize-outcome"): ("larch.state.stall_recovery", "normalize_outcome_main"),
    ("stall-recovery", "compose-report"): ("larch.state.stall_recovery", "compose_report_main"),
    ("stall-recovery", "dedup-tier-a-report"): ("larch.state.stall_recovery", "dedup_tier_a_report_main"),
    ("stall-recovery", "normalize-file-failure-report-env"): ("larch.state.stall_recovery", "normalize_file_failure_report_env_main"),
    ("stall-recovery", "normalize-issue-env"): ("larch.state.stall_recovery", "normalize_issue_env_main"),
    ("stall-recovery", "validate-token"): ("larch.state.stall_recovery", "validate_token_main"),
    ("stall-recovery", "validate-terminal-state"): ("larch.state.stall_recovery", "validate_terminal_state_main"),
    ("stall-recovery", "validate-tier-b-public-file"): ("larch.state.stall_recovery", "validate_tier_b_public_file_main"),
    ("stall-recovery", "populate-sensitive-corpus"): ("larch.state.stall_recovery", "populate_sensitive_corpus_main"),
    ("stall-recovery", "chat-print"): ("larch.state.stall_recovery", "chat_print_main"),
    ("stall-recovery", "record-attempt"): ("larch.state.stall_recovery", "record_attempt_main"),
    ("stall-recovery", "retry-policy"): ("larch.state.stall_recovery", "retry_policy_main"),
    ("stall-recovery", "is-larch-dev-clone"): ("larch.state.stall_recovery", "is_larch_dev_clone_main"),
    ("stall-recovery", "clear-stall"): ("larch.state.stall_recovery", "clear_stall_main"),
    ("stall-recovery", "seed-terminal-state"): ("larch.state.stall_recovery", "seed_terminal_state_main"),
    ("stall-recovery", "lint"): ("larch.state.stall_recovery", "lint_main"),
    ("implement", "step-7a"): ("larch.implement.step_7a", "main"),
    ("implement", "preflight"): ("larch.implement.preflight", "preflight_main"),
    ("implement", "step-16"): ("larch.state.closeout", "step_16_main"),
    ("implement", "step-17"): ("larch.state.closeout", "step_17_main"),
    ("implement", "step-16-16a"): ("larch.state.closeout", "step_16_16a_main"),
    ("implement", "step-16-17"): ("larch.state.closeout", "step_16_17_main"),
    ("implement", "cleanup"): ("larch.state.finalize", "cleanup_main"),
    ("implement-finalize", "postbump"): ("larch.state.finalize", "implement_finalize_postbump_main"),
    ("implement-finalize", "postmerge"): ("larch.state.finalize", "implement_finalize_postmerge_main"),
    ("implement-finalize", "teardown"): ("larch.state.finalize", "implement_finalize_teardown_main"),
    ("final-report", "write"): ("larch.report.final_report", "write_final_report_main"),
    ("final-report", "step18b"): ("larch.report.final_report", "step18b_final_report_main"),
    ("tracking", "post-issue"): ("larch.git.pr_body", "post_tracking_issue_main"),
    ("slack", "issue-announce"): ("larch.git.pr_body", "slack_issue_announce_main"),
    ("diagram", "code-flow"): ("larch.git.pr_body", "generate_code_flow_diagram_main"),
    ("render", "run-summary"): ("larch.git.pr_body", "render_run_summary_main"),
    ("pr", "compose-summary"): ("larch.git.pr_body", "compose_pr_summary_main"),
    ("oos", "serialize"): ("larch.issue.oos", "oos_serialize_main"),
    ("oos", "normalize-header"): ("larch.issue.oos", "oos_normalize_header_main"),
    ("git", "commit"): ("larch.git.git", "commit_main"),
    ("git", "stage"): ("larch.git.git", "stage_main"),
    ("git", "amend-add"): ("larch.git.git", "amend_add_main"),
    ("git", "current-branch"): ("larch.git.git", "current_branch_main"),
    ("git", "branch-info"): ("larch.git.git", "branch_info_main"),
    ("git", "conflict-files"): ("larch.git.git", "conflict_files_main"),
    ("git", "rebase-abort"): ("larch.git.git", "rebase_abort_main"),
    ("git", "rebase-skip"): ("larch.git.git", "rebase_skip_main"),
    ("git", "checkout-ours"): ("larch.git.git", "checkout_ours_main"),
    ("git", "show-stage"): ("larch.git.git", "show_stage_main"),
    ("git", "sync-local-main"): ("larch.git.git", "sync_local_main_main"),
    ("git", "clean-tree"): ("larch.git.git", "clean_tree_main"),
    ("git", "snapshot-untracked"): ("larch.git.git", "snapshot_untracked_main"),
    ("git", "count-commits"): ("larch.git.git", "count_commits_main"),
    ("git", "check-main-sync"): ("larch.git.git", "check_main_sync_main"),
    ("git", "check-remote-branch"): ("larch.git.git", "check_remote_branch_main"),
    ("git", "check-phantom-dirty"): ("larch.git.git", "check_phantom_dirty_main"),
    ("git", "phantom-probe"): ("larch.git.git", "phantom_probe_main"),
    ("push", "branch"): ("larch.git.push", "branch_main"),
    ("push", "force"): ("larch.git.push", "force_main"),
    ("push", "rebase"): ("larch.git.push", "rebase_main"),
    ("push", "checkpoint-probe"): ("larch.git.push", "checkpoint_probe_main"),
    ("pr", "create-branch"): ("larch.git.pr", "create_branch_main"),
    ("pr", "create"): ("larch.git.pr", "create_main"),
    ("pr", "body-update"): ("larch.git.pr", "body_update_main"),
    ("pr", "checks"): ("larch.git.pr", "checks_main"),
    ("pr", "closes-issue"): ("larch.git.pr", "closes_issue_main"),
    ("merge", "pr"): ("larch.git.merge", "pr_main"),
    ("gh", "resolve-repo"): ("larch.git.gh", "resolve_repo_main"),
    ("gh", "remote-repo"): ("larch.git.gh", "remote_repo_main"),
    ("gh", "run-logs"): ("larch.git.gh", "run_logs_main"),
    ("gh", "workflow-path"): ("larch.git.gh", "workflow_path_main"),
    ("ci", "wait"): ("larch.implement.ci", "wait_main"),
    ("ci", "status"): ("larch.implement.ci", "status_main"),
    ("ci", "decide"): ("larch.implement.ci", "decide_main"),
    ("ci", "failed-jobs"): ("larch.implement.ci", "failed_jobs_main"),
    ("ci", "behind-count"): ("larch.implement.ci", "behind_count_main"),
    ("ci", "rerun-failed"): ("larch.implement.ci", "rerun_failed_main"),
    ("session", "setup"): ("larch.state.session_env", "setup_main"),
    ("session", "write-env"): ("larch.state.session_env", "write_env_main"),
    ("session", "read-key"): ("larch.state.session_env", "read_key_main"),
    ("session", "read-keys"): ("larch.state.session_env", "read_keys_main"),
    ("session", "write-design-env"): ("larch.state.session_env", "write_design_env_main"),
    ("session", "validate-design-tmpdir"): ("larch.state.session_env", "validate_design_tmpdir_main"),
    ("session", "write-implement-env"): ("larch.state.session_env", "write_implement_env_main"),
    ("session", "clear-implement-pointer"): ("larch.state.session_env", "clear_implement_pointer_main"),
    ("session", "write-run-params"): ("larch.state.session_env", "write_run_params_main"),
    ("session", "write-id"): ("larch.state.session_env", "write_id_main"),
    ("session", "persist-run-flags"): ("larch.state.session_env", "persist_run_flags_main"),
    ("session", "restore-finalize-state"): ("larch.state.session_env", "restore_finalize_state_main"),
    ("session", "cleanup-tmpdir"): ("larch.state.session_env", "cleanup_tmpdir_main"),
    ("session", "kill-background-processes"): ("larch.state.finalize", "kill_background_processes_main"),
    ("session", "local-cleanup"): ("larch.state.session_env", "local_cleanup_main"),
    ("session", "entry-gate"): ("larch.state.session_env", "entry_gate_main"),
    ("session", "resolve-implement-tmpdir"): ("larch.state.session_env", "resolve_implement_tmpdir_main"),
}

# Design-lifecycle + plan step1 entrypoints that emit machine-readable stdout.
# Shared with test_cli.py so the registry-membership test does not re-enumerate
# the same keys (issue #4480 duplicate-code consolidation).
_DESIGN_LIFECYCLE_STDOUT_KEYS: frozenset[tuple[str, str]] = frozenset({
    ("design", "parse-argv"),
    ("design", "step0-parse"),
    ("design", "step0-session"),
    ("design", "step0-route"),
    ("design", "step0-clarify-hard-halt"),
    ("design", "step0-init"),
    ("design", "step0-abort-cleanup"),
    ("design", "step0-ap-continue"),
    ("design", "step0c"),
    ("design", "step1d5"),
    ("design", "step1d7"),
    ("design", "step1e-reentry"),
    ("design", "route"),
    ("design", "init-runparams"),
    ("design", "driver"),
    ("design", "stage-terminal-state"),
    ("design", "failure-report"),
    ("design", "step-final-summary"),
    ("design", "step2b-drafter"),
    ("design", "step2b-postplan"),
    ("design", "step2b5"),
    ("design", "step5b-prepare"),
    ("design", "step5b-annotate"),
    ("design", "step5c"),
    ("design", "step6"),
    ("design", "step6-prelude"),
    ("design", "step6-cleanup"),
    ("design", "postplan-emit"),
    ("design", "publish"),
    ("design", "clarify"),
    ("design", "pause-save"),
    ("design", "pause-load"),
    ("design", "log-publish"),
    ("design", "render-final-summary"),
    ("design", "read-result-env"),
    ("design", "file-oos-prepare"),
    ("design", "file-oos-annotate"),
    ("plan", "step1-log"),
})

_MACHINE_STDOUT_KEYS: frozenset[tuple[str, str]] = frozenset({
    ("checks", "run-relevant"),
    ("checks", "lint-fix"),
    ("checks", "repair-loop"),
    ("checks", "contains-pins"),
    ("residual-bash", "paths"),
    ("upgrade-larch", "sparse-dirs"),
    ("bootstrap", "invoke"),
    ("bootstrap", "parse-routing"),
    ("admission", "gate"),
    ("admission", "preflight"),
    ("admission", "fork-env"),
    ("dirty-tree", "baseline"),
    ("dirty-tree", "checkpoint"),
    ("plan", "validate"),
    ("plan", "validate-commands"),
    ("plan", "check-size"),
    ("plan", "revise-waterfall"),
    ("plan", "auto-fix-commands"),
    ("plan", "validator-autofix"),
    ("plan", "optional-trailers"),
    ("plan", "compose-goals-test"),
    *_DESIGN_LIFECYCLE_STDOUT_KEYS,
    ("plan-review", "run"),
    ("plan-review", "normalize-status"),
    ("plan-review", "panel-dispatch"),
    ("plan-review", "voter-dispatch"),
    ("plan-review", "tally"),
    ("plan-review", "emit"),
    ("plan-review", "finalize"),
    ("plan-review", "preview"),
    ("plan-review", "gate-b-counts"),
    ("plan-review", "gate-b-finding-line"),
    ("plan-review", "gate-b-dedup"),
    ("plan-review", "persist-retally-env"),
    ("plan-review", "persist-round-start-s"),
    ("plan-review", "step3-state"),
    ("plan-review", "record-round-timing"),
    ("plan-review", "continuation"),
    ("plan-review", "prelaunch-failure"),
    ("plan-review", "step3-entry"),
    ("plan-review", "step3-mav"),
    ("plan-review", "step3b-entry"),
    ("plan-review", "step3b-sanitize"),
    ("plan-review", "step3b-tail"),
    ("plan-review", "emit-rejected"),
    ("plan-review", "step35"),
    ("plan-review", "step35-settle"),
    ("plan-review", "json-get-bool"),
    ("review", "gather-context"),
    ("review", "dispatch-panel"),
    ("review", "collect-findings"),
    ("review", "check-reviewer-failure-threshold"),
    ("review", "aggregate-findings"),
    ("review", "prune-nit-findings"),
    ("review", "tally-code-votes"),
    ("review", "emit-tally"),
    ("review", "log-phase"),
    ("review", "core"),
    ("external-defaults", "role"),
    ("external-defaults", "resolve-vendor"),
    ("external-defaults", "docs"),
    ("review", "compose-findings"),
    ("review-and-fix", "apply-findings"),
    ("review-and-fix", "step5"),
    ("review-and-fix", "check-changes"),
    ("review-and-fix", "commit-fixes"),
    ("review-and-fix", "write-rejected"),
    ("review-and-fix", "record-round-timing"),
    ("review-and-fix", "write-self-review-tally"),
    ("review-and-fix", "write-pre-self-review-snapshot"),
    ("oos", "materialize-manifest"),
    ("oos", "file"),
    ("oos", "issue-cap"),
    ("oos", "file-conflict-deps"),
    ("oos", "disposition-gate"),
    ("oos", "disposition-checkpoint"),
    ("ship", "pre-driver"),
    ("ship", "route-exit"),
    ("implement", "commit-route"),
    ("implement", "checks-commit-route"),
    ("implement", "checks-step5-resume"),
    ("implement", "step-8-oos-checkpoint"),
    ("implement", "step-18-gate-finalize"),
    ("execution-issues", "append"),
    ("execution-issues", "flush"),
    ("execution-issues", "refresh"),
    ("stall-recovery", "init-attempts"),
    ("stall-recovery", "classify"),
    ("stall-recovery", "record-escalation"),
    ("stall-recovery", "normalize-outcome"),
    ("stall-recovery", "compose-report"),
    ("stall-recovery", "dedup-tier-a-report"),
    ("stall-recovery", "normalize-file-failure-report-env"),
    ("stall-recovery", "normalize-issue-env"),
    ("stall-recovery", "validate-token"),
    ("stall-recovery", "validate-terminal-state"),
    ("stall-recovery", "validate-tier-b-public-file"),
    ("stall-recovery", "populate-sensitive-corpus"),
    ("stall-recovery", "chat-print"),
    ("stall-recovery", "record-attempt"),
    ("stall-recovery", "retry-policy"),
    ("stall-recovery", "is-larch-dev-clone"),
    ("stall-recovery", "clear-stall"),
    ("stall-recovery", "seed-terminal-state"),
    ("stall-recovery", "lint"),
    ("implement", "step-7a"),
    ("implement", "preflight"),
    ("implement", "step-16"),
    ("implement", "step-17"),
    ("implement", "step-16-16a"),
    ("implement", "step-16-17"),
    ("implement", "cleanup"),
    ("architectural-guidelines", "read"),
    ("architectural-guidelines", "present-note"),
    ("architectural-guidelines", "materialize-diff"),
    ("architectural-guidelines", "prepare"),
    ("architectural-guidelines", "write-staged-assessment"),
    ("architectural-guidelines", "pin-note-from-staged"),
    ("architectural-guidelines", "invalidate"),
    ("architectural-guidelines", "persist-design-assessment"),
    ("implement-finalize", "postbump"),
    ("implement-finalize", "postmerge"),
    ("implement-finalize", "teardown"),
    ("final-report", "write"),
    ("final-report", "step18b"),
    ("tracking", "post-issue"),
    ("slack", "issue-announce"),
    ("diagram", "code-flow"),
    ("render", "run-summary"),
    ("pr", "compose-summary"),
    ("session", "resolve-implement-tmpdir"),
})

_SHIP_PRE_DRIVER_STALLED_JSON = '{"detail":"Python ship driver requires Python 3.11 or newer","failed_run_id":"","ledger_dispatcher":"","ledger_exit_code":null,"ledger_failure_detail_log":"","ledger_phase":"","ledger_ready":false,"ledger_site":"","ledger_step":"","ledger_trigger":"","merge_result":"","needs_user_reason":"","outcome":"STALLED","pr_number":null,"pr_url":""}'
_MIN_SUBCOMMAND_PARTS = 2


def _version_supported(version_info: object) -> bool:
    return tuple(version_info) >= (3, 11)  # type: ignore[arg-type]


def _unsupported_version_exit(args: list[str]) -> int:
    if len(args) >= _MIN_SUBCOMMAND_PARTS and args[0] == "ship" and args[1] == "pre-driver":
        print("ERROR: Python ship driver requires Python 3.11 or newer", file=sys.stderr)
        print(_SHIP_PRE_DRIVER_STALLED_JSON, file=sys.stderr)
        print("NEXT_ACTION=stall")
        return 4
    print(
        "ERROR: larch cli.py requires Python 3.11 or newer",
        file=sys.stderr,
    )
    return 2


def _build_help_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="cli.py",
        description="larch Python runtime dispatcher",
        add_help=True,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    domains: dict[str, list[str]] = {}
    for domain, verb in _REGISTRY:
        domains.setdefault(domain, []).append(verb)
    lines = ["Available subcommands:"]
    lines.extend(
        f"  {domain} {verb}" for domain in sorted(domains) for verb in sorted(domains[domain])
    )
    parser.epilog = "\n".join(lines)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = argv if argv is not None else sys.argv[1:]

    if not _version_supported(sys.version_info):
        return _unsupported_version_exit(args)

    if not args or args[0] in {"-h", "--help"}:
        _build_help_parser().print_help()
        return 0

    domain = args[0]
    if len(args) < 2 or args[1].startswith("-"):  # noqa: PLR2004
        print(
            f"ERROR: missing verb for domain {domain!r}. "
            f"Usage: cli.py <domain> <verb> [args...]",
            file=sys.stderr,
        )
        return 2

    verb = args[1]
    key = (domain, verb)
    if key not in _REGISTRY:
        known = ", ".join(f"{d} {v}" for d, v in sorted(_REGISTRY))
        print(
            f"ERROR: unknown subcommand {domain!r} {verb!r}. "
            f"Known: {known}",
            file=sys.stderr,
        )
        return 2

    module_name, func_name = _REGISTRY[key]
    rest_argv = args[2:]
    if key in _MACHINE_STDOUT_KEYS:
        os.environ["LARCH_QUIET_DISABLE"] = "1"

    try:
        module = importlib.import_module(module_name)
    except ImportError as exc:
        print(f"ERROR: failed to import module {module_name!r}: {exc}", file=sys.stderr)
        return 2

    target_main = getattr(module, func_name, None)
    if target_main is None:
        print(
            f"ERROR: module {module_name!r} has no function {func_name!r}",
            file=sys.stderr,
        )
        return 2

    try:
        return int(target_main(rest_argv))
    except RuntimeError as exc:
        plan_review_mod = sys.modules.get("larch.review.plan_review")
        if plan_review_mod is not None:
            plan_review_error = getattr(plan_review_mod, "PlanReviewError", None)
            if plan_review_error is not None and isinstance(exc, plan_review_error):
                print(f"ERROR: plan-review: {exc}", file=sys.stderr)
                return 1
        raise
