#!/usr/bin/env bash
# /design session env — generated by session_env.py. Do not edit.
export DESIGN_TMPDIR=<TMPDIR>
export SESSION_TMPDIR=<TMPDIR>
export SESSION_ID=7B4FD739-7E04-4F71-8404-07AC3E94D9EC
export REPO=character-ai/larch
export ISSUE_NUMBER=4180
export CODEX_PRESENT=true
export CODEX_AVAILABLE=true
export CURSOR_PRESENT=true
export CURSOR_AVAILABLE=true
export CODEX_BINARY_FOUND=true
export CURSOR_BINARY_FOUND=true
export LARCH_EXTERNAL_HEALTH_CHECK_TIMEOUT=30
export CLAUDE_PLUGIN_ROOT=<OPERATOR_REPO_PATH>/plugins/cache/larch-local/larch/50.0.5
