#!/usr/bin/env bash
# /design session env — generated by write-design-current-env.sh. Do not edit.
export DESIGN_TMPDIR=<TMPDIR>
export SESSION_TMPDIR=<TMPDIR>
export SESSION_ID=D3B111F7-D5CE-44D3-8B2B-017AD47A984B
export ISSUE_NUMBER=3032
export CODEX_PRESENT=true
export CURSOR_PRESENT=true
export CODEX_AVAILABLE=true
export CURSOR_AVAILABLE=true
export CLAUDE_PLUGIN_ROOT=<OPERATOR_REPO_PATH>/plugins/cache/larch-local/larch/45.0.0
